import type {
  MustHaveItem,
  PantryItem,
  ReceiptLineItem,
  ReceiptUpload,
} from "./grocery-types";

export const initialPantryItems: readonly PantryItem[] = [
  {
    id: "pantry-oats",
    ingredientId: "ingredient-oats",
    name: "Oats",
    canonicalName: "oats",
    category: "grains",
    quantity: 200,
    unit: "g",
    confidence: "medium",
    source: "mock",
    updatedAt: "2026-06-20",
    imageUrl: "/images/grocery/oats.svg",
    imageAlt: "Oats grocery placeholder",
  },
  {
    id: "pantry-skyr",
    ingredientId: "ingredient-skyr",
    name: "Skyr",
    canonicalName: "skyr",
    category: "dairy",
    quantity: 300,
    unit: "g",
    confidence: "high",
    source: "mock",
    updatedAt: "2026-06-20",
    expiresAt: "2026-06-25",
    imageUrl: "/images/grocery/skyr.svg",
    imageAlt: "Skyr grocery placeholder",
  },
  {
    id: "pantry-rice",
    ingredientId: "ingredient-rice",
    name: "Rice",
    canonicalName: "rice",
    category: "grains",
    quantity: 500,
    unit: "g",
    confidence: "medium",
    source: "mock",
    updatedAt: "2026-06-18",
    imageUrl: "/images/grocery/rice.svg",
    imageAlt: "Rice grocery placeholder",
  },
  {
    id: "pantry-eggs",
    ingredientId: "ingredient-eggs",
    name: "Eggs",
    canonicalName: "eggs",
    category: "dairy",
    quantity: 4,
    unit: "piece",
    confidence: "high",
    source: "mock",
    updatedAt: "2026-06-20",
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Eggs grocery placeholder",
  },
  {
    id: "pantry-tofu",
    ingredientId: "ingredient-tofu",
    name: "Tofu",
    canonicalName: "tofu",
    category: "dairy",
    quantity: 200,
    unit: "g",
    confidence: "medium",
    source: "mock",
    updatedAt: "2026-06-19",
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Tofu grocery placeholder",
  },
  {
    id: "pantry-vegetables",
    ingredientId: "ingredient-vegetables",
    name: "Vegetables",
    canonicalName: "vegetables",
    category: "produce",
    quantity: 300,
    unit: "g",
    confidence: "low",
    source: "mock",
    updatedAt: "2026-06-19",
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Vegetables grocery placeholder",
  },
  {
    id: "pantry-olive-oil",
    ingredientId: "ingredient-olive-oil",
    name: "Olive oil",
    canonicalName: "olive oil",
    category: "pantry",
    quantity: 250,
    unit: "ml",
    confidence: "medium",
    source: "mock",
    updatedAt: "2026-06-15",
    imageUrl: "/images/grocery/olive-oil.svg",
    imageAlt: "Olive oil grocery placeholder",
  },
];

export const initialMustHaveItems: readonly MustHaveItem[] = [
  {
    id: "must-water",
    ingredientId: "ingredient-water",
    name: "Water",
    canonicalName: "water",
    category: "drinks",
    desiredQuantity: 6,
    unit: "l",
    priority: "high",
    enabled: true,
    imageUrl: "/images/grocery/water.svg",
    imageAlt: "Water bottle grocery placeholder",
  },
  {
    id: "must-coffee",
    ingredientId: "ingredient-coffee",
    name: "Coffee",
    canonicalName: "coffee",
    category: "pantry",
    desiredQuantity: 250,
    unit: "g",
    priority: "normal",
    enabled: true,
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Coffee grocery placeholder",
  },
  {
    id: "must-oats",
    ingredientId: "ingredient-oats",
    name: "Oats",
    canonicalName: "oats",
    category: "grains",
    desiredQuantity: 500,
    unit: "g",
    priority: "normal",
    enabled: true,
    imageUrl: "/images/grocery/oats.svg",
    imageAlt: "Oats grocery placeholder",
  },
  {
    id: "must-rice",
    ingredientId: "ingredient-rice",
    name: "Rice",
    canonicalName: "rice",
    category: "grains",
    desiredQuantity: 500,
    unit: "g",
    priority: "normal",
    enabled: true,
    imageUrl: "/images/grocery/rice.svg",
    imageAlt: "Rice grocery placeholder",
  },
  {
    id: "must-olive-oil",
    ingredientId: "ingredient-olive-oil",
    name: "Olive oil",
    canonicalName: "olive oil",
    category: "pantry",
    desiredQuantity: 250,
    unit: "ml",
    priority: "normal",
    enabled: true,
    imageUrl: "/images/grocery/olive-oil.svg",
    imageAlt: "Olive oil grocery placeholder",
  },
  {
    id: "must-salt",
    ingredientId: "ingredient-salt",
    name: "Salt",
    canonicalName: "salt",
    category: "spices",
    priority: "low",
    enabled: true,
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Salt grocery placeholder",
  },
  {
    id: "must-toilet-paper",
    ingredientId: "ingredient-toilet-paper",
    name: "Toilet paper",
    canonicalName: "toilet paper",
    category: "household",
    desiredQuantity: 8,
    unit: "piece",
    priority: "high",
    enabled: true,
    imageUrl: "/images/grocery/toilet-paper.svg",
    imageAlt: "Toilet paper grocery placeholder",
  },
  {
    id: "must-dish-soap",
    ingredientId: "ingredient-dish-soap",
    name: "Dish soap",
    canonicalName: "dish soap",
    category: "household",
    priority: "normal",
    enabled: true,
    imageUrl: "/images/grocery/dish-soap.svg",
    imageAlt: "Dish soap grocery placeholder",
  },
  {
    id: "must-toothpaste",
    ingredientId: "ingredient-toothpaste",
    name: "Toothpaste",
    canonicalName: "toothpaste",
    category: "hygiene",
    priority: "normal",
    enabled: true,
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Toothpaste grocery placeholder",
  },
  {
    id: "must-trash-bags",
    ingredientId: "ingredient-trash-bags",
    name: "Trash bags",
    canonicalName: "trash bags",
    category: "household",
    priority: "normal",
    enabled: false,
    imageUrl: "/images/grocery/fallback.svg",
    imageAlt: "Trash bags grocery placeholder",
  },
];

export const initialReceiptUploads: readonly ReceiptUpload[] = [
  {
    id: "receipt-aldi-example",
    fileName: "aldi-receipt-example.jpg",
    uploadedAt: "2026-06-20",
    status: "pending_review",
    parserMode: "stub",
  },
];

export const initialReceiptLineItems: readonly ReceiptLineItem[] = [
  {
    id: "receipt-aldi-skyr",
    receiptUploadId: "receipt-aldi-example",
    rawLabel: "SKYR NATUR 500G",
    matchedIngredientId: "ingredient-skyr",
    name: "Skyr",
    category: "dairy",
    estimatedQuantity: 500,
    unit: "g",
    confidence: "medium",
    accepted: true,
  },
  {
    id: "receipt-aldi-oats",
    receiptUploadId: "receipt-aldi-example",
    rawLabel: "HAFERFLOCKEN 1KG",
    matchedIngredientId: "ingredient-oats",
    name: "Oats",
    category: "grains",
    estimatedQuantity: 1000,
    unit: "g",
    confidence: "medium",
    accepted: true,
  },
  {
    id: "receipt-aldi-chicken",
    receiptUploadId: "receipt-aldi-example",
    rawLabel: "HAEHNCHEN 400G",
    matchedIngredientId: "ingredient-chicken-breast",
    name: "Chicken breast",
    category: "meat_fish",
    estimatedQuantity: 400,
    unit: "g",
    confidence: "low",
    accepted: true,
  },
  {
    id: "receipt-aldi-potatoes",
    receiptUploadId: "receipt-aldi-example",
    rawLabel: "KARTOFFELN 1KG",
    matchedIngredientId: "ingredient-potatoes",
    name: "Potatoes",
    category: "produce",
    estimatedQuantity: 1000,
    unit: "g",
    confidence: "medium",
    accepted: true,
  },
];
