import type {
  EntityCollection,
  EntityMilestone,
  LifeGoal,
  LifeProject,
  LifeSkill,
  LifeTask,
} from "./types";

export const entityMilestones: readonly EntityMilestone[] = [
  {
    id: "milestone-life-os-entity-depth",
    title: "Entity detail routes usable",
    status: "active",
    dueDate: "2026-06-22",
    progress: 72,
    linkedTaskIds: [
      "task-portfolio-figma",
      "task-calendar-page",
      "task-run-quality-checks",
    ],
    linkedProjectId: "portfolio-life-os-app",
    linkedGoalId: "portfolio-life-os-mvp",
  },
  {
    id: "milestone-life-os-static-shell",
    title: "Static app skeleton stable",
    status: "planned",
    dueDate: "2026-06-24",
    progress: 58,
    linkedTaskIds: ["task-inbox-empty", "task-daily-review-closeout"],
    linkedProjectId: "portfolio-life-os-app",
    linkedGoalId: "portfolio-life-os-mvp",
  },
  {
    id: "milestone-thesis-source-decision",
    title: "Literature source decision closed",
    status: "blocked",
    dueDate: "2026-06-23",
    progress: 35,
    linkedTaskIds: ["task-literature-source", "task-literature-structure"],
    linkedProjectId: "portfolio-masterarbeit",
    linkedGoalId: "portfolio-masterarbeit-goal",
  },
  {
    id: "milestone-thesis-chapter-flow",
    title: "Chapter 2 writing flow protected",
    status: "planned",
    dueDate: "2026-06-28",
    progress: 42,
    linkedTaskIds: ["task-literature-structure"],
    linkedProjectId: "portfolio-masterarbeit",
    linkedGoalId: "portfolio-masterarbeit-goal",
  },
  {
    id: "milestone-java-practice-loop",
    title: "Consistent Java practice loop",
    status: "active",
    dueDate: "2026-06-27",
    progress: 41,
    linkedTaskIds: ["task-java-hyperskill-close", "task-hyperskill"],
    linkedProjectId: "project-java-hyperskill",
    linkedSkillId: "portfolio-java-hyperskill",
  },
  {
    id: "milestone-fi-note-outline",
    title: "Work notes sorted into wiki outline",
    status: "planned",
    dueDate: "2026-06-30",
    progress: 33,
    linkedTaskIds: ["task-fi-notes"],
    linkedProjectId: "portfolio-finanzinformatik",
    linkedGoalId: "goal-career-plan",
  },
  {
    id: "milestone-fitness-one-session",
    title: "One realistic session planned",
    status: "planned",
    dueDate: "2026-06-25",
    progress: 28,
    linkedTaskIds: ["task-workout-plan"],
    linkedGoalId: "goal-fitness-routine",
  },
  {
    id: "milestone-figma-v5-evidence",
    title: "Applied V5 layout evidence",
    status: "active",
    dueDate: "2026-06-26",
    progress: 52,
    linkedTaskIds: ["task-figma-practice", "task-portfolio-figma"],
    linkedProjectId: "portfolio-life-os-app",
    linkedSkillId: "portfolio-figma-design",
  },
] as const;

export const entityTasks: readonly LifeTask[] = [
  {
    id: "task-literature-structure",
    title: "Literaturstruktur ueberarbeiten",
    description:
      "Sort chapter 2.3 around three useful source clusters without opening new research branches.",
    status: "active",
    priority: "P1",
    date: "2026-06-22",
    startTime: "18:05",
    durationMinutes: 55,
    energy: "high",
    areaId: "education",
    projectId: "portfolio-masterarbeit",
    goalId: "portfolio-masterarbeit-goal",
    type: "deep-work",
    nextStep: "Move the three source clusters into the chapter outline.",
    resultNote: "Structure pass started; source decision still needs review.",
    reviewNeeded: true,
    source: "Dashboard Daily Control",
    timeline: [
      {
        label: "created",
        detail: "Promoted from thesis planning queue.",
        dateLabel: "2026-06-20",
      },
      {
        label: "started",
        detail: "Current focus block on dashboard.",
        dateLabel: "2026-06-22",
      },
      {
        label: "review pending",
        detail: "Check whether source triage blocks writing.",
        dateLabel: "Tonight",
      },
    ],
    evidence: [
      {
        title: "Chapter outline note",
        detail: "Evidence lives in Education / Scientific Work.",
        sourceLabel: "Scientific Work",
        href: "/education/scientific-work",
      },
    ],
    calendarBlockIds: ["block-literature-structure"],
  },
  {
    id: "task-java-hyperskill-close",
    title: "Java/Hyperskill abschliessen",
    description: "Finish one contained Java lesson block and record friction.",
    status: "planned",
    priority: "P2",
    date: "2026-06-22",
    startTime: "20:00",
    durationMinutes: 30,
    energy: "medium",
    areaId: "education",
    projectId: "project-java-hyperskill",
    skillId: "portfolio-java-hyperskill",
    type: "task",
    nextStep: "Complete the active lesson and write one friction note.",
    resultNote: "No result yet; planned for later today.",
    reviewNeeded: false,
    source: "Dashboard Daily Control queue",
    timeline: [
      {
        label: "planned",
        detail: "Queued after thesis focus block.",
        dateLabel: "Today",
      },
    ],
    evidence: [
      {
        title: "Learning log slot",
        detail: "Practice evidence should be added after completion.",
        sourceLabel: "Education / Learning Log",
        href: "/education/learning-log",
      },
    ],
  },
  {
    id: "task-daily-review-closeout",
    title: "Daily Review ausfuellen",
    description:
      "Close the day with outcome, open loops and tomorrow hint. Review is linked, not converted into a normal project.",
    status: "planned",
    priority: "P2",
    date: "2026-06-22",
    startTime: "21:30",
    durationMinutes: 15,
    energy: "low",
    areaId: "review",
    type: "review-trigger",
    nextStep: "Capture outcome, wins and one carry-forward item.",
    resultNote: "Awaiting evening closeout.",
    reviewNeeded: true,
    source: "Daily Control queue",
    timeline: [
      {
        label: "planned",
        detail: "Review trigger for the daily flow.",
        dateLabel: "Today",
      },
    ],
    evidence: [
      {
        title: "Daily review page",
        detail: "Review remains its own entity near Today and Calendar.",
        sourceLabel: "Daily Review",
        href: "/review/daily",
      },
    ],
  },
  {
    id: "task-inbox-triage",
    title: "Inbox triagieren",
    description: "Clarify three open Inbox items without starting side work.",
    status: "planned",
    priority: "P2",
    date: "2026-06-22",
    durationMinutes: 10,
    energy: "low",
    areaId: "review",
    type: "admin",
    nextStep: "Convert only items with a clear next action.",
    resultNote: "No triage run yet.",
    reviewNeeded: false,
    source: "Dashboard queue",
    timeline: [
      {
        label: "planned",
        detail: "Added as low-energy admin task.",
        dateLabel: "Today",
      },
    ],
    evidence: [
      {
        title: "Inbox",
        detail: "Inbox processing remains the source flow.",
        sourceLabel: "Inbox",
        href: "/inbox",
      },
    ],
    inboxItemIds: ["inbox-review-1", "inbox-review-2", "inbox-review-3"],
  },
  {
    id: "task-open-focus-buffer",
    title: "Open Focus Buffer neu planen",
    description:
      "Decide whether the blocked free slot should move, close or become a real task.",
    status: "waiting",
    priority: "P1",
    date: "2026-06-22",
    startTime: "13:30",
    durationMinutes: 60,
    energy: "medium",
    areaId: "review",
    type: "task",
    nextStep: "Choose reschedule or close during review.",
    resultNote: "Blocked because the slot has no current owner.",
    reviewNeeded: true,
    source: "Today Agenda block",
    timeline: [
      {
        label: "shifted",
        detail: "Focus buffer lost clear owner.",
        dateLabel: "Today",
      },
    ],
    evidence: [
      {
        title: "Calendar block",
        detail: "Calendar keeps the temporal projection.",
        sourceLabel: "Calendar",
        href: "/calendar?view=day&date=today&block=block-open-focus-buffer",
      },
    ],
    calendarBlockIds: ["block-open-focus-buffer"],
  },
  {
    id: "task-figma-practice",
    title: "Skill Practice: Figma",
    description:
      "Run a contained V5 spacing pass and record concrete evidence for the design skill.",
    status: "active",
    priority: "P1",
    date: "2026-06-22",
    startTime: "15:30",
    durationMinutes: 60,
    energy: "medium",
    areaId: "coding",
    projectId: "portfolio-life-os-app",
    goalId: "portfolio-life-os-mvp",
    skillId: "portfolio-figma-design",
    type: "task",
    nextStep: "Review one page against V5 spacing and component rules.",
    resultNote: "Practice is active; evidence note still open.",
    reviewNeeded: true,
    source: "Today Agenda skill block",
    timeline: [
      {
        label: "started",
        detail: "Marked active from Today Agenda.",
        dateLabel: "Today",
      },
    ],
    evidence: [
      {
        title: "Portfolio Page V1",
        detail: "Reference for applied layout practice.",
        sourceLabel: "Portfolio",
        href: "/portfolio",
      },
    ],
    calendarBlockIds: ["block-skill-practice-figma"],
  },
  {
    id: "task-calendar-page",
    title: "Calendar page implementieren",
    description: "Translate the accepted Calendar design into the static route.",
    status: "active",
    priority: "P1",
    date: "2026-06-23",
    durationMinutes: 45,
    energy: "high",
    areaId: "coding",
    projectId: "portfolio-life-os-app",
    goalId: "portfolio-life-os-mvp",
    type: "deep-work",
    nextStep: "Resolve remaining route validation checks.",
    resultNote: "Calendar route is usable; review panel remains mock based.",
    reviewNeeded: true,
    source: "Portfolio",
    timeline: [
      {
        label: "started",
        detail: "Moved from Portfolio attention list.",
        dateLabel: "This week",
      },
    ],
    evidence: [
      {
        title: "Calendar route",
        detail: "Temporal projection remains separate from Portfolio.",
        sourceLabel: "Calendar",
        href: "/calendar",
      },
    ],
  },
  {
    id: "task-portfolio-figma",
    title: "Portfolio page in Figma finalisieren",
    description: "Confirm V1 page contract and implementation handoff.",
    status: "waiting",
    priority: "P1",
    date: "2026-06-24",
    durationMinutes: 30,
    energy: "medium",
    areaId: "coding",
    projectId: "portfolio-life-os-app",
    goalId: "portfolio-life-os-mvp",
    skillId: "portfolio-figma-design",
    type: "task",
    nextStep: "Compare implementation with the accepted V1 node.",
    resultNote: "Review remains open.",
    reviewNeeded: true,
    source: "Portfolio",
    timeline: [
      {
        label: "review needed",
        detail: "Design handoff should stay reference only.",
        dateLabel: "This week",
      },
    ],
    evidence: [
      {
        title: "Portfolio V1 implementation",
        detail: "Workbench pattern, not a second dashboard.",
        sourceLabel: "Portfolio",
        href: "/portfolio",
      },
    ],
  },
  {
    id: "task-run-quality-checks",
    title: "Run lint and TypeScript checks",
    description: "Run the local validation commands and record failures clearly.",
    status: "planned",
    priority: "P1",
    date: "2026-06-22",
    durationMinutes: 25,
    energy: "medium",
    areaId: "system",
    projectId: "portfolio-life-os-app",
    goalId: "portfolio-life-os-mvp",
    type: "admin",
    nextStep: "Run lint, TypeScript and whitespace validation.",
    resultNote: "Pending validation run.",
    reviewNeeded: false,
    source: "Calendar scheduling queue",
    timeline: [
      {
        label: "planned",
        detail: "Added as QA task for implementation work.",
        dateLabel: "Today",
      },
    ],
    evidence: [],
  },
  {
    id: "task-inbox-empty",
    title: "Inbox empty state pruefen",
    description: "Check whether empty Inbox copy still guides capture triage.",
    status: "planned",
    priority: "P2",
    date: "2026-06-24",
    durationMinutes: 20,
    energy: "low",
    areaId: "system",
    projectId: "portfolio-life-os-app",
    goalId: "portfolio-life-os-mvp",
    type: "task",
    nextStep: "Review empty-state copy against the current Inbox route.",
    resultNote: "Copy review not started.",
    reviewNeeded: false,
    source: "Portfolio",
    timeline: [
      {
        label: "planned",
        detail: "Kept as a small static route quality check.",
        dateLabel: "2d ago",
      },
    ],
    evidence: [
      {
        title: "Inbox route",
        detail: "Empty state should reduce pressure and point to capture.",
        sourceLabel: "Inbox",
        href: "/inbox",
      },
    ],
  },
  {
    id: "task-literature-source",
    title: "Literature source deadline klaeren",
    description: "Confirm whether the next literature source blocks thesis work.",
    status: "waiting",
    priority: "P1",
    date: "2026-06-23",
    durationMinutes: 25,
    energy: "medium",
    areaId: "education",
    projectId: "portfolio-masterarbeit",
    goalId: "portfolio-masterarbeit-goal",
    type: "task",
    nextStep: "Decide source priority before the next writing block.",
    resultNote: "Blocked by source priority decision.",
    reviewNeeded: true,
    source: "Portfolio",
    timeline: [
      {
        label: "blocked",
        detail: "Source value must be decided before expanding reading list.",
        dateLabel: "Yesterday",
      },
    ],
    evidence: [
      {
        title: "Literature queue",
        detail: "Education Literature keeps the source context.",
        sourceLabel: "Education / Literature",
        href: "/education/literature",
      },
    ],
  },
  {
    id: "task-hyperskill",
    title: "Hyperskill lesson block abschliessen",
    description: "Finish one contained Java learning block without scope creep.",
    status: "active",
    priority: "P2",
    date: "2026-06-27",
    durationMinutes: 50,
    energy: "medium",
    areaId: "education",
    projectId: "project-java-hyperskill",
    skillId: "portfolio-java-hyperskill",
    type: "task",
    nextStep: "Complete lesson and record one friction point.",
    resultNote: "Lesson is in progress.",
    reviewNeeded: false,
    source: "Portfolio",
    timeline: [
      {
        label: "started",
        detail: "Learning block opened from skill practice.",
        dateLabel: "2d ago",
      },
    ],
    evidence: [
      {
        title: "Learning log",
        detail: "One short friction note is enough for MVP.",
        sourceLabel: "Education / Learning Log",
        href: "/education/learning-log",
      },
    ],
  },
  {
    id: "task-weekly-review",
    title: "Weekly review vorbereiten",
    description: "Collect open loops, wins, blockers and carry-forward items.",
    status: "planned",
    priority: "P2",
    date: "2026-06-28",
    durationMinutes: 35,
    energy: "low",
    areaId: "review",
    type: "review-trigger",
    nextStep: "Draft open loops before the Calendar review panel work.",
    resultNote: "No review note yet.",
    reviewNeeded: true,
    source: "Portfolio",
    timeline: [
      {
        label: "planned",
        detail: "Weekly review remains a review entity.",
        dateLabel: "This week",
      },
    ],
    evidence: [
      {
        title: "Calendar",
        detail: "Review stays Calendar/Today-near.",
        sourceLabel: "Calendar",
        href: "/calendar",
      },
    ],
  },
  {
    id: "task-fi-notes",
    title: "FI notes strukturieren",
    description: "Convert scattered work notes into a small Work Wiki outline.",
    status: "planned",
    priority: "P2",
    date: "2026-06-30",
    durationMinutes: 40,
    energy: "medium",
    areaId: "work",
    projectId: "portfolio-finanzinformatik",
    goalId: "goal-career-plan",
    type: "task",
    nextStep: "Group notes by system, decision and follow-up.",
    resultNote: "No wiki outline yet.",
    reviewNeeded: false,
    source: "Portfolio",
    timeline: [
      {
        label: "planned",
        detail: "Work notes stay private and scoped.",
        dateLabel: "3d ago",
      },
    ],
    evidence: [
      {
        title: "Work Wiki",
        detail: "Only durable context moves to the wiki.",
        sourceLabel: "Work / Wiki",
        href: "/work/wiki",
      },
    ],
  },
  {
    id: "task-workout-plan",
    title: "Workout planen",
    description: "Plan the next strength or running slot around weekly load.",
    status: "planned",
    priority: "P3",
    date: "2026-06-25",
    durationMinutes: 15,
    energy: "low",
    areaId: "health",
    goalId: "goal-fitness-routine",
    type: "task",
    nextStep: "Pick one realistic session and a recovery note.",
    resultNote: "Workout detail belongs to Health later.",
    reviewNeeded: false,
    source: "Portfolio",
    timeline: [
      {
        label: "planned",
        detail: "Health action is linked, not turned into a project.",
        dateLabel: "This week",
      },
    ],
    evidence: [
      {
        title: "Health trackers",
        detail: "Workout/run details should live under Health.",
        sourceLabel: "Health / Running",
        href: "/health/running",
      },
    ],
  },
  {
    id: "task-protein-bowl",
    title: "Protein Bowl vorbereiten",
    description: "Prepare a simple meal option that supports the week.",
    status: "planned",
    priority: "P3",
    date: "2026-06-25",
    durationMinutes: 20,
    energy: "low",
    areaId: "nutrition",
    type: "task",
    nextStep: "Check ingredients and choose one recipe.",
    resultNote: "Meal detail belongs to Nutrition later.",
    reviewNeeded: false,
    source: "Portfolio",
    timeline: [
      {
        label: "planned",
        detail: "Meal prep supports the day without becoming a portfolio type.",
        dateLabel: "This week",
      },
    ],
    evidence: [
      {
        title: "Meal Planner",
        detail: "Recipe and meal detail stays in Nutrition.",
        sourceLabel: "Nutrition / Meal Planner",
        href: "/nutrition/meal-planner",
      },
    ],
  },
] as const;

export const entityProjects: readonly LifeProject[] = [
  {
    id: "portfolio-life-os-app",
    title: "Life OS App",
    description: "Core app implementation and static V5 route coverage.",
    status: "active",
    areaId: "coding",
    goalId: "portfolio-life-os-mvp",
    skillIds: ["portfolio-figma-design"],
    nextStep: "Plan the next implementation task after entity detail pages.",
    progress: 56,
    deadline: "2026-06-24",
    focusThisWeek: true,
    risk: "Static app scope can drift into data binding too early.",
    blocker: "None; validation remains the main gate.",
    priority: "P1",
    phase: "Static app skeleton",
    taskIds: [
      "task-calendar-page",
      "task-portfolio-figma",
      "task-run-quality-checks",
      "task-inbox-empty",
      "task-figma-practice",
    ],
    milestoneIds: [
      "milestone-life-os-entity-depth",
      "milestone-life-os-static-shell",
    ],
    notes: [
      {
        title: "Source-of-truth boundary",
        detail: "Phase 2 stays static and mock based until manual flow is stable.",
        sourceLabel: "ROADMAP.md",
      },
    ],
    activity: [
      {
        label: "last task completed",
        detail: "Portfolio route moved from skeleton to static workbench.",
        dateLabel: "today",
      },
      {
        label: "plan changed",
        detail: "Entity depth promoted before Supabase work.",
        dateLabel: "today",
      },
    ],
  },
  {
    id: "portfolio-masterarbeit",
    title: "Masterarbeit",
    description: "Thesis writing, sources and deadline control.",
    status: "active",
    areaId: "education",
    goalId: "portfolio-masterarbeit-goal",
    nextStep: "Protect the next literature and writing block.",
    progress: 42,
    deadline: "2026-07-31",
    focusThisWeek: true,
    risk: "Source triage can delay actual writing output.",
    blocker: "Literature source priority decision is open.",
    priority: "P1",
    phase: "Chapter structure",
    taskIds: ["task-literature-structure", "task-literature-source"],
    milestoneIds: [
      "milestone-thesis-source-decision",
      "milestone-thesis-chapter-flow",
    ],
    notes: [
      {
        title: "Writing boundary",
        detail: "No new source rabbit hole before the current chapter pass.",
        sourceLabel: "Scientific Work",
        href: "/education/scientific-work",
      },
    ],
    activity: [
      {
        label: "decision opened",
        detail: "Source first or writing first needs review.",
        dateLabel: "yesterday",
      },
    ],
  },
  {
    id: "project-java-hyperskill",
    title: "Java / Hyperskill",
    description: "Structured Java learning through contained practice blocks.",
    status: "active",
    areaId: "education",
    skillIds: ["portfolio-java-hyperskill"],
    nextStep: "Finish the active lesson block.",
    progress: 41,
    deadline: "2026-06-27",
    focusThisWeek: true,
    priority: "P2",
    phase: "Practice loop",
    taskIds: ["task-java-hyperskill-close", "task-hyperskill"],
    milestoneIds: ["milestone-java-practice-loop"],
    notes: [
      {
        title: "Evidence rule",
        detail: "Practice evidence beats course collection.",
        sourceLabel: "Learning Log",
        href: "/education/learning-log",
      },
    ],
    activity: [
      {
        label: "practice started",
        detail: "Active lesson block opened.",
        dateLabel: "2d ago",
      },
    ],
  },
  {
    id: "portfolio-finanzinformatik",
    title: "Finanzinformatik notes aufbereiten",
    description: "Work notes, decisions and reusable context for FI tasks.",
    status: "active",
    areaId: "work",
    goalId: "goal-career-plan",
    nextStep: "Structure notes into work wiki and follow-up buckets.",
    progress: 33,
    deadline: "2026-06-30",
    focusThisWeek: false,
    risk: "Confidential work context must stay scoped.",
    priority: "P2",
    phase: "Outline",
    taskIds: ["task-fi-notes"],
    milestoneIds: ["milestone-fi-note-outline"],
    notes: [
      {
        title: "Privacy note",
        detail: "Only durable, non-sensitive structure belongs in the app mock.",
        sourceLabel: "Work / Wiki",
        href: "/work/wiki",
      },
    ],
    activity: [
      {
        label: "last touched",
        detail: "Follow-up buckets identified.",
        dateLabel: "3d ago",
      },
    ],
  },
] as const;

export const entityGoals: readonly LifeGoal[] = [
  {
    id: "portfolio-life-os-mvp",
    title: "Life OS MVP nutzbar machen",
    description: "Reach a usable static app before adding persistence.",
    status: "active",
    horizon: "month",
    why: "Anton should be able to use the manual daily flow before data binding begins.",
    measure: "Static core routes usable with no dead navigation links.",
    currentValue: "Portfolio, Calendar and entity routes in progress",
    targetValue: "All MVP route skeletons navigable",
    remaining: "Entity depth, resources and validation",
    progress: 58,
    nextStep: "Finish entity detail pages and validate static routes.",
    areaId: "coding",
    linkedProjectIds: ["portfolio-life-os-app"],
    linkedTaskIds: [
      "task-calendar-page",
      "task-portfolio-figma",
      "task-run-quality-checks",
    ],
    milestoneIds: [
      "milestone-life-os-entity-depth",
      "milestone-life-os-static-shell",
    ],
    reviewNotes: [
      {
        title: "Weekly review prompt",
        detail: "Start data binding only after manual source-of-truth is stable.",
        sourceLabel: "ROADMAP.md",
      },
    ],
  },
  {
    id: "portfolio-masterarbeit-goal",
    title: "Masterarbeit abgeben",
    description: "Keep thesis output moving while source work stays bounded.",
    status: "active",
    horizon: "quarter",
    why: "The thesis needs protected output time, not unlimited source triage.",
    measure: "Chapter structure and source decisions closed before deadline.",
    currentValue: "Chapter structure active, source decision blocked",
    targetValue: "Submission-ready thesis package",
    remaining: "Source decision, chapter pass, final review",
    progress: 37,
    nextStep: "Resolve literature source deadline and protect writing time.",
    areaId: "education",
    linkedProjectIds: ["portfolio-masterarbeit"],
    linkedTaskIds: ["task-literature-structure", "task-literature-source"],
    milestoneIds: [
      "milestone-thesis-source-decision",
      "milestone-thesis-chapter-flow",
    ],
    reviewNotes: [
      {
        title: "Open decision",
        detail: "Choose whether writing moves before source cleanup.",
        sourceLabel: "Weekly Review",
        href: "/review/daily",
      },
    ],
  },
  {
    id: "goal-fitness-routine",
    title: "Fitness-Routine stabilisieren",
    description: "Make health actions consistent without overloading the day.",
    status: "active",
    horizon: "month",
    why: "Training should support energy instead of competing with P0 work.",
    measure: "One realistic workout and recovery cue per planning cycle.",
    currentValue: "Next workout not yet selected",
    targetValue: "Repeatable weekly health baseline",
    remaining: "Pick next session and recovery note",
    progress: 28,
    nextStep: "Plan one workout and one recovery cue.",
    areaId: "health",
    linkedProjectIds: [],
    linkedTaskIds: ["task-workout-plan"],
    milestoneIds: ["milestone-fitness-one-session"],
    reviewNotes: [
      {
        title: "Domain boundary",
        detail: "Workout/run detail should live under Health later.",
        sourceLabel: "Health",
        href: "/health",
      },
    ],
  },
  {
    id: "goal-career-plan",
    title: "Finanz-/Karriere-Plan strukturieren",
    description: "Keep work learning, notes and career decisions connected.",
    status: "draft",
    horizon: "someday",
    why: "Career decisions need context, but should stay low-pressure now.",
    measure: "One useful next decision named during review.",
    currentValue: "Work notes exist, goal is not promoted",
    targetValue: "Clear career direction note",
    remaining: "Review promotion decision",
    progress: 14,
    nextStep: "List the next useful career decision.",
    areaId: "work",
    linkedProjectIds: ["portfolio-finanzinformatik"],
    linkedTaskIds: ["task-fi-notes"],
    milestoneIds: ["milestone-fi-note-outline"],
    reviewNotes: [
      {
        title: "Review condition",
        detail: "Keep low pressure until a weekly review promotes it.",
        sourceLabel: "Work Log",
        href: "/work/log",
      },
    ],
  },
] as const;

export const entitySkills: readonly LifeSkill[] = [
  {
    id: "portfolio-java-hyperskill",
    title: "Java / Hyperskill",
    description: "Java practice through contained lessons and applied notes.",
    areaId: "education",
    status: "learning",
    currentLevel: "Foundation",
    targetLevel: "Applied project confidence",
    progress: 41,
    nextPractice: "Complete the active lesson and record one friction point.",
    lastPracticedAt: "2026-06-20",
    practiceFrequency: "2 contained sessions per week",
    linkedTaskIds: ["task-java-hyperskill-close", "task-hyperskill"],
    linkedProjectIds: ["project-java-hyperskill"],
    linkedGoalIds: [],
    milestoneIds: ["milestone-java-practice-loop"],
    learningPath: [
      {
        title: "Foundation",
        status: "active",
        detail: "Syntax and basic problem solving.",
      },
      {
        title: "Practice",
        status: "planned",
        detail: "Repeat small lessons without scope creep.",
      },
      {
        title: "Application",
        status: "planned",
        detail: "Apply in one small Life OS or study utility.",
      },
      {
        title: "Review",
        status: "planned",
        detail: "Record friction and next practice cue.",
      },
      {
        title: "Maintenance",
        status: "planned",
        detail: "Keep a light recurring practice slot.",
      },
    ],
    evidence: [
      {
        title: "Hyperskill lesson block",
        detail: "Evidence expected after the active lesson is closed.",
        sourceLabel: "Learning Log",
        href: "/education/learning-log",
      },
    ],
  },
  {
    id: "portfolio-figma-design",
    title: "Figma Layout Practice",
    description: "Practice calm, buildable Life OS page layouts in Figma.",
    areaId: "coding",
    status: "practicing",
    currentLevel: "Review-capable",
    targetLevel: "Reliable V5 handoff",
    progress: 52,
    nextPractice: "Run a 30 min layout review against V5 rules.",
    lastPracticedAt: "2026-06-22",
    practiceFrequency: "1 review pass per implementation loop",
    linkedTaskIds: ["task-figma-practice", "task-portfolio-figma"],
    linkedProjectIds: ["portfolio-life-os-app"],
    linkedGoalIds: ["portfolio-life-os-mvp"],
    milestoneIds: ["milestone-figma-v5-evidence"],
    learningPath: [
      {
        title: "Foundation",
        status: "done",
        detail: "Understands V5 surfaces, hierarchy and hard limits.",
      },
      {
        title: "Practice",
        status: "active",
        detail: "Review page layouts against component rules.",
      },
      {
        title: "Application",
        status: "active",
        detail: "Apply to Life OS entity and area pages.",
      },
      {
        title: "Review",
        status: "planned",
        detail: "Write concise evidence notes.",
      },
      {
        title: "Maintenance",
        status: "planned",
        detail: "Keep V5 checks small and repeatable.",
      },
    ],
    evidence: [
      {
        title: "Portfolio Page V1",
        detail: "Applied as calm workbench reference.",
        sourceLabel: "Portfolio",
        href: "/portfolio",
      },
    ],
  },
  {
    id: "skill-life-os-product-thinking",
    title: "Life OS Product Thinking",
    description: "Keep routes, page contracts and source-of-truth boundaries coherent.",
    areaId: "system",
    status: "maintaining",
    currentLevel: "Operational",
    targetLevel: "Reliable implementation reviewer",
    progress: 64,
    nextPractice: "Review one new page contract against Product/Data rules.",
    lastPracticedAt: "2026-06-21",
    practiceFrequency: "Every route implementation",
    linkedTaskIds: ["task-inbox-triage", "task-weekly-review"],
    linkedProjectIds: ["portfolio-life-os-app"],
    linkedGoalIds: ["portfolio-life-os-mvp"],
    milestoneIds: [],
    learningPath: [
      {
        title: "Foundation",
        status: "done",
        detail: "Product model and route types are understood.",
      },
      {
        title: "Practice",
        status: "done",
        detail: "Used in Portfolio and Calendar alignment.",
      },
      {
        title: "Application",
        status: "active",
        detail: "Apply to entity depth pages.",
      },
      {
        title: "Review",
        status: "active",
        detail: "Check no page creates a second source of truth.",
      },
      {
        title: "Maintenance",
        status: "planned",
        detail: "Keep docs and routes aligned.",
      },
    ],
    evidence: [
      {
        title: "Pages and Routes alignment",
        detail: "Portfolio entity routes stay global, not nested.",
        sourceLabel: "pages-and-routes.md",
      },
    ],
  },
  {
    id: "skill-research-writing",
    title: "Research Writing",
    description: "Thesis writing, evidence selection and argument structure.",
    areaId: "education",
    status: "learning",
    currentLevel: "Evidence selection",
    targetLevel: "Submission-ready argument flow",
    progress: 35,
    nextPractice: "Resolve the source decision and write the next paragraph.",
    lastPracticedAt: "2026-06-21",
    practiceFrequency: "One protected writing drill after source decisions",
    linkedTaskIds: ["task-literature-structure", "task-literature-source"],
    linkedProjectIds: ["portfolio-masterarbeit"],
    linkedGoalIds: ["portfolio-masterarbeit-goal"],
    milestoneIds: [
      "milestone-thesis-source-decision",
      "milestone-thesis-chapter-flow",
    ],
    learningPath: [
      {
        title: "Foundation",
        status: "active",
        detail: "Source choice and argument structure.",
      },
      {
        title: "Practice",
        status: "blocked",
        detail: "Writing drill waits on the source decision.",
      },
      {
        title: "Application",
        status: "planned",
        detail: "Apply to the next thesis chapter section.",
      },
      {
        title: "Review",
        status: "planned",
        detail: "Check evidence strength during weekly review.",
      },
      {
        title: "Maintenance",
        status: "planned",
        detail: "Keep writing blocks bounded.",
      },
    ],
    evidence: [
      {
        title: "Source decision note",
        detail: "Evidence is currently blocked by decision quality, not effort.",
        sourceLabel: "Education / Literature",
        href: "/education/literature",
      },
    ],
  },
  {
    id: "skill-ai-agent-workflow",
    title: "AI Agent Workflow",
    description: "Use agent prompts, skills and review loops safely.",
    areaId: "coding",
    status: "practicing",
    currentLevel: "Scoped implementation loops",
    targetLevel: "Reliable agent handoff and review",
    progress: 47,
    nextPractice: "Review one scoped Codex prompt against root truths.",
    lastPracticedAt: "2026-06-22",
    practiceFrequency: "Every agent-assisted implementation",
    linkedTaskIds: ["task-weekly-review", "task-run-quality-checks"],
    linkedProjectIds: ["portfolio-life-os-app"],
    linkedGoalIds: ["portfolio-life-os-mvp"],
    milestoneIds: [],
    learningPath: [
      {
        title: "Foundation",
        status: "done",
        detail: "Root truths and skill activation rules are understood.",
      },
      {
        title: "Practice",
        status: "active",
        detail: "Keep prompts scoped to small reviewable changes.",
      },
      {
        title: "Application",
        status: "active",
        detail: "Apply to Life OS implementation loops.",
      },
      {
        title: "Review",
        status: "planned",
        detail: "Validate outcomes without granting broad tool access.",
      },
      {
        title: "Maintenance",
        status: "planned",
        detail: "Avoid external tool expansion before risk review.",
      },
    ],
    evidence: [
      {
        title: "AI Workflow rules",
        detail: "External tools wait until scope, rights and risk are clear.",
        sourceLabel: "AI_WORKFLOW.md",
      },
    ],
  },
] as const;

export const entityCollection = {
  tasks: entityTasks,
  projects: entityProjects,
  goals: entityGoals,
  skills: entitySkills,
  milestones: entityMilestones,
} as const satisfies EntityCollection;
