"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { EmptyState, Pill } from "@/components/layout/route-page-primitives";
import {
  createEducationLiteratureFormAction,
  createEducationProjectFormAction,
  linkEducationLiteratureFormAction,
  unlinkEducationLiteratureFormAction,
  updateEducationLiteratureFormAction,
  updateEducationProjectFormAction,
} from "@/features/real-data/actions/education.actions";
import type { EducationOverviewViewModel } from "./types";

const input = "min-h-8 rounded-[9px] border border-[var(--border-subtle)] bg-[rgba(7,11,18,.78)] px-2 text-[11px] text-[var(--text-primary)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--focus-ring)]";
const button = "min-h-8 rounded-full border border-[rgba(95,200,215,.34)] bg-[rgba(95,200,215,.12)] px-3 text-[10px] font-semibold text-[var(--text-primary)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--focus-ring)]";
const panel = "min-w-0 rounded-[18px] border border-[var(--border-subtle)] bg-[rgba(15,23,36,.86)] p-3 shadow-[0_8px_22px_rgba(0,0,0,.12)]";
const statuses = ["idea", "active", "paused", "blocked", "completed", "archived"];
const types = ["research", "source", "link", "learning", "note"];
const messages: Record<string, string> = { blocked: "Anmeldung erforderlich.", literature_created: "Literatur erstellt und verknüpft.", literature_error: "Literatur konnte nicht gespeichert werden.", literature_linked: "Literatur verknüpft.", literature_unlinked: "Literaturverknüpfung gelöst.", literature_updated: "Literatur aktualisiert.", project_created: "Education Project erstellt.", project_error: "Education Project konnte nicht gespeichert werden.", project_updated: "Education Project aktualisiert." };

function Field({ children, label }: Readonly<{ children: React.ReactNode; label: string }>) { return <label className="grid gap-1 text-[10px] font-semibold text-[var(--text-muted)]"><span>{label}</span>{children}</label>; }

export function EducationManualWorkspace({ viewModel }: Readonly<{ viewModel: EducationOverviewViewModel }>) {
  const params = useSearchParams();
  const workspace = viewModel.manualWorkspace!;
  const selectedId = params.get("selected") ?? workspace.projects[0]?.id;
  const project = workspace.projects.find((item) => item.id === selectedId) ?? workspace.projects[0] ?? null;
  const selectedResourceId = params.get("resource");
  const selectedResource = project?.literature.find((item) => item.id === selectedResourceId) ?? project?.literature[0] ?? null;
  const action = params.get("educationAction");
  const availableResources = workspace.resources.filter((resource) => !project?.literature.some((item) => item.id === resource.id));

  return <div className="mx-auto flex w-full max-w-[2208px] flex-col gap-2 pb-6" id="education-overview-page">
    <header className={panel}><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[var(--accent-cyan)]">Life OS / Education</p><h1 className="mt-1 text-[24px] font-semibold text-[var(--text-primary)]">Education Projects & Literature</h1><p className="mt-1 text-[11px] text-[var(--text-secondary)]">Kanonische Projects, Tasks, Deadlines und Resources für Research- und Thesis-Kontexte.</p></header>
    {action && messages[action] ? <div className={panel} data-education-action-status role="status">{messages[action]}</div> : null}
    {!workspace.authAvailable ? <div className={panel}><EmptyState title="Education ist auth-blocked" description="Melde dich lokal an, um Education-Daten zu verwalten." /></div> : null}
    <div className="grid gap-2 xl:h-[calc(100vh-220px)] xl:min-h-[500px] xl:grid-cols-12">
      <section aria-label="Education Projects" className={`${panel} xl:col-span-3 xl:overflow-y-auto`} data-education-region="projects"><h2 className="text-[14px] font-semibold text-[var(--text-primary)]">Aktive Education Projects</h2><div className="mt-2 grid gap-2">{workspace.projects.length ? workspace.projects.map((item) => <Link className="rounded-[11px] border border-[var(--border-subtle)] p-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--focus-ring)]" data-education-project-card href={`/education?selected=${item.id}`} key={item.id}><span className="block text-[11px] font-semibold text-[var(--text-primary)]">{item.title}</span><span className="text-[10px] text-[var(--text-muted)]">{item.status} · {item.tasks.length} Tasks · {item.literature.length} Sources</span></Link>) : <EmptyState title="Keine Education Projects" description="Erstelle das erste kanonische Education Project." />}</div>
        {workspace.authAvailable ? <form action={createEducationProjectFormAction} aria-label="Education Project erstellen" className="mt-3 grid gap-2"><Field label="Titel"><input className={input} name="title" required /></Field><Field label="Beschreibung"><textarea className={input} name="description" /></Field><Field label="Status"><select className={input} defaultValue="active" name="status">{statuses.map((status) => <option key={status}>{status}</option>)}</select></Field><button className={button}>Education Project erstellen</button></form> : null}
      </section>
      <section aria-label="Education Project Context" className={`${panel} xl:col-span-4 xl:overflow-y-auto`} data-education-region="project-context">{project ? <><div className="flex justify-between gap-2"><div><h2 className="text-[17px] font-semibold text-[var(--text-primary)]">{project.title}</h2><p className="mt-1 text-[11px] text-[var(--text-secondary)]">{project.description || "Keine Beschreibung."}</p></div><Pill>{project.status}</Pill></div><Link className={`${button} mt-2 inline-flex items-center`} href={`/portfolio?view=projects&selected=${project.id}`}>Project öffnen</Link>
        <form action={updateEducationProjectFormAction} aria-label="Education Project bearbeiten" className="mt-3 grid gap-2"><input name="projectId" type="hidden" value={project.id} /><Field label="Titel"><input className={input} defaultValue={project.title} name="title" required /></Field><Field label="Beschreibung"><textarea className={input} defaultValue={project.description ?? ""} name="description" /></Field><Field label="Status"><select className={input} defaultValue={project.status} name="status">{statuses.map((status) => <option key={status}>{status}</option>)}</select></Field><button className={button}>Project speichern</button></form>
        <section aria-label="Education Tasks and Deadlines" className="mt-3"><h3 className="text-[12px] font-semibold text-[var(--text-primary)]">Tasks & Deadlines</h3>{project.tasks.length ? <ul className="mt-2 grid gap-1">{project.tasks.map((task) => <li className="rounded-[9px] border border-[var(--border-subtle)] p-2" key={task.id}><Link className="text-[10px] text-[var(--accent-cyan)]" href={`/portfolio?view=tasks&selected=${task.id}`}>{task.title}</Link><p className="text-[9px] text-[var(--text-muted)]">{task.status} · Deadline {task.dueAt?.slice(0, 10) ?? task.plannedDate ?? "nicht gesetzt"}</p></li>)}</ul> : <p className="mt-1 text-[10px] text-[var(--text-muted)]">Keine verknüpften Tasks oder Deadlines.</p>}</section></> : <EmptyState title="Kein Project ausgewählt" description="Erstelle oder wähle ein Education Project." />}</section>
      <section aria-label="Education Literature" className={`${panel} xl:col-span-5 xl:overflow-y-auto`} data-education-region="literature"><h2 className="text-[14px] font-semibold text-[var(--text-primary)]">Literature / Sources</h2>{project ? <>
        <div className="mt-2 grid gap-2">{project.literature.length ? project.literature.map((resource) => <article className="rounded-[11px] border border-[var(--border-subtle)] p-2" data-education-resource-card key={resource.id}><div className="flex justify-between gap-2"><Link className="text-[11px] font-semibold text-[var(--accent-cyan)]" href={`/education?selected=${project.id}&resource=${resource.id}`}>{resource.title}</Link><Pill>{resource.type}</Pill></div><p className="mt-1 text-[10px] text-[var(--text-muted)]">{resource.relationType} · {resource.url ?? "Keine URL"}</p><form action={unlinkEducationLiteratureFormAction} aria-label={`Literatur lösen ${resource.title}`} className="mt-1"><input name="projectId" type="hidden" value={project.id} /><input name="relationId" type="hidden" value={resource.relationId} /><button className="text-[10px] text-[var(--accent-red)]">Verknüpfung lösen</button></form></article>) : <p className="text-[10px] text-[var(--text-muted)]">Keine Literatur verknüpft.</p>}</div>
        <form action={createEducationLiteratureFormAction} aria-label="Literatur erstellen" className="mt-3 grid gap-2 rounded-[11px] border border-[var(--border-subtle)] p-2"><input name="projectId" type="hidden" value={project.id} /><Field label="Titel"><input className={input} name="title" required /></Field><Field label="Notiz"><textarea className={input} name="body" /></Field><Field label="URL"><input className={input} name="url" type="url" /></Field><Field label="Resource-Typ"><select className={input} defaultValue="research" name="type">{types.map((type) => <option key={type}>{type}</option>)}</select></Field><button className={button}>Literatur speichern und verknüpfen</button></form>
        <form action={linkEducationLiteratureFormAction} aria-label="Bestehende Resource verknüpfen" className="mt-3 grid gap-2"><input name="projectId" type="hidden" value={project.id} /><Field label="Resource"><select className={input} name="resourceId" required><option value="">Resource wählen</option>{availableResources.map((resource) => <option key={resource.id} value={resource.id}>{resource.title} · {resource.type}</option>)}</select></Field><button className={button} disabled={!availableResources.length}>Resource verknüpfen</button></form>
        {selectedResource ? <form action={updateEducationLiteratureFormAction} aria-label="Literatur bearbeiten" className="mt-3 grid gap-2 rounded-[11px] border border-[var(--border-subtle)] p-2"><input name="projectId" type="hidden" value={project.id} /><input name="resourceId" type="hidden" value={selectedResource.id} /><h3 className="text-[12px] font-semibold text-[var(--text-primary)]">Resource Detail</h3><Field label="Titel"><input className={input} defaultValue={selectedResource.title} name="title" required /></Field><Field label="Notiz"><textarea className={input} defaultValue={selectedResource.body ?? ""} name="body" /></Field><Field label="URL"><input className={input} defaultValue={selectedResource.url ?? ""} name="url" type="url" /></Field><Field label="Resource-Typ"><select className={input} defaultValue={selectedResource.type} name="type">{types.map((type) => <option key={type}>{type}</option>)}</select></Field><button className={button}>Literatur aktualisieren</button><Link className="text-[10px] text-[var(--accent-cyan)]" href={`/resources?selected=${selectedResource.id}`}>Resource öffnen</Link></form> : null}
      </> : <EmptyState title="Kein Literaturkontext" description="Wähle zuerst ein Education Project." />}</section>
    </div>
  </div>;
}
