import type {
  LearningInsight,
  LearningSession,
  LearningTrack,
  LiteratureItem,
  MasterThesisMilestone,
  MasterThesisState,
  PracticeQueueItem,
  ResearchField,
  ResearchIdea,
  ResearchNote,
  ResearchQuestion,
  WeeklyLearningDay,
} from "./types";

export const mockResearchFields: ResearchField[] = [
  {
    id: "field-human-ai",
    title: "Human-AI Interaction",
    description:
      "Wie Menschen KI-Agenten, Assistenzsysteme und Review-Pflichten in Wissensarbeit akzeptieren und steuern.",
    status: "active",
    ideaCount: 2,
    literatureCount: 2,
    openQuestionCount: 2,
    nextAction: "Begriffe fuer Vertrauen, Kontrolle und Review sauber trennen.",
  },
  {
    id: "field-pkm",
    title: "Personal Knowledge Management",
    description:
      "Persoenliche Wissenssysteme, Notizen, Quellenarbeit und die Vermeidung von Wissensfriedhoefen.",
    status: "active",
    ideaCount: 1,
    literatureCount: 1,
    openQuestionCount: 1,
    nextAction: "PKM-Modelle gegen Life-OS-Workflow abgleichen.",
  },
  {
    id: "field-information-systems",
    title: "Information Systems",
    description:
      "Digitale Systeme als organisatorische Steuerungsflaechen mit klaren Daten- und Prozessgrenzen.",
    status: "watching",
    ideaCount: 1,
    literatureCount: 1,
    openQuestionCount: 1,
    nextAction: "Moegliche Theorieanker fuer persoenliche Productivity Apps sammeln.",
  },
  {
    id: "field-learning-analytics",
    title: "Learning Analytics",
    description:
      "Lernverhalten, Reflexion und digitale Lernsignale ohne automatische Leistungsbewertung.",
    status: "watching",
    ideaCount: 1,
    literatureCount: 1,
    openQuestionCount: 1,
    nextAction: "Abgrenzen, was ohne externe Auswertung im MVP sichtbar sein darf.",
  },
  {
    id: "field-privacy",
    title: "Privacy by Design",
    description:
      "Datensparsamkeit, Zugriffskontrolle und transparente Verarbeitung in persoenlichen Systemen.",
    status: "active",
    ideaCount: 1,
    literatureCount: 1,
    openQuestionCount: 0,
    nextAction: "Privacy-Kriterien als Bewertungsraster fuer App-Architektur vorbereiten.",
  },
  {
    id: "field-calm-technology",
    title: "Calm Technology",
    description:
      "Ruhige Systeme, die Aufmerksamkeit respektieren und Entscheidungen ohne Druck vorbereiten.",
    status: "watching",
    ideaCount: 2,
    literatureCount: 1,
    openQuestionCount: 1,
    nextAction: "Calm-Prinzipien als Design- und Forschungskriterien formulieren.",
  },
];

export const mockResearchIdeas: ResearchIdea[] = [
  {
    id: "idea-ai-agents",
    title: "KI-Agenten als persönliche Produktivitätsassistenten",
    status: "exploring",
    workType: "master_thesis",
    fieldId: "field-human-ai",
    fieldTitle: "Human-AI Interaction",
    thesisPotential: "high",
    summary:
      "Untersucht, wie Agenten persönliche Planung, Recherche und Review unterstützen koennen, ohne Autonomie oder Vertrauen zu ueberziehen.",
    researchQuestion:
      "Wie kann Review-Pflicht Vertrauen in Agentenoutputs erhöhen?",
    nextAction: "3 Kernquellen lesen und Argumentationslinie skizzieren",
    sourceCount: 5,
    noteCount: 4,
    openQuestionCount: 2,
    updatedAt: "2026-06-20T13:30:00.000Z",
  },
  {
    id: "idea-life-os",
    title: "Life OS als persönliches Wissens- und Steuerungssystem",
    status: "promising",
    workType: "research_project",
    fieldId: "field-pkm",
    fieldTitle: "Personal Knowledge Management",
    thesisPotential: "high",
    summary:
      "Bündelt persönliche Steuerung, Wissen und Review zu einem System, das Entscheidungen vorbereitet statt Daten nur zu sammeln.",
    researchQuestion:
      "Wie lassen sich lose Notizen ohne Wissensfriedhof strukturieren?",
    nextAction: "Systemgrenzen zwischen Dashboard, Resources und Education notieren",
    sourceCount: 4,
    noteCount: 5,
    openQuestionCount: 1,
    updatedAt: "2026-06-19T18:15:00.000Z",
  },
  {
    id: "idea-ai-learning",
    title: "Akzeptanz von KI-gestützten Lernsystemen",
    status: "idea",
    workType: "seminararbeit",
    fieldId: "field-learning-analytics",
    fieldTitle: "Learning Analytics",
    thesisPotential: "medium",
    summary:
      "Fragt, wann Lernende KI-Hinweise als hilfreiche Reflexion und wann als Bewertung oder Kontrolle wahrnehmen.",
    researchQuestion:
      "Welche Rolle spielt Transparenz bei KI-gestützten Lernempfehlungen?",
    nextAction: "Begriffe Akzeptanz, Transparenz und Selbstregulation abgrenzen",
    sourceCount: 2,
    noteCount: 1,
    openQuestionCount: 1,
    updatedAt: "2026-06-18T10:00:00.000Z",
  },
  {
    id: "idea-privacy-rls",
    title: "RLS und Privacy in persönlichen Productivity Apps",
    status: "active",
    workType: "hausarbeit",
    fieldId: "field-privacy",
    fieldTitle: "Privacy by Design",
    thesisPotential: "medium",
    summary:
      "Vergleicht technische Zugriffskontrolle mit verständlicher Privacy-Kommunikation in persönlichen Datenprodukten.",
    researchQuestion:
      "Wie sichtbar muss Privacy-Logik fuer Nutzer sein, damit sie vertrauensbildend wirkt?",
    nextAction: "Privacy-by-Design-Kriterien in 5 prüfbare Aussagen übersetzen",
    sourceCount: 3,
    noteCount: 2,
    openQuestionCount: 0,
    updatedAt: "2026-06-17T16:20:00.000Z",
  },
  {
    id: "idea-calm-gamification",
    title: "Gamification ohne Produktivitätsdruck",
    status: "paused",
    workType: "presentation",
    fieldId: "field-calm-technology",
    fieldTitle: "Calm Technology",
    thesisPotential: "unknown",
    summary:
      "Sammelt Kriterien für Motivationselemente, die Verhalten unterstützen, ohne Druck, Vergleich oder künstliche Dringlichkeit zu erzeugen.",
    researchQuestion:
      "Wann wird Gamification produktiv und wann erzeugt sie Druck?",
    nextAction: "Beispiele fuer ruhige Motivation von Leistungsdruck trennen",
    sourceCount: 2,
    noteCount: 2,
    openQuestionCount: 1,
    updatedAt: "2026-06-15T09:10:00.000Z",
  },
];

export const mockLiteratureItems: LiteratureItem[] = [
  {
    id: "lit-human-ai-collab",
    title: "Human-AI Collaboration in Knowledge Work",
    authors: "Example Research Group",
    year: 2024,
    type: "paper",
    status: "reading",
    fieldId: "field-human-ai",
    fieldTitle: "Human-AI Interaction",
    ideaId: "idea-ai-agents",
    ideaTitle: "KI-Agenten als persönliche Produktivitätsassistenten",
    relevance: "high",
    citationKey: "example-human-ai-2024",
    note: "Mock source used for UI structure, not a verified citation.",
    nextAction: "Argumente zu Review und Kontrollgefühl extrahieren",
    updatedAt: "2026-06-20T11:45:00.000Z",
  },
  {
    id: "lit-pkm-revisited",
    title: "Personal Knowledge Management Revisited",
    authors: "Sample Authors",
    year: 2023,
    type: "article",
    status: "to_read",
    fieldId: "field-pkm",
    fieldTitle: "Personal Knowledge Management",
    ideaId: "idea-life-os",
    ideaTitle: "Life OS als persönliches Wissens- und Steuerungssystem",
    relevance: "high",
    citationKey: "sample-pkm-2023",
    note: "Mock source for overview interaction only.",
    nextAction: "Lesen und PKM-Begriffe in Notizmodell übersetzen",
    updatedAt: "2026-06-19T08:20:00.000Z",
  },
  {
    id: "lit-calm-tech",
    title: "Designing Calm Technology",
    authors: "Illustrative Design Notes",
    year: 2022,
    type: "book",
    status: "extracting",
    fieldId: "field-calm-technology",
    fieldTitle: "Calm Technology",
    ideaId: "idea-ai-agents",
    ideaTitle: "KI-Agenten als persönliche Produktivitätsassistenten",
    relevance: "medium",
    citationKey: "illustrative-calm-2022",
    note: "Mock source, not a bibliographic claim.",
    nextAction: "2 Zitate zu ruhiger Steuerung als Evidence markieren",
    updatedAt: "2026-06-18T19:00:00.000Z",
  },
  {
    id: "lit-srl-digital-tools",
    title: "Self-Regulated Learning and Digital Tools",
    authors: "Learning Systems Lab",
    year: 2021,
    type: "paper",
    status: "to_read",
    fieldId: "field-learning-analytics",
    fieldTitle: "Learning Analytics",
    ideaId: "idea-ai-learning",
    ideaTitle: "Akzeptanz von KI-gestützten Lernsystemen",
    relevance: "medium",
    citationKey: "learning-srl-2021",
    note: "Mock literature item for learning analytics workflow.",
    nextAction: "Selbstregulation und Feedback-Timing prüfen",
    updatedAt: "2026-06-17T14:40:00.000Z",
  },
  {
    id: "lit-privacy-design",
    title: "Privacy by Design in Personal Data Systems",
    authors: "Privacy Systems Forum",
    year: 2020,
    type: "report",
    status: "reviewed",
    fieldId: "field-privacy",
    fieldTitle: "Privacy by Design",
    ideaId: "idea-privacy-rls",
    ideaTitle: "RLS und Privacy in persönlichen Productivity Apps",
    relevance: "high",
    citationKey: "privacy-systems-2020",
    note: "Mock reviewed item for local UI state.",
    nextAction: "Kriterien in Research-Idea-Notiz verlinken",
    updatedAt: "2026-06-16T16:10:00.000Z",
  },
];

export const mockResearchNotes: ResearchNote[] = [
  {
    id: "note-review-duty",
    title: "Review-Pflicht als Vertrauenssignal",
    type: "argument",
    ideaId: "idea-ai-agents",
    ideaTitle: "KI-Agenten als persönliche Produktivitätsassistenten",
    literatureId: "lit-human-ai-collab",
    literatureTitle: "Human-AI Collaboration in Knowledge Work",
    fieldId: "field-human-ai",
    fieldTitle: "Human-AI Interaction",
    snippet:
      "Review darf nicht nur Kontrollverlust verhindern, sondern muss als sichtbarer Arbeitsschritt im System verankert sein.",
    body:
      "Die Review-Pflicht sollte nicht als Misstrauen gegen KI formuliert werden. Sie kann als akademischer Kontrollpunkt dienen, an dem Argument, Quelle und Entscheidung zusammengeführt werden.",
    tags: ["review", "trust", "agents"],
    source: "manual",
    reviewNeeded: true,
    updatedAt: "2026-06-20T15:00:00.000Z",
  },
  {
    id: "note-life-os-boundary",
    title: "Dashboard ist Steuerung, Education ist Kontext",
    type: "decision",
    ideaId: "idea-life-os",
    ideaTitle: "Life OS als persönliches Wissens- und Steuerungssystem",
    fieldId: "field-pkm",
    fieldTitle: "Personal Knowledge Management",
    snippet:
      "Education darf wissenschaftliche Tiefe bündeln, aber nicht die tägliche Steuerung des Dashboards duplizieren.",
    body:
      "Die Bereichsseiten bleiben Kontextflächen. Wissenschaftliche Tiefe wird über Ideen, Felder, Quellen und Notizen sichtbar, nicht über eine zweite Tagessteuerung.",
    tags: ["life-os", "scope"],
    source: "quick_capture",
    reviewNeeded: false,
    updatedAt: "2026-06-19T20:10:00.000Z",
  },
  {
    id: "note-calm-tech",
    title: "Calm Technology als Designfilter",
    type: "summary",
    ideaId: "idea-ai-agents",
    ideaTitle: "KI-Agenten als persönliche Produktivitätsassistenten",
    literatureId: "lit-calm-tech",
    literatureTitle: "Designing Calm Technology",
    fieldId: "field-calm-technology",
    fieldTitle: "Calm Technology",
    snippet:
      "Ruhige Systeme sollten Entscheidungslast reduzieren, ohne relevante Unsicherheit zu verstecken.",
    body:
      "Calm Technology passt als Designfilter, wenn die Masterarbeit Systeme betrachtet, die Review, Unsicherheit und nächste Schritte sichtbar machen, ohne Druck aufzubauen.",
    tags: ["calm", "design"],
    source: "literature",
    reviewNeeded: true,
    updatedAt: "2026-06-18T21:25:00.000Z",
  },
  {
    id: "note-gamification-pressure",
    title: "Motivation ohne Drucksprache",
    type: "question",
    ideaId: "idea-calm-gamification",
    ideaTitle: "Gamification ohne Produktivitätsdruck",
    fieldId: "field-calm-technology",
    fieldTitle: "Calm Technology",
    snippet:
      "Welche Mechaniken zeigen Fortschritt, ohne Schuld, Vergleich oder künstliche Dringlichkeit zu erzeugen?",
    body:
      "Die Frage bleibt offen, weil Motivationselemente je nach Sprache und Kontext hilfreich oder druckvoll wirken können.",
    tags: ["gamification", "pressure"],
    source: "manual",
    reviewNeeded: false,
    updatedAt: "2026-06-16T12:05:00.000Z",
  },
  {
    id: "note-privacy-rules",
    title: "Privacy-Regeln müssen sichtbar bleiben",
    type: "method",
    ideaId: "idea-privacy-rls",
    ideaTitle: "RLS und Privacy in persönlichen Productivity Apps",
    literatureId: "lit-privacy-design",
    literatureTitle: "Privacy by Design in Personal Data Systems",
    fieldId: "field-privacy",
    fieldTitle: "Privacy by Design",
    snippet:
      "RLS ist technische Absicherung; die Forschungsfrage braucht zusätzlich verständliche Nutzerkommunikation.",
    body:
      "Privacy by Design muss als Systemprinzip und als sichtbare Nutzerinformation betrachtet werden. Nur technische RLS-Regeln reichen fuer die Forschungsargumentation nicht aus.",
    tags: ["privacy", "rls"],
    source: "manual",
    reviewNeeded: false,
    updatedAt: "2026-06-15T17:45:00.000Z",
  },
];

export const mockResearchQuestions: ResearchQuestion[] = [
  {
    id: "question-decision-pressure",
    question: "Wie kann ein persönliches System Entscheidungsdruck reduzieren?",
    ideaId: "idea-life-os",
    ideaTitle: "Life OS als persönliches Wissens- und Steuerungssystem",
    fieldId: "field-pkm",
    fieldTitle: "Personal Knowledge Management",
    status: "open",
    importance: "high",
    nextAction: "Begriffe Druck, Auswahl und Review anhand von 2 Quellen trennen",
    updatedAt: "2026-06-20T09:35:00.000Z",
  },
  {
    id: "question-review-duty",
    question: "Welche Rolle spielt Review-Pflicht bei KI-generierten Outputs?",
    ideaId: "idea-ai-agents",
    ideaTitle: "KI-Agenten als persönliche Produktivitätsassistenten",
    fieldId: "field-human-ai",
    fieldTitle: "Human-AI Interaction",
    status: "investigating",
    importance: "high",
    nextAction: "Kernargumente aus Human-AI-Literatur markieren",
    updatedAt: "2026-06-20T08:30:00.000Z",
  },
  {
    id: "question-gamification",
    question: "Wann wird Gamification produktiv und wann erzeugt sie Druck?",
    ideaId: "idea-calm-gamification",
    ideaTitle: "Gamification ohne Produktivitätsdruck",
    fieldId: "field-calm-technology",
    fieldTitle: "Calm Technology",
    status: "open",
    importance: "medium",
    nextAction: "Drei Mechaniken nach Druckrisiko sortieren",
    updatedAt: "2026-06-18T10:50:00.000Z",
  },
  {
    id: "question-notes-structure",
    question: "Wie lassen sich lose Notizen ohne Wissensfriedhof strukturieren?",
    ideaId: "idea-life-os",
    ideaTitle: "Life OS als persönliches Wissens- und Steuerungssystem",
    fieldId: "field-pkm",
    fieldTitle: "Personal Knowledge Management",
    status: "open",
    importance: "high",
    nextAction: "Notiztypen Summary, Argument, Decision und Source Note vergleichen",
    updatedAt: "2026-06-17T15:15:00.000Z",
  },
];

export const mockMasterThesis: MasterThesisState = {
  id: "master-thesis-ai-productivity",
  title: "Masterarbeit: KI-gestützte persönliche Produktivitätssysteme",
  currentPhase: "topic_selection",
  researchQuestion:
    "Wie kann Review-Pflicht Vertrauen und Kontrolle in KI-gestützten persönlichen Produktivitätssystemen stärken?",
  supervisor: "Noch offen",
  progress: 18,
  nextAction: "Forschungsfrage schärfen und 5 Kernquellen prüfen",
  openRisk: "Forschungsfrage ist noch zu breit und muss auf Review-Pflicht eingegrenzt werden.",
  linkedIdeaId: "idea-ai-agents",
  linkedFieldId: "field-human-ai",
  sourceCount: 5,
  noteCount: 4,
  milestoneCount: 5,
};

export const mockMasterThesisMilestones: MasterThesisMilestone[] = [
  {
    id: "thesis-milestone-topic",
    title: "Thema eingrenzen",
    status: "active",
    dueLabel: "Next 2 weeks",
    progress: 45,
    nextAction: "Arbeitsbegriff Review-Pflicht definieren",
  },
  {
    id: "thesis-milestone-core-literature",
    title: "Kernliteratur prüfen",
    status: "planned",
    dueLabel: "After topic decision",
    progress: 15,
    nextAction: "5 Kernquellen lesen und Relevanz notieren",
  },
  {
    id: "thesis-milestone-proposal",
    title: "Exposé vorbereiten",
    status: "planned",
    dueLabel: "Draft window",
    progress: 0,
    nextAction: "Gliederungsentwurf aus Research Question ableiten",
  },
  {
    id: "thesis-milestone-method",
    title: "Methodik klären",
    status: "blocked",
    dueLabel: "Before proposal",
    progress: 5,
    nextAction: "Entscheiden, ob Designanalyse oder qualitative Auswertung sinnvoller ist",
  },
  {
    id: "thesis-milestone-writing",
    title: "Schreibphase starten",
    status: "paused",
    dueLabel: "Later",
    progress: 0,
    nextAction: "Erst nach Exposé-Freigabe aktivieren",
  },
];

export const mockLearningTracks: LearningTrack[] = [
  {
    id: "track-java-hyperskill",
    title: "Java / Hyperskill",
    type: "platform",
    status: "active",
    focusArea: "Java Foundations",
    progress: 41,
    currentModule: "Collections",
    nextAction: "Collections Practice abschließen und Ergebnisnotiz schreiben",
    linkedSkill: "Java",
    linkedProject: "Life OS Backend Patterns",
    updatedAt: "2026-06-20T18:30:00.000Z",
  },
  {
    id: "track-leetcode-basics",
    title: "LeetCode Basics",
    type: "practice",
    status: "active",
    focusArea: "Arrays und Hash Maps",
    progress: 28,
    currentModule: "Two Pointer Patterns",
    nextAction: "Two Sum Varianten vergleichen und Pattern-Notiz schreiben",
    linkedSkill: "Algorithmic Thinking",
    updatedAt: "2026-06-19T17:20:00.000Z",
  },
  {
    id: "track-research-methods",
    title: "Research Methods",
    type: "reading",
    status: "active",
    focusArea: "Methodische Einordnung",
    progress: 35,
    currentModule: "Qualitative Designanalyse",
    nextAction: "Method Section markieren und 3 Kriterien extrahieren",
    linkedSkill: "Scientific Work",
    linkedProject: "Master Thesis",
    updatedAt: "2026-06-20T12:05:00.000Z",
  },
  {
    id: "track-academic-writing",
    title: "Academic Writing",
    type: "course",
    status: "planned",
    focusArea: "Argumentationsstruktur",
    progress: 12,
    currentModule: "Claim Evidence Reasoning",
    nextAction: "Argumentationsstruktur für Research Question skizzieren",
    linkedSkill: "Academic Writing",
    linkedProject: "Master Thesis",
    updatedAt: "2026-06-18T10:15:00.000Z",
  },
  {
    id: "track-typescript-deepening",
    title: "TypeScript Deepening",
    type: "project",
    status: "active",
    focusArea: "Typed UI State",
    progress: 54,
    currentModule: "Discriminated Unions",
    nextAction: "Form-State-Union für lokale Dialoge prüfen",
    linkedSkill: "TypeScript",
    linkedProject: "Life OS",
    updatedAt: "2026-06-20T09:45:00.000Z",
  },
  {
    id: "track-supabase-rls",
    title: "Supabase RLS Concepts",
    type: "reading",
    status: "paused",
    focusArea: "Policy Design",
    progress: 18,
    currentModule: "User-owned rows",
    nextAction: "RLS Policy Beispiel als User-Story erklären",
    linkedSkill: "Supabase",
    updatedAt: "2026-06-17T16:35:00.000Z",
  },
];

export const mockLearningSessions: LearningSession[] = [
  {
    id: "session-collections",
    title: "Collections-Modul abgeschlossen",
    trackId: "track-java-hyperskill",
    trackTitle: "Java / Hyperskill",
    date: "2026-06-20",
    durationMinutes: 45,
    outcome: "Map, Set und List-Verhalten anhand kleiner Aufgaben wiederholt.",
    evidence: "Collections Practice bis Review-Schritt vorbereitet.",
    energyLabel: "medium",
    status: "done",
    notes: "Kurze Ergebnisnotiz hilft, die Unterschiede zwischen Set und List sauber zu behalten.",
  },
  {
    id: "session-leetcode-arrays",
    title: "LeetCode Arrays wiederholt",
    trackId: "track-leetcode-basics",
    trackTitle: "LeetCode Basics",
    date: "2026-06-19",
    durationMinutes: 35,
    outcome: "Two Sum und Prefix-Sum Varianten erneut strukturiert.",
    evidence: "2 Lösungswege mit kurzer Pattern-Notiz verglichen.",
    energyLabel: "medium",
    status: "done",
  },
  {
    id: "session-paper-method",
    title: "Paper Method Section gelesen",
    trackId: "track-research-methods",
    trackTitle: "Research Methods",
    date: "2026-06-18",
    durationMinutes: 50,
    outcome: "Methodische Begriffe für qualitative Auswertung markiert.",
    evidence: "3 Kriterien für spätere Methodik-Entscheidung notiert.",
    energyLabel: "high",
    status: "review_needed",
    notes: "Muss noch gegen Master-Thesis-Frage geprüft werden.",
  },
  {
    id: "session-research-question",
    title: "Research Question geschärft",
    trackId: "track-academic-writing",
    trackTitle: "Academic Writing",
    date: "2026-06-17",
    durationMinutes: 30,
    outcome: "Review-Pflicht als engeren Fokus formuliert.",
    evidence: "Alte breite Frage in zwei präzisere Varianten zerlegt.",
    energyLabel: "low",
    status: "done",
  },
  {
    id: "session-zod-pattern",
    title: "Zod Validation Pattern notiert",
    trackId: "track-typescript-deepening",
    trackTitle: "TypeScript Deepening",
    date: "2026-06-16",
    durationMinutes: 40,
    outcome: "Validierungslogik als wiederverwendbares Pattern dokumentiert.",
    evidence: "Notiz mit Pflichtfeldern, Fehlermeldung und späterer Server-Action-Grenze.",
    energyLabel: "medium",
    status: "done",
  },
];

export const mockPracticeQueue: PracticeQueueItem[] = [
  {
    id: "practice-hyperskill-collections",
    title: "Hyperskill: Collections Practice",
    source: "hyperskill",
    difficulty: "medium",
    linkedTrackId: "track-java-hyperskill",
    linkedSkill: "Java",
    status: "queued",
    nextAction: "Practice abschließen und Fehler in Ergebnisnotiz aufnehmen",
  },
  {
    id: "practice-two-sum",
    title: "LeetCode: Two Sum Varianten",
    source: "leetcode",
    difficulty: "easy",
    linkedTrackId: "track-leetcode-basics",
    linkedSkill: "Algorithmic Thinking",
    status: "in_progress",
    nextAction: "Hash-Map-Variante ohne Hilfe erneut schreiben",
  },
  {
    id: "practice-writing-structure",
    title: "Academic Writing: Argumentationsstruktur",
    source: "course",
    difficulty: "medium",
    linkedTrackId: "track-academic-writing",
    linkedSkill: "Academic Writing",
    status: "queued",
    nextAction: "Claim, Evidence und Reasoning für eine Kernthese skizzieren",
  },
  {
    id: "practice-rls-policy",
    title: "RLS Policy Beispiel erklären",
    source: "manual",
    difficulty: "hard",
    linkedTrackId: "track-supabase-rls",
    linkedSkill: "Supabase",
    status: "blocked",
    nextAction: "Vorher Auth-Kontext und user_id-Regel wiederholen",
  },
  {
    id: "practice-paper-summary",
    title: "Paper Summary schreiben",
    source: "book",
    difficulty: "medium",
    linkedTrackId: "track-research-methods",
    linkedSkill: "Scientific Work",
    status: "queued",
    nextAction: "Method Section in 5 Bullet Points zusammenfassen",
  },
];

export const mockLearningInsights: LearningInsight[] = [
  {
    id: "insight-outcome-note",
    title: "Wiederholung wirkt besser nach kurzer Ergebnisnotiz",
    source: "session",
    snippet:
      "Nach Übungen bleibt mehr hängen, wenn direkt Outcome, Fehler und nächster Schritt notiert werden.",
    linkedTrackId: "track-java-hyperskill",
    reviewNeeded: false,
    createdAt: "2026-06-20T19:10:00.000Z",
  },
  {
    id: "insight-rls-user-story",
    title: "RLS wird klarer, wenn Policies als User-Story formuliert werden",
    source: "reading",
    snippet:
      "Eine Policy lässt sich besser prüfen, wenn zuerst beschrieben wird, welcher Nutzer welche Zeile sehen darf.",
    linkedTrackId: "track-supabase-rls",
    reviewNeeded: true,
    createdAt: "2026-06-18T16:40:00.000Z",
  },
  {
    id: "insight-leetcode-patterns",
    title: "LeetCode braucht feste Problemtypen statt zufälliges Üben",
    source: "practice",
    snippet:
      "Arrays und Hash Maps sollten als wiederkehrende Patterns geübt werden, nicht als zufällige Einzelaufgaben.",
    linkedTrackId: "track-leetcode-basics",
    reviewNeeded: false,
    createdAt: "2026-06-19T18:25:00.000Z",
  },
  {
    id: "insight-method-evidence",
    title: "Methodik braucht Evidence, nicht nur Bauchgefühl",
    source: "reflection",
    snippet:
      "Die spätere Methodenwahl sollte an Forschungsfrage, Datenzugang und Auswertbarkeit hängen.",
    linkedTrackId: "track-research-methods",
    reviewNeeded: true,
    createdAt: "2026-06-18T20:00:00.000Z",
  },
];

export const mockWeeklyLearningDays: WeeklyLearningDay[] = [
  { id: "learning-week-mon", dayLabel: "Mon", status: "done", minutes: 40 },
  { id: "learning-week-tue", dayLabel: "Tue", status: "done", minutes: 30 },
  { id: "learning-week-wed", dayLabel: "Wed", status: "rest", minutes: 0 },
  { id: "learning-week-thu", dayLabel: "Thu", status: "done", minutes: 50 },
  { id: "learning-week-fri", dayLabel: "Fri", status: "planned", minutes: 35 },
  { id: "learning-week-sat", dayLabel: "Sat", status: "planned", minutes: 45 },
  { id: "learning-week-sun", dayLabel: "Sun", status: "rest", minutes: 0 },
];

export const mockLearningMethodNotes = [
  "Learning sessions should end with an outcome",
  "Practice items need a next action",
  "Evidence increases confidence",
  "Rest days are allowed",
  "No XP or pressure scoring in MVP",
];
