import type { PortfolioEntity } from "./types";

export const portfolioEntities: PortfolioEntity[] = [
  {
    id: "project-life-os-app",
    type: "project",
    title: "Life OS App",
    description: "Core app implementation and static V5 route coverage.",
    area: "coding",
    status: "needs_decision",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Implement Portfolio page from Figma",
    dueLabel: "This week",
    dueRank: 1,
    progress: 56,
    countLabel: "9 direct / 18 linked",
    lastTouched: "today",
    recentRank: 1,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Goal", value: "Life OS MVP nutzbar machen" },
      { label: "Area", value: "Coding & Agents" },
      { label: "Milestone", value: "Static app skeleton" },
    ],
    decisions: [
      {
        title: "Portfolio V1 implementation ready?",
        detail: "Static workbench can replace the route skeleton.",
        state: "decide",
      },
      {
        title: "Calendar route remains separate?",
        detail: "Calendar keeps time projection, Portfolio keeps entities.",
        state: "ready",
      },
    ],
    sourceLinks: [
      { label: "Project / Life OS App", href: "/projects" },
      { label: "Tasks / Portfolio", href: "/tasks" },
      { label: "Goal / Life OS MVP", href: "/goals" },
    ],
    noteSnippet: "Keep Portfolio as list plus context, not a second dashboard.",
  },
  {
    id: "task-calendar-page",
    type: "task",
    title: "Calendar page implementieren",
    description: "Translate accepted Calendar design into the static route.",
    area: "coding",
    status: "in_progress",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Resolve remaining layout and validation checks",
    dueLabel: "This week",
    dueRank: 1,
    progress: 64,
    countLabel: "45 min",
    lastTouched: "today",
    recentRank: 2,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Project", value: "Life OS App" },
      { label: "Goal", value: "Life OS MVP nutzbar machen" },
      { label: "Source", value: "Figma Calendar V1" },
    ],
    decisions: [
      {
        title: "Keep right panel review-aware?",
        detail: "Review remains Calendar/Today-near and not a sidebar item.",
        state: "watch",
      },
    ],
    sourceLinks: [
      { label: "Task / Calendar", href: "/tasks" },
      { label: "Calendar", href: "/calendar" },
      { label: "Project / Life OS App", href: "/projects" },
    ],
    noteSnippet:
      "Use Calendar for time projection, not duplicated project data.",
  },
  {
    id: "task-portfolio-figma",
    type: "task",
    title: "Portfolio page in Figma finalisieren",
    description: "Confirm V1 page contract and implementation handoff.",
    area: "coding",
    status: "review_open",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Compare app implementation with accepted V1 node",
    dueLabel: "This week",
    dueRank: 1,
    progress: 72,
    countLabel: "30 min",
    lastTouched: "today",
    recentRank: 3,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Project", value: "Life OS App" },
      { label: "Design", value: "Portfolio Page V1" },
      { label: "Area", value: "Coding & Agents" },
    ],
    decisions: [
      {
        title: "State frames stay reference only?",
        detail: "Views should filter the list instead of rendering previews.",
        state: "ready",
      },
    ],
    sourceLinks: [
      { label: "Task / Portfolio", href: "/tasks" },
      { label: "Project / Life OS App", href: "/projects" },
      { label: "Skills / Design", href: "/skills" },
    ],
    noteSnippet: "Use the workbench pattern, not a 2x2 state gallery.",
  },
  {
    id: "task-inbox-empty",
    type: "task",
    title: "Inbox empty state pruefen",
    description: "Check whether empty Inbox copy still guides capture triage.",
    area: "system",
    status: "planned",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Review empty-state copy against current Inbox route",
    dueLabel: "Next focus",
    dueRank: 3,
    progress: 15,
    countLabel: "20 min",
    lastTouched: "2d ago",
    recentRank: 6,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Route", value: "Inbox" },
      { label: "Flow", value: "Quick Capture" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Inbox", href: "/inbox" },
      { label: "Tasks", href: "/tasks" },
    ],
    noteSnippet: "Empty state should reduce pressure and point to capture.",
  },
  {
    id: "task-literature-source",
    type: "task",
    title: "Literature source deadline klaeren",
    description:
      "Confirm whether the next literature source blocks thesis work.",
    area: "education",
    status: "blocked",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Decide source priority before the next writing block",
    dueLabel: "This week",
    dueRank: 1,
    progress: 20,
    countLabel: "25 min",
    lastTouched: "yesterday",
    recentRank: 4,
    reviewNeeded: true,
    blocked: true,
    relations: [
      { label: "Project", value: "Masterarbeit" },
      { label: "Area", value: "Education" },
      { label: "Goal", value: "Masterarbeit abgeben" },
    ],
    decisions: [
      {
        title: "Use source now or park it?",
        detail: "Writing momentum should not wait on weak evidence.",
        state: "blocked",
      },
    ],
    sourceLinks: [
      { label: "Education / Literature", href: "/education/literature" },
      { label: "Project / Masterarbeit", href: "/projects" },
      { label: "Goal / Masterarbeit", href: "/goals" },
    ],
    noteSnippet: "Clarify source value before expanding the reading list.",
  },
  {
    id: "task-hyperskill",
    type: "task",
    title: "Hyperskill lesson block abschliessen",
    description:
      "Finish one contained Java learning block without scope creep.",
    area: "education",
    status: "in_progress",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Complete lesson and record friction point",
    dueLabel: "Friday",
    dueRank: 2,
    progress: 41,
    countLabel: "50 min",
    lastTouched: "2d ago",
    recentRank: 7,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Skill", value: "Java / Hyperskill" },
      { label: "Area", value: "Education" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Skill / Java", href: "/skills" },
      { label: "Education / Learning Log", href: "/education/learning-log" },
    ],
    noteSnippet: "Keep practice small enough to preserve the daily flow.",
  },
  {
    id: "task-weekly-review",
    type: "task",
    title: "Weekly review vorbereiten",
    description: "Collect open loops, wins, blockers and carry-forward items.",
    area: "review",
    status: "review_open",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Draft open loops before Calendar review panel work",
    dueLabel: "This week",
    dueRank: 1,
    progress: 30,
    countLabel: "35 min",
    lastTouched: "yesterday",
    recentRank: 5,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Route", value: "Calendar" },
      { label: "Flow", value: "Weekly Review" },
    ],
    decisions: [
      {
        title: "Which loops move into next week?",
        detail: "Only carry forward items with a next action.",
        state: "decide",
      },
    ],
    sourceLinks: [
      { label: "Calendar", href: "/calendar" },
      { label: "Tasks", href: "/tasks" },
    ],
    noteSnippet: "Review stays near Calendar and Today, not primary sidebar.",
  },
  {
    id: "task-fi-notes",
    type: "task",
    title: "FI notes strukturieren",
    description: "Convert scattered work notes into a small Work Wiki outline.",
    area: "work",
    status: "planned",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Group notes by system, decision and follow-up",
    dueLabel: "Next review",
    dueRank: 4,
    progress: 18,
    countLabel: "40 min",
    lastTouched: "3d ago",
    recentRank: 9,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Project", value: "Finanzinformatik Work Notes" },
      { label: "Area", value: "Work" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Work / Wiki", href: "/work/wiki" },
      { label: "Work Log", href: "/work/log" },
      { label: "Tasks", href: "/tasks" },
    ],
    noteSnippet: "Separate follow-ups from durable wiki notes.",
  },
  {
    id: "task-workout-plan",
    type: "task",
    title: "Workout planen",
    description: "Plan the next strength or running slot around weekly load.",
    area: "health",
    status: "planned",
    priority: "P3",
    focusLevel: "low",
    nextAction: "Pick one realistic session and recovery note",
    dueLabel: "This week",
    dueRank: 1,
    progress: 10,
    countLabel: "15 min",
    lastTouched: "4d ago",
    recentRank: 12,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Area", value: "Health" },
      { label: "Goal", value: "Fitness-Routine stabilisieren" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Health / Running", href: "/health/running" },
      { label: "Health / Strength", href: "/health/strength" },
    ],
    noteSnippet: "Plan recovery first if the week is overloaded.",
  },
  {
    id: "task-protein-bowl",
    type: "task",
    title: "Protein Bowl vorbereiten",
    description: "Prepare a simple meal option that supports the week.",
    area: "nutrition",
    status: "planned",
    priority: "P3",
    focusLevel: "low",
    nextAction: "Check ingredients and choose one recipe",
    dueLabel: "This week",
    dueRank: 1,
    progress: 25,
    countLabel: "20 min",
    lastTouched: "5d ago",
    recentRank: 13,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Area", value: "Nutrition" },
      { label: "Source", value: "Meal Planner" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Nutrition / Meal Planner", href: "/nutrition/meal-planner" },
      { label: "Recipes", href: "/nutrition/recipes" },
    ],
    noteSnippet: "Keep meal prep as support, not the main control surface.",
  },
  {
    id: "project-masterarbeit",
    type: "project",
    title: "Masterarbeit",
    description: "Thesis writing, sources and deadline control.",
    area: "education",
    status: "active",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Protect the next literature and writing block",
    dueLabel: "June focus",
    dueRank: 2,
    progress: 42,
    countLabel: "27 / 60 open",
    lastTouched: "yesterday",
    recentRank: 8,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Goal", value: "Masterarbeit abgeben" },
      { label: "Area", value: "Education" },
      { label: "Constraint", value: "Literature source clarity" },
    ],
    decisions: [
      {
        title: "Source deadline before writing?",
        detail: "Avoid delaying output if the source is optional.",
        state: "decide",
      },
    ],
    sourceLinks: [
      {
        label: "Education / Scientific Work",
        href: "/education/scientific-work",
      },
      { label: "Education / Literature", href: "/education/literature" },
      { label: "Goals", href: "/goals" },
    ],
    noteSnippet: "Keep visible, but do not let source triage own the page.",
  },
  {
    id: "project-java-hyperskill",
    type: "project",
    title: "Java / Hyperskill",
    description: "Structured Java learning through contained practice blocks.",
    area: "education",
    status: "active",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Finish the active lesson block",
    dueLabel: "Friday",
    dueRank: 2,
    progress: 41,
    countLabel: "9 / 22 open",
    lastTouched: "2d ago",
    recentRank: 10,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Skill", value: "Java / Hyperskill" },
      { label: "Area", value: "Education" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Skills", href: "/skills" },
      { label: "Education / Learning Log", href: "/education/learning-log" },
    ],
    noteSnippet: "Evidence should come from practice, not course collecting.",
  },
  {
    id: "project-fi-work-notes",
    type: "project",
    title: "Finanzinformatik notes aufbereiten",
    description: "Work notes, decisions and reusable context for FI tasks.",
    area: "work",
    status: "review_open",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Structure notes into work wiki and follow-up buckets",
    dueLabel: "Next review",
    dueRank: 4,
    progress: 33,
    countLabel: "3 / 9 open",
    lastTouched: "3d ago",
    recentRank: 11,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Area", value: "Work" },
      { label: "Source", value: "Work Log" },
    ],
    decisions: [
      {
        title: "What becomes durable wiki context?",
        detail: "Only stable system notes should move into Wiki.",
        state: "watch",
      },
    ],
    sourceLinks: [
      { label: "Work / Wiki", href: "/work/wiki" },
      { label: "Work Log", href: "/work/log" },
      { label: "Tasks", href: "/tasks" },
    ],
    noteSnippet: "Keep confidential work context quiet and scoped.",
  },
  {
    id: "goal-life-os-mvp",
    type: "goal",
    title: "Life OS MVP nutzbar machen",
    description: "Reach a usable static app before adding persistence.",
    area: "coding",
    status: "active",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Finish Portfolio, Calendar and resource skeleton alignment",
    dueLabel: "June focus",
    dueRank: 2,
    progress: 58,
    countLabel: "4 projects linked",
    lastTouched: "today",
    recentRank: 14,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Project", value: "Life OS App" },
      { label: "Area", value: "Coding & Agents" },
      { label: "Phase", value: "Static App" },
    ],
    decisions: [
      {
        title: "Start data binding now?",
        detail: "Phase 2 should stay static until manual flow is stable.",
        state: "decide",
      },
    ],
    sourceLinks: [
      { label: "Project / Life OS App", href: "/projects" },
      { label: "Portfolio", href: "/portfolio" },
      { label: "Roadmap", href: "/resources" },
    ],
    noteSnippet: "Manual source of truth first, data model later.",
  },
  {
    id: "goal-masterarbeit",
    type: "goal",
    title: "Masterarbeit abgeben",
    description: "Keep thesis output moving while source work stays bounded.",
    area: "education",
    status: "active",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Resolve literature source deadline and protect writing time",
    dueLabel: "June focus",
    dueRank: 2,
    progress: 37,
    countLabel: "2 projects linked",
    lastTouched: "yesterday",
    recentRank: 15,
    reviewNeeded: true,
    blocked: true,
    relations: [
      { label: "Project", value: "Masterarbeit" },
      { label: "Area", value: "Education" },
      { label: "Constraint", value: "Source decision" },
    ],
    decisions: [
      {
        title: "Source first or writing first?",
        detail: "Choose the path that protects output this week.",
        state: "blocked",
      },
    ],
    sourceLinks: [
      {
        label: "Education / Scientific Work",
        href: "/education/scientific-work",
      },
      { label: "Education / Literature", href: "/education/literature" },
      { label: "Projects", href: "/projects" },
    ],
    noteSnippet: "Decision pressure belongs here, not in the Dashboard.",
  },
  {
    id: "goal-fitness-routine",
    type: "goal",
    title: "Fitness-Routine stabilisieren",
    description: "Make health actions consistent without overloading the day.",
    area: "health",
    status: "active",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Plan one workout and one recovery cue",
    dueLabel: "June support",
    dueRank: 2,
    progress: 28,
    countLabel: "2 habits linked",
    lastTouched: "2d ago",
    recentRank: 18,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Area", value: "Health" },
      { label: "Task", value: "Workout planen" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Health", href: "/health" },
      { label: "Habits", href: "/health/habits" },
    ],
    noteSnippet: "Support the day, do not compete with the P0 flow.",
  },
  {
    id: "goal-career-plan",
    type: "goal",
    title: "Finanz-/Karriere-Plan strukturieren",
    description: "Keep work learning, notes and career decisions connected.",
    area: "work",
    status: "planned",
    priority: "P3",
    focusLevel: "low",
    nextAction: "List the next useful career decision",
    dueLabel: "Later",
    dueRank: 5,
    progress: 14,
    countLabel: "1 project linked",
    lastTouched: "6d ago",
    recentRank: 20,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Area", value: "Work" },
      { label: "Project", value: "Finanzinformatik Work Notes" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Work", href: "/work" },
      { label: "Projects", href: "/projects" },
    ],
    noteSnippet: "Keep this low-pressure until weekly review promotes it.",
  },
  {
    id: "skill-figma-design",
    type: "skill",
    title: "Figma Layout Practice",
    description: "Practice calm, buildable Life OS page layouts in Figma.",
    area: "coding",
    status: "practicing",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Run a 30 min layout review against V5 rules",
    dueLabel: "This week",
    dueRank: 1,
    progress: 52,
    countLabel: "4 sessions planned",
    lastTouched: "today",
    recentRank: 16,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Project", value: "Life OS App" },
      { label: "Evidence", value: "Portfolio Page V1" },
    ],
    decisions: [
      {
        title: "Promote Figma review checklist?",
        detail: "Only after the implementation loop proves useful.",
        state: "watch",
      },
    ],
    sourceLinks: [
      { label: "Skills", href: "/skills" },
      { label: "Portfolio", href: "/portfolio" },
    ],
    noteSnippet:
      "Design work should constrain implementation, not decorate it.",
    skillContext: {
      practiceStatus: "practicing",
      confidence: "medium",
      nextSession: "30 min Portfolio layout review",
      evidence: "Linked to Life OS App and Portfolio Page V1",
    },
  },
  {
    id: "skill-java-hyperskill",
    type: "skill",
    title: "Java / Hyperskill",
    description: "Structured Java practice with clear lesson outcomes.",
    area: "education",
    status: "practicing",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Finish current lesson and log one takeaway",
    dueLabel: "Friday",
    dueRank: 2,
    progress: 41,
    countLabel: "1 active block",
    lastTouched: "2d ago",
    recentRank: 17,
    reviewNeeded: false,
    blocked: false,
    relations: [
      { label: "Project", value: "Java / Hyperskill" },
      { label: "Area", value: "Education" },
    ],
    decisions: [],
    sourceLinks: [
      { label: "Education / Learning Log", href: "/education/learning-log" },
      { label: "Projects", href: "/projects" },
    ],
    noteSnippet:
      "Small lessons keep the skill active without dominating Today.",
    skillContext: {
      practiceStatus: "practicing",
      confidence: "medium",
      nextSession: "Finish one contained lesson block",
      evidence: "Learning log plus Java / Hyperskill project",
    },
  },
  {
    id: "skill-research-writing",
    type: "skill",
    title: "Research Writing",
    description: "Thesis writing, evidence selection and argument structure.",
    area: "education",
    status: "blocked",
    priority: "P1",
    focusLevel: "high",
    nextAction: "Resolve literature source and write the next paragraph",
    dueLabel: "This week",
    dueRank: 1,
    progress: 35,
    countLabel: "source decision open",
    lastTouched: "yesterday",
    recentRank: 19,
    reviewNeeded: true,
    blocked: true,
    relations: [
      { label: "Goal", value: "Masterarbeit abgeben" },
      { label: "Project", value: "Masterarbeit" },
    ],
    decisions: [
      {
        title: "Which evidence is enough?",
        detail: "Pick minimum viable evidence for the next writing block.",
        state: "blocked",
      },
    ],
    sourceLinks: [
      { label: "Education / Literature", href: "/education/literature" },
      {
        label: "Education / Scientific Work",
        href: "/education/scientific-work",
      },
    ],
    noteSnippet: "Writing skill is blocked by decision quality, not effort.",
    skillContext: {
      practiceStatus: "blocked practice",
      confidence: "low",
      nextSession: "Resolve source decision before writing drill",
      evidence: "Linked to Masterarbeit goal and project",
    },
  },
  {
    id: "skill-ai-agent-workflow",
    type: "skill",
    title: "AI Agent Workflow",
    description: "Use agent prompts, skills and review loops safely.",
    area: "coding",
    status: "practicing",
    priority: "P2",
    focusLevel: "medium",
    nextAction: "Keep prompts scoped to small reviewable changes",
    dueLabel: "This week",
    dueRank: 1,
    progress: 47,
    countLabel: "2 prompts active",
    lastTouched: "today",
    recentRank: 21,
    reviewNeeded: true,
    blocked: false,
    relations: [
      { label: "Project", value: "Life OS App" },
      { label: "Source", value: "AI Workflow" },
    ],
    decisions: [
      {
        title: "Add more agent tooling now?",
        detail: "External tools wait until scope, rights and risk are clear.",
        state: "ready",
      },
    ],
    sourceLinks: [
      { label: "Coding / Agents", href: "/coding/agents" },
      { label: "Resources", href: "/resources" },
    ],
    noteSnippet: "Agent capability stays bounded by root truths and reviews.",
    skillContext: {
      practiceStatus: "practicing",
      confidence: "medium",
      nextSession: "Review one scoped Codex prompt",
      evidence: "AI_WORKFLOW rules and Life OS App implementation loops",
    },
  },
];
