import type { DashboardMockData } from "./types";

export const dashboardMockData = {
  commandCenter: {
    priority: "P1",
    greeting: "Good evening, Anton",
    dateLabel: "Tuesday, 09 June",
    dayTypeLabel: "Work / Study Day",
    metrics: [
      {
        label: "Tasks",
        value: "12 / 18",
        detail: "67% complete",
        progress: 67,
        accent: "var(--accent-blue)",
        area: "review",
      },
      {
        label: "Focus Time",
        value: "1h 40m",
        detail: "of 3h target",
        progress: 56,
        accent: "var(--accent-blue)",
        area: "education",
      },
      {
        label: "Inbox",
        value: "5 open",
        detail: "3 need review",
        progress: 38,
        accent: "var(--accent-green)",
        area: "review",
      },
      {
        label: "Nutrition",
        value: "1,720",
        detail: "of 2,200 kcal",
        progress: 78,
        accent: "var(--accent-yellow)",
        area: "nutrition",
      },
      {
        label: "Steps",
        value: "4,200",
        detail: "target 10,000",
        progress: 42,
        accent: "var(--accent-blue)",
        area: "health",
      },
      {
        label: "Sleep",
        value: "6h 12m",
        detail: "target 8h",
        progress: 77,
        accent: "var(--accent-blue)",
        area: "health",
      },
    ],
    timeProgress: [
      { label: "Year 2026", value: "44%", progress: 44 },
      { label: "Month June", value: "43%", progress: 43 },
      { label: "Week 24", value: "71%", progress: 71 },
    ],
    weather: {
      temperatureLabel: "18°C cloudy",
      periodLabel: "Evening",
      conditionLabel: "cloudy",
    },
    moodCheck: {
      title: "Mood",
      eyebrow: "Wellbeing",
      prompt: "How do you feel right now?",
      moodLabel: "Content",
      detail: "stabil · fokusfähig · Stress im Blick",
      scoreLabel: "7.6 / 10",
      progress: 76,
      accent: "var(--accent-cyan)",
      options: ["Happy", "Anxious", "Angry", "Tired", "Sad", "Stressed"],
      activeOption: "Happy",
    },
  },
  quickCapture: {
    priority: "P1",
    title: "Quick Thought",
    destinationLabel: "AI Inbox",
    placeholder: "Write a thought, task or instruction...",
    helperText: "Agent erkennt Task · Note · Question · Loop",
    captureLabel: "Capture",
    kinds: ["Task", "Note", "Question", "Agent"],
    activeKind: "Task",
  },
  dailyControl: {
    priority: "P0",
    title: "Daily Control",
    subtitle: "Current task + next queue",
    focus: {
      label: "Tagesfokus",
      title: "Masterarbeit Struktur",
      detail: "Literaturkapitel ordnen, keine neuen Quellen starten",
      blockLabel: "Fokusblock",
      block: "18:05-19:00 · 55 min",
    },
    nextStep: {
      label: "Nächster Schritt",
      title: "Abschnitt 2.3 neu sortieren",
      detail: "3 Quellen clustern, danach Review-Haken setzen",
    },
    currentTask: {
      sectionLabel: "Current Task",
      timeRemainingLabel: "18:32 · 25 min left",
      statusLabel: "Active Now",
      title: "Literaturstruktur überarbeiten",
      contextLabel: "Masterarbeit · hoher Fokus",
      actionLabel: "Continue current task",
      progress: 34,
      accent: "var(--accent-blue)",
      area: "education",
    },
    signals: [
      {
        kind: "energy",
        label: "Energy",
        value: "High focus",
        detail: "keine Side-Tasks",
        accent: "var(--accent-blue)",
      },
      {
        kind: "inbox",
        label: "Inbox",
        value: "3 review",
        detail: "nach Fokusblock",
        accent: "var(--accent-green)",
      },
      {
        kind: "review",
        label: "Review",
        value: "Open",
        detail: "21:30 closeout",
        accent: "var(--accent-cyan)",
      },
    ],
    queueTitle: "Up Next",
    queueSubtitle: "Nächste Schritte, priorisiert",
    queueSummary: "3 queued",
    queue: [
      {
        title: "Java/Hyperskill abschließen",
        meta: "Heute später · 30 min",
        tag: "Learn",
        area: "coding",
      },
      {
        title: "Daily Review ausfüllen",
        meta: "Abends · offen",
        tag: "Review",
        area: "review",
      },
      {
        title: "Inbox triagieren",
        meta: "3 offen · 10 min",
        tag: "Inbox",
        area: "review",
      },
    ],
  },
  todayAgenda: {
    priority: "P0",
    title: "Today Agenda",
    views: ["Day", "Week", "Month"],
    activeView: "Day",
    preparedViewsLabel: "Week and month views prepared",
    currentTimeLabel: "15:42",
    currentTimePositionPercent: 53.5,
    hours: [
      "06:00",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
      "24:00",
    ],
    events: [
      {
        title: "Morning Routine",
        time: "06:30-07:15 · 45 min",
        note: "Start baseline",
        areaLabel: "Personal",
        type: "routine",
        typeLabel: "Routine",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P1",
        nextAction: "Baseline abhaken",
        accent: "var(--accent-blue)",
        area: "personal",
        energy: "low",
        priority: "P1",
      },
      {
        title: "Deep Work: Masterarbeit",
        time: "08:00-10:00 · 120 min",
        note: "Literature extraction · source notes",
        areaLabel: "Education",
        type: "focus",
        typeLabel: "Focus",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P0",
        nextAction: "Notizen in Abschnitt 2.3 übertragen",
        tags: ["Focus", "high"],
        accent: "var(--accent-blue)",
        area: "education",
        energy: "high",
        priority: "P0",
        tall: true,
      },
      {
        title: "Team Standup",
        time: "10:15-10:45 · 30 min",
        note: "Sync + blockers",
        areaLabel: "Work",
        type: "meeting",
        typeLabel: "Meeting",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P1",
        nextAction: "Blocker in Work Notes notieren",
        accent: "var(--accent-blue)",
        area: "work",
        energy: "medium",
        priority: "P1",
      },
      {
        title: "Lunch & Walk",
        time: "12:00-13:00 · 60 min",
        note: "Reset + movement",
        areaLabel: "Health",
        type: "break",
        typeLabel: "Break",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P2",
        nextAction: "Meal + steps loggen",
        tags: ["Health", "low"],
        accent: "var(--accent-red)",
        area: "health",
        energy: "low",
        priority: "P2",
      },
      {
        title: "Open Focus Buffer",
        time: "13:30-14:30 · 60 min",
        note: "Free slot",
        areaLabel: "Review",
        type: "task",
        typeLabel: "Buffer",
        status: "blocked",
        statusLabel: "Blocked",
        relevanceLabel: "P1",
        nextAction: "Neu planen oder schließen",
        attentionLabel: "Needs decision",
        tags: ["Free", "medium"],
        accent: "var(--accent-blue)",
        area: "review",
        energy: "medium",
        priority: "P1",
      },
      {
        title: "Skill Practice: Figma",
        time: "15:30-16:30 · 60 min",
        note: "Life OS layout refinement",
        areaLabel: "Coding",
        type: "task",
        typeLabel: "Skill",
        status: "active",
        statusLabel: "Active",
        relevanceLabel: "P1",
        nextAction: "V5 spacing pass starten",
        attentionLabel: "Start here",
        tags: ["Skill", "medium"],
        accent: "var(--accent-purple)",
        area: "coding",
        energy: "medium",
        priority: "P1",
        active: true,
      },
      {
        title: "Workout / Run",
        time: "17:00-18:00 · 60 min",
        note: "Training planned",
        areaLabel: "Health",
        type: "training",
        typeLabel: "Training",
        status: "next",
        statusLabel: "Next",
        relevanceLabel: "P2",
        nextAction: "Easy run oder Recovery wählen",
        tags: ["Health", "medium"],
        accent: "var(--accent-red)",
        area: "health",
        energy: "medium",
        priority: "P2",
        strong: true,
      },
      {
        title: "Dinner: Protein Bowl",
        time: "19:00-19:30 · 30 min",
        note: "Nutrition target",
        areaLabel: "Nutrition",
        type: "meal",
        typeLabel: "Meal",
        status: "planned",
        statusLabel: "Planned",
        relevanceLabel: "P2",
        nextAction: "Protein-Ziel prüfen",
        accent: "var(--accent-yellow)",
        area: "nutrition",
        energy: "low",
        priority: "P2",
      },
      {
        title: "Journal & Plan Tomorrow",
        time: "21:30-22:00 · 30 min",
        note: "Daily review closeout",
        areaLabel: "Review",
        type: "review",
        typeLabel: "Review",
        status: "planned",
        statusLabel: "Planned",
        relevanceLabel: "P1",
        nextAction: "3 offene Loops schließen",
        attentionLabel: "Review open",
        accent: "var(--accent-purple)",
        area: "review",
        energy: "low",
        priority: "P1",
      },
    ],
  },
  inboxSignals: {
    priority: "P1",
    title: "Inbox Signals",
    summary: "5 open",
    openCount: 5,
    reviewCount: 3,
    items: [
      {
        title: "Agent context: dashboard spacing",
        type: "agent_context",
        area: "coding",
        status: "raw",
        reviewNeeded: true,
        meta: "agent_context · review needed",
      },
      {
        title: "Literature idea: chapter structure",
        type: "note",
        area: "education",
        status: "raw",
        reviewNeeded: true,
        meta: "note · education",
      },
      {
        title: "Meal prep grocery reminder",
        type: "task",
        area: "nutrition",
        status: "clarified",
        reviewNeeded: false,
        meta: "task · nutrition",
      },
      {
        title: "Question: Supabase RLS setup",
        type: "question",
        area: "coding",
        status: "raw",
        reviewNeeded: true,
        meta: "question · coding",
      },
    ],
  },
  habitTrackers: {
    priority: "P1",
    title: "Habit Trackers",
    windows: ["Morning", "Midday", "Evening"],
    activeWindow: "Morning",
    totalSlotsLabel: "7 per view · 21 total slots",
    addHabitLabel: "Add habit",
    addHabitMeta: "new tracker",
    habits: [
      { marker: "W", label: "Water", value: "1100 / 2200", done: 3, total: 5, area: "health" },
      { marker: "C", label: "Coffee", value: "2 / 4", done: 4, total: 5, area: "health" },
      { marker: "E", label: "Exercise", value: "3 / 6", done: 4, total: 5, area: "health" },
      { marker: "M", label: "Morning", value: "1 / 1", done: 5, total: 5, area: "personal" },
      { marker: "S", label: "Study", value: "2h / 3h", done: 3, total: 5, area: "education" },
      { marker: "B", label: "Mindful", value: "8 / 10 min", done: 4, total: 5, area: "health" },
      { marker: "P", label: "Meal Prep", value: "2 / 3", done: 4, total: 5, area: "nutrition" },
    ],
  },
  activePortfolio: {
    priority: "P1",
    title: "Active Portfolio",
    subtitle: "Unique active projects · next action first",
    viewTitle: "Portfolio View",
    viewSubtitle: "Switch content state",
    views: ["Project View", "Goal View", "Skill View"],
    activeView: "Project View",
    items: [
      {
        title: "Life OS App",
        label: "Coding",
        next: "Project view finalisieren",
        meta: "18 / 42 tasks",
        progress: 56,
        accent: "var(--accent-orange)",
        area: "coding",
        kind: "project",
      },
      {
        title: "Masterarbeit",
        label: "Education",
        next: "Literaturquelle eintragen",
        meta: "27 / 60 sources",
        progress: 68,
        accent: "var(--accent-blue)",
        area: "education",
        kind: "project",
      },
      {
        title: "Java / Hyperskill",
        label: "Skill",
        next: "Modul abschließen",
        meta: "9 / 22 lessons",
        progress: 41,
        accent: "var(--accent-purple)",
        area: "coding",
        kind: "skill",
      },
      {
        title: "Finanzinformatik",
        label: "Work",
        next: "Notizen für FI aufbereiten",
        meta: "3 / 9 items",
        progress: 33,
        accent: "var(--accent-green)",
        area: "work",
        kind: "project",
      },
    ],
  },
  weightLossGoal: {
    priority: "P2",
    title: "Weight Loss Goal",
    currentWeight: "75.0 kg",
    targetLabel: "Target 70.0 kg · -0.4 kg this week",
    progressLabel: "42% to goal",
    progress: 42,
    accent: "var(--accent-green)",
  },
  nutrientBalance: {
    priority: "P2",
    title: "Nutrient Balance",
    items: [
      {
        label: "Protein",
        value: "25 / 100 g",
        progress: 25,
        accent: "var(--accent-red)",
      },
      {
        label: "Carbs",
        value: "102 / 102 g",
        progress: 100,
        accent: "var(--accent-blue)",
      },
      {
        label: "Fat",
        value: "42 / 36 g",
        progress: 100,
        accent: "var(--accent-yellow)",
      },
    ],
  },
  meals: {
    priority: "P2",
    title: "Meals Today",
    items: [
      {
        type: "Breakfast",
        name: "Overnight Oats",
        kcal: "310 kcal",
        macros: ["P 8g", "C 38g", "F 6g"],
        area: "nutrition",
      },
      {
        type: "Lunch",
        name: "Steak Salad",
        kcal: "400 kcal",
        macros: ["P 58g", "C 10g", "F 20g"],
        area: "nutrition",
      },
      {
        type: "Dinner",
        name: "Protein Bowl",
        kcal: "690 kcal",
        macros: ["P 48g", "C 62g", "F 18g"],
        area: "nutrition",
      },
    ],
  },
  runningRecovery: {
    priority: "P2",
    title: "Running Tracker",
    subtitle: "Health view switch · current run state",
    modes: ["Running", "Muscle", "Recovery"],
    activeMode: "Running",
    stats: [
      { label: "Distance", value: "6.2 km", delta: "+0.8 km" },
      { label: "Pace", value: "5:42 / km", delta: "better" },
      { label: "Time", value: "35m 20s", delta: "+31s" },
    ],
    rhythm: {
      title: "Today is above your 7-day rhythm",
      detail: "6.2 km today · 4.9 km avg",
      progress: 78,
      statusLabel: "better",
      accent: "var(--accent-red)",
    },
  },
  antiRotActions: {
    priority: "P3",
    title: "Anti-Rot Actions / Bad Habit Reset Row",
    donePrompt: "Done?",
    actions: [
      {
        title: "10-minute walk",
        type: "Focus",
        bad: "Instagram refresh",
        effort: "Easy",
        time: "10 min",
        accent: "var(--accent-red)",
        area: "health",
      },
      {
        title: "Read 10 pages",
        type: "Reset",
        bad: "TikTok / Shorts",
        effort: "Medium",
        time: "20 min",
        accent: "var(--accent-purple)",
        area: "personal",
      },
      {
        title: "Do 1 priority task",
        type: "Discipline",
        bad: "Avoiding priority",
        effort: "Medium",
        time: "30 min",
        accent: "var(--accent-purple)",
        area: "review",
      },
      {
        title: "Cold water on face",
        type: "Health",
        bad: "Gaming instead of start",
        effort: "Easy",
        time: "5 min",
        accent: "var(--accent-red)",
        area: "health",
      },
      {
        title: "5-minute desk clean",
        type: "Environment",
        bad: "Messy desk loop",
        effort: "Easy",
        time: "5 min",
        accent: "var(--accent-purple)",
        area: "personal",
      },
    ],
  },
  challengesRewardFocus: {
    priority: "P3",
    title: "Challenges",
    summary: "Complete 2 challenges today",
    measurementLabel: "1 / 2 measurable · 1 rule active",
    rewardFocus: "Small reward after review closeout",
    items: [
      {
        title: "No Shorts after 18:00",
        type: "Rule",
        status: "Safe so far",
        footer: "mark at day end",
        progress: 0,
        area: "personal",
      },
      {
        title: "Run 2 km easy",
        type: "Health",
        status: "small win",
        footer: "mark done",
        progress: 65,
        area: "health",
      },
      {
        title: "Study block 45 min",
        type: "Deep focus",
        status: "small win",
        footer: "mark done",
        progress: 55,
        area: "education",
      },
    ],
  },
} satisfies DashboardMockData;
