import type { DashboardMockData } from "./types";

const filledMetricState = {
  hasHistory: true,
  hasPrimaryValue: true,
  itemCount: 1,
  state: "filled",
} as const;

export const dashboardMockData = {
  commandCenter: {
    priority: "P1",
    greeting: "Good evening, Anton",
    dateLabel: "Tuesday, 09 June",
    dayTypeLabel: "Work / Study Day",
    contentState: { capacity: 6, itemCount: 6, state: "filled" },
    metrics: [
      {
        label: "Tasks",
        value: "12 / 18",
        detail: "67% complete",
        progress: 67,
        accent: "var(--accent-blue)",
        area: "review",
        href: "/tasks?view=today",
      },
      {
        label: "Focus Time",
        value: "1h 40m",
        detail: "of 3h target",
        progress: 56,
        accent: "var(--accent-blue)",
        area: "education",
        href: "/tasks?view=today&focus=true",
      },
      {
        label: "Inbox",
        value: "5 open",
        detail: "3 need review",
        progress: 38,
        accent: "var(--accent-green)",
        area: "review",
        href: "/inbox",
      },
      {
        label: "Nutrition",
        value: "1,720",
        detail: "of 2,200 kcal",
        progress: 78,
        accent: "var(--accent-yellow)",
        area: "nutrition",
        href: "/nutrition/meal-planner?view=today",
      },
      {
        label: "Review Status",
        value: "Review open",
        detail: "Daily Review · 5 min",
        progress: 18,
        accent: "var(--accent-cyan)",
        area: "review",
        href: "/review/daily",
      },
      {
        label: "Sleep",
        value: "6h 12m",
        detail: "target 8h",
        progress: 77,
        accent: "var(--accent-blue)",
        area: "health",
        href: "/health/mental?section=sleep",
      },
    ],
    timeProgress: [
      { label: "Year 2026", value: "44%", progress: 44 },
      { label: "Month June", value: "43%", progress: 43 },
      { label: "Week 24", value: "71%", progress: 71 },
    ],
    timeProgressHref: "/timeline",
    weather: {
      temperatureLabel: "18°C cloudy",
      periodLabel: "Evening",
      conditionLabel: "cloudy",
    },
    moodCheck: {
      title: "Mood",
      eyebrow: "Wellbeing",
      prompt: "How do you feel?",
      moodLabel: "Content",
      detail: "stabil · fokusfähig · Stress im Blick",
      progressLabel: "Calm index",
      scoreLabel: "7.6 / 10",
      progress: 76,
      accent: "var(--accent-cyan)",
      href: "/health/mental",
      options: ["Content", "Calm", "Focused", "Tired", "Anxious", "Stressed"],
      activeOption: "Content",
    },
  },
  quickCapture: {
    priority: "P1",
    title: "Quick Thought",
    destinationLabel: "AI Inbox",
    placeholder: "Write a thought, task or instruction...",
    helperText: "Agent erkennt Task · Note · Question · Loop",
    captureLabel: "Capture",
    contentState: { capacity: 1, itemCount: 1, state: "filled" },
    kinds: ["Task", "Note", "Question", "Agent"],
    activeKind: "Task",
  },
  dailyControl: {
    priority: "P0",
    title: "Daily Control",
    subtitle: "Current task + next queue",
    contentState: { capacity: 4, itemCount: 4, state: "filled" },
    focus: {
      label: "Tagesfokus",
      title: "Masterarbeit Struktur",
      detail: "Literaturkapitel ordnen, keine neuen Quellen starten",
      blockLabel: "Fokusblock",
      block: "18:05-19:00 · 55 min",
    },
    nextStep: {
      label: "Nächster Schritt",
      title: "Abschnitt 2.3 neu sortieren",
      detail: "3 Quellen clustern, danach Review-Haken setzen",
    },
    currentTask: {
      id: "task-literature-structure",
      sectionLabel: "Current Task",
      timeRemainingLabel: "18:32 · 25 min left",
      statusLabel: "Active Now",
      title: "Literaturstruktur überarbeiten",
      contextLabel: "Masterarbeit · hoher Fokus",
      actionLabel: "Continue current task",
      progress: 34,
      accent: "var(--accent-blue)",
      area: "education",
      href: "/tasks/task-literature-structure",
    },
    signals: [
      {
        kind: "energy",
        label: "Energy",
        value: "High focus",
        detail: "keine Side-Tasks",
        accent: "var(--accent-blue)",
      },
      {
        kind: "inbox",
        label: "Inbox",
        value: "3 review",
        detail: "nach Fokusblock",
        accent: "var(--accent-green)",
      },
      {
        kind: "review",
        label: "Review",
        value: "Open",
        detail: "21:30 closeout",
        accent: "var(--accent-cyan)",
      },
    ],
    queueTitle: "Up Next",
    queueSubtitle: "Nächste Schritte, priorisiert",
    queueSummary: "3 queued",
    queue: [
      {
        id: "task-java-hyperskill-close",
        title: "Java/Hyperskill abschließen",
        meta: "Heute später · 30 min",
        tag: "Learn",
        area: "coding",
        href: "/tasks/task-java-hyperskill-close",
      },
      {
        id: "task-daily-review-closeout",
        title: "Daily Review ausfüllen",
        meta: "Abends · offen",
        tag: "Review",
        area: "review",
        href: "/tasks/task-daily-review-closeout",
      },
      {
        id: "task-inbox-triage",
        title: "Inbox triagieren",
        meta: "3 offen · 10 min",
        tag: "Inbox",
        area: "review",
        href: "/tasks/task-inbox-triage",
      },
    ],
  },
  todayAgenda: {
    priority: "P0",
    title: "Today Agenda",
    href: "/calendar?view=day&date=today",
    contentState: { capacity: 9, itemCount: 9, state: "filled" },
    views: ["Day", "Week", "Month"],
    activeView: "Day",
    preparedViewsLabel: "Week and month views prepared",
    currentTimeLabel: "15:42",
    currentTimePositionPercent: 53.5,
    hours: [
      "06:00",
      "07:00",
      "08:00",
      "09:00",
      "10:00",
      "11:00",
      "12:00",
      "13:00",
      "14:00",
      "15:00",
      "16:00",
      "17:00",
      "18:00",
      "19:00",
      "20:00",
      "21:00",
      "22:00",
      "23:00",
      "24:00",
    ],
    events: [
      {
        id: "block-morning-routine",
        title: "Morning Routine",
        time: "06:30-07:15 · 45 min",
        note: "Start baseline",
        areaLabel: "Personal",
        type: "routine",
        typeLabel: "Routine",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P1",
        nextAction: "Baseline abhaken",
        accent: "var(--accent-blue)",
        area: "personal",
        energy: "low",
        priority: "P1",
        href: "/calendar?view=day&date=today&block=block-morning-routine",
      },
      {
        id: "block-deep-work-masterarbeit",
        title: "Deep Work: Masterarbeit",
        time: "08:00-10:00 · 120 min",
        note: "Literature extraction · source notes",
        areaLabel: "Education",
        type: "focus",
        typeLabel: "Focus",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P0",
        nextAction: "Notizen in Abschnitt 2.3 übertragen",
        tags: ["Focus", "high"],
        accent: "var(--accent-blue)",
        area: "education",
        energy: "high",
        priority: "P0",
        tall: true,
        href: "/tasks/task-literature-structure",
      },
      {
        id: "block-team-standup",
        title: "Team Standup",
        time: "10:15-10:45 · 30 min",
        note: "Sync + blockers",
        areaLabel: "Work",
        type: "meeting",
        typeLabel: "Meeting",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P1",
        nextAction: "Blocker in Work Notes notieren",
        accent: "var(--accent-blue)",
        area: "work",
        energy: "medium",
        priority: "P1",
        href: "/calendar?view=day&date=today&block=block-team-standup",
      },
      {
        id: "block-lunch-walk",
        title: "Lunch & Walk",
        time: "12:00-13:00 · 60 min",
        note: "Reset + movement",
        areaLabel: "Health",
        type: "break",
        typeLabel: "Break",
        status: "done",
        statusLabel: "Done",
        relevanceLabel: "P2",
        nextAction: "Meal + steps loggen",
        tags: ["Health", "low"],
        accent: "var(--accent-red)",
        area: "health",
        energy: "low",
        priority: "P2",
        href: "/calendar?view=day&date=today&block=block-lunch-walk",
      },
      {
        id: "block-open-focus-buffer",
        title: "Open Focus Buffer",
        time: "13:30-14:30 · 60 min",
        note: "Free slot",
        areaLabel: "Review",
        type: "task",
        typeLabel: "Buffer",
        status: "blocked",
        statusLabel: "Blocked",
        relevanceLabel: "P1",
        nextAction: "Neu planen oder schließen",
        attentionLabel: "Needs decision",
        tags: ["Free", "medium"],
        accent: "var(--accent-blue)",
        area: "review",
        energy: "medium",
        priority: "P1",
        href: "/tasks/task-open-focus-buffer",
      },
      {
        id: "block-skill-practice-figma",
        title: "Skill Practice: Figma",
        time: "15:30-16:30 · 60 min",
        note: "Life OS layout refinement",
        areaLabel: "Coding",
        type: "task",
        typeLabel: "Skill",
        status: "active",
        statusLabel: "Active",
        relevanceLabel: "P1",
        nextAction: "V5 spacing pass starten",
        attentionLabel: "Start here",
        tags: ["Skill", "medium"],
        accent: "var(--accent-purple)",
        area: "coding",
        energy: "medium",
        priority: "P1",
        active: true,
        href: "/tasks/task-figma-practice",
      },
      {
        id: "block-workout-run",
        title: "Workout / Run",
        time: "17:00-18:00 · 60 min",
        note: "Training planned",
        areaLabel: "Health",
        type: "training",
        typeLabel: "Training",
        status: "next",
        statusLabel: "Next",
        relevanceLabel: "P2",
        nextAction: "Easy run oder Kraftslot wählen",
        tags: ["Health", "medium"],
        accent: "var(--accent-red)",
        area: "health",
        energy: "medium",
        priority: "P2",
        strong: true,
        href: "/health/workouts/workout-easy-run",
      },
      {
        id: "block-dinner-protein-bowl",
        title: "Dinner: Protein Bowl",
        time: "19:00-19:30 · 30 min",
        note: "Nutrition target",
        areaLabel: "Nutrition",
        type: "meal",
        typeLabel: "Meal",
        status: "planned",
        statusLabel: "Planned",
        relevanceLabel: "P2",
        nextAction: "Protein-Ziel prüfen",
        accent: "var(--accent-yellow)",
        area: "nutrition",
        energy: "low",
        priority: "P2",
        href: "/nutrition/recipes/protein-bowl",
      },
      {
        id: "block-journal-plan-tomorrow",
        title: "Journal & Plan Tomorrow",
        time: "21:30-22:00 · 30 min",
        note: "Daily review closeout",
        areaLabel: "Review",
        type: "review",
        typeLabel: "Review",
        status: "planned",
        statusLabel: "Planned",
        relevanceLabel: "P1",
        nextAction: "3 offene Loops schließen",
        attentionLabel: "Review open",
        accent: "var(--accent-purple)",
        area: "review",
        energy: "low",
        priority: "P1",
        href: "/tasks/task-daily-review-closeout",
      },
    ],
  },
  inboxSignals: {
    priority: "P1",
    title: "Inbox Signals",
    summary: "5 open",
    openCount: 5,
    reviewCount: 3,
    items: [
      {
        title: "Agent context: dashboard spacing",
        type: "agent_context",
        area: "coding",
        status: "raw",
        reviewNeeded: true,
        meta: "agent_context · review needed",
      },
      {
        title: "Literature idea: chapter structure",
        type: "note",
        area: "education",
        status: "raw",
        reviewNeeded: true,
        meta: "note · education",
      },
      {
        title: "Meal prep grocery reminder",
        type: "task",
        area: "nutrition",
        status: "clarified",
        reviewNeeded: false,
        meta: "task · nutrition",
      },
      {
        title: "Question: Supabase RLS setup",
        type: "question",
        area: "coding",
        status: "raw",
        reviewNeeded: true,
        meta: "question · coding",
      },
    ],
  },
  habitTrackers: {
    priority: "P1",
    title: "Habit Trackers",
    href: "/health/habits",
    contentState: { capacity: 8, itemCount: 7, state: "partial" },
    windows: ["Morning", "Midday", "Evening"],
    activeWindow: "Morning",
    totalSlotsLabel: "7 per view · 21 total slots",
    addHabitLabel: "Add habit",
    addHabitMeta: "new tracker",
    habitsByWindow: {
      Morning: [
        {
          id: "habit-water-morning",
          marker: "W",
          label: "Water",
          currentValue: 1100,
          targetValue: 2200,
          unit: "ml",
          stepValue: 250,
          total: 5,
          area: "health",
        },
        {
          id: "habit-coffee-morning",
          marker: "C",
          label: "Coffee",
          currentValue: 2,
          targetValue: 4,
          stepValue: 1,
          total: 5,
          area: "health",
        },
        {
          id: "habit-mobility-morning",
          marker: "M",
          label: "Mobility",
          currentValue: 1,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "health",
        },
        {
          id: "habit-study-morning",
          marker: "S",
          label: "Study",
          currentValue: 2,
          targetValue: 3,
          unit: "h",
          stepValue: 0.5,
          total: 5,
          area: "education",
        },
        {
          id: "habit-mindful-morning",
          marker: "B",
          label: "Mindful",
          currentValue: 8,
          targetValue: 10,
          unit: "min",
          stepValue: 2,
          total: 5,
          area: "health",
        },
        {
          id: "habit-meal-prep-morning",
          marker: "P",
          label: "Meal Prep",
          currentValue: 2,
          targetValue: 3,
          stepValue: 1,
          total: 5,
          area: "nutrition",
        },
        {
          id: "habit-planning-morning",
          marker: "D",
          label: "Day Plan",
          currentValue: 1,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "review",
        },
      ],
      Midday: [
        {
          id: "habit-lunch-midday",
          marker: "L",
          label: "Lunch logged",
          currentValue: 1,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "nutrition",
        },
        {
          id: "habit-walk-midday",
          marker: "W",
          label: "Walk",
          currentValue: 12,
          targetValue: 15,
          unit: "min",
          stepValue: 3,
          total: 5,
          area: "health",
        },
        {
          id: "habit-inbox-midday",
          marker: "I",
          label: "Inbox review",
          currentValue: 2,
          targetValue: 3,
          stepValue: 1,
          total: 5,
          area: "review",
        },
        {
          id: "habit-posture-midday",
          marker: "P",
          label: "Posture",
          currentValue: 3,
          targetValue: 5,
          stepValue: 1,
          total: 5,
          area: "health",
        },
        {
          id: "habit-hydration-midday",
          marker: "H",
          label: "Hydration",
          currentValue: 600,
          targetValue: 900,
          unit: "ml",
          stepValue: 150,
          total: 5,
          area: "health",
        },
        {
          id: "habit-focus-midday",
          marker: "F",
          label: "Focus reset",
          currentValue: 1,
          targetValue: 2,
          stepValue: 1,
          total: 5,
          area: "work",
        },
        {
          id: "habit-source-midday",
          marker: "Q",
          label: "Source note",
          currentValue: 0,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "education",
        },
      ],
      Evening: [
        {
          id: "habit-review-evening",
          marker: "R",
          label: "Daily Review",
          currentValue: 0,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "review",
        },
        {
          id: "habit-dinner-evening",
          marker: "D",
          label: "Dinner check",
          currentValue: 0,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "nutrition",
        },
        {
          id: "habit-reading-evening",
          marker: "B",
          label: "Read",
          currentValue: 10,
          targetValue: 20,
          unit: "pages",
          stepValue: 5,
          total: 5,
          area: "personal",
        },
        {
          id: "habit-stretch-evening",
          marker: "S",
          label: "Stretch",
          currentValue: 5,
          targetValue: 10,
          unit: "min",
          stepValue: 5,
          total: 5,
          area: "health",
        },
        {
          id: "habit-shutdown-evening",
          marker: "X",
          label: "Shutdown",
          currentValue: 0,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "work",
        },
        {
          id: "habit-screen-evening",
          marker: "N",
          label: "No Shorts",
          currentValue: 0,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "personal",
        },
        {
          id: "habit-sleep-evening",
          marker: "Z",
          label: "Sleep prep",
          currentValue: 0,
          targetValue: 1,
          stepValue: 1,
          total: 5,
          area: "health",
        },
      ],
    },
  },
  activePortfolio: {
    priority: "P1",
    title: "Active Portfolio",
    subtitle: "Unique active projects · next action first",
    contentState: { capacity: 4, itemCount: 4, state: "filled" },
    viewTitle: "Portfolio View",
    viewSubtitle: "Switch content state",
    href: "/portfolio?status=active",
    views: [
      {
        label: "Project View",
        href: "/portfolio?view=projects",
      },
      {
        label: "Goal View",
        href: "/portfolio?view=goals",
      },
      {
        label: "Skill View",
        href: "/portfolio?view=skills",
      },
    ],
    activeView: "Project View",
    items: [
      {
        id: "portfolio-life-os-app",
        title: "Life OS App",
        label: "Coding",
        next: "Project view finalisieren",
        meta: "18 / 42 tasks",
        progress: 56,
        accent: "var(--accent-orange)",
        area: "coding",
        kind: "project",
        href: "/projects/portfolio-life-os-app",
      },
      {
        id: "portfolio-masterarbeit",
        title: "Masterarbeit",
        label: "Education",
        next: "Literaturquelle eintragen",
        meta: "27 / 60 sources",
        progress: 68,
        accent: "var(--accent-blue)",
        area: "education",
        kind: "project",
        href: "/projects/portfolio-masterarbeit",
      },
      {
        id: "portfolio-java-hyperskill",
        title: "Java / Hyperskill",
        label: "Skill",
        next: "Modul abschließen",
        meta: "9 / 22 lessons",
        progress: 41,
        accent: "var(--accent-purple)",
        area: "coding",
        kind: "skill",
        href: "/skills/portfolio-java-hyperskill",
      },
      {
        id: "portfolio-life-os-mvp",
        title: "Life OS MVP",
        label: "Goal",
        next: "Static App nutzbar machen",
        meta: "4 linked projects",
        progress: 58,
        accent: "var(--accent-purple)",
        area: "coding",
        kind: "goal",
        href: "/goals/portfolio-life-os-mvp",
      },
      {
        id: "portfolio-masterarbeit-goal",
        title: "Masterarbeit abgeben",
        label: "Goal",
        next: "Quellenentscheidung klären",
        meta: "2 projects linked",
        progress: 37,
        accent: "var(--accent-blue)",
        area: "education",
        kind: "goal",
        href: "/goals/portfolio-masterarbeit-goal",
      },
      {
        id: "portfolio-finanzinformatik",
        title: "Finanzinformatik",
        label: "Work",
        next: "Notizen für FI aufbereiten",
        meta: "3 / 9 items",
        progress: 33,
        accent: "var(--accent-green)",
        area: "work",
        kind: "project",
        href: "/projects/portfolio-finanzinformatik",
      },
    ],
  },
  weightLossGoal: {
    priority: "P2",
    title: "Weight Loss Goal",
    href: "/health",
    contentState: filledMetricState,
    currentWeight: "75.0 kg",
    targetLabel: "Target 70.0 kg · -0.4 kg this week",
    remainingLabel: "5.0 kg to goal",
    weeklyStatusLabel: "On track",
    weeklyStatusAccent: "var(--accent-green)",
    progress: 42,
    accent: "var(--accent-green)",
  },
  nutrientBalance: {
    priority: "P2",
    title: "Nutrient Balance",
    href: "/nutrition/meal-planner?view=today",
    contentState: { capacity: 3, itemCount: 3, state: "filled" },
    lastUpdatedLabel: "Nutrition plan updated: today 12:10",
    items: [
      {
        label: "Protein",
        value: "25 / 100 g",
        status: "Under",
        progress: 25,
        accent: "var(--accent-red)",
        statusAccent: "var(--accent-orange)",
      },
      {
        label: "Carbs",
        value: "102 / 102 g",
        status: "On target",
        progress: 100,
        accent: "var(--accent-blue)",
        statusAccent: "var(--accent-green)",
      },
      {
        label: "Fat",
        value: "42 / 36 g",
        status: "Over",
        progress: 100,
        accent: "var(--accent-yellow)",
        statusAccent: "var(--accent-orange)",
      },
    ],
  },
  meals: {
    priority: "P2",
    title: "Meals Today",
    href: "/nutrition/meal-planner?view=today",
    contentState: { capacity: 3, itemCount: 3, state: "filled" },
    currentTimeLabel: "15:42",
    recipeOptions: [],
    items: [
      {
        recipeId: "skyr-oats",
        mealId: "breakfast",
        type: "Breakfast",
        name: "Skyr with oats and berries",
        time: "07:30",
        kcal: "435 kcal",
        macros: ["P 40g", "C 55g", "F 5g"],
        area: "nutrition",
        href: "/nutrition/recipes/skyr-oats",
      },
      {
        recipeId: "chicken-wrap",
        mealId: "lunch",
        type: "Lunch",
        name: "Chicken wrap",
        time: "12:30",
        kcal: "560 kcal",
        macros: ["P 56g", "C 45g", "F 17g"],
        area: "nutrition",
        href: "/nutrition/recipes/chicken-wrap",
      },
      {
        recipeId: "protein-bowl",
        mealId: "dinner",
        type: "Dinner",
        name: "Protein bowl with vegetables",
        time: "19:00",
        kcal: "649 kcal",
        macros: ["P 56g", "C 55g", "F 22g"],
        area: "nutrition",
        href: "/nutrition/recipes/protein-bowl",
      },
    ],
  },
  runningRecovery: {
    priority: "P2",
    title: "Running Tracker",
    subtitle: "Workout data · periodic sync",
    href: "/health/running",
    contentState: filledMetricState,
    modes: ["Running", "Muscle"],
    activeMode: "Running",
    stats: [
      { label: "Distance", value: "6.2 km", delta: "+0.8 km" },
      { label: "Pace", value: "5:42 / km", delta: "better" },
      { label: "Time", value: "35m 20s", delta: "+31s" },
    ],
    rhythm: {
      title: "Better than 7-day rhythm",
      detail: "6.2 km today · 4.9 km avg",
      progress: 78,
      statusLabel: "Better",
      accent: "var(--accent-red)",
    },
    todayGoalLabel: "Today goal: 6.0 km easy",
    lastSyncLabel: "Last Health/Garmin sync: yesterday 23:58",
    muscle: {
      workoutId: "workout-upper-a",
      title: "Upper A planned",
      detail: "Last strength session: Sunday · 42 min",
      focusGroups: ["Chest", "Back", "Core"],
      nextStep: "Next: incline press · set 1",
      statusLabel: "Planned",
      href: "/health/workouts/workout-upper-a",
    },
  },
  antiRotActions: {
    priority: "P3",
    title: "Anti-Rot Actions / Bad Habit Reset Row",
    href: "/health/habits?view=bad-habits",
    contentState: { capacity: 5, itemCount: 5, state: "filled" },
    donePrompt: "Done?",
    actions: [
      {
        id: "anti-rot-walk",
        title: "10-minute walk",
        type: "Focus",
        bad: "Instagram refresh",
        effort: "Easy",
        time: "10 min",
        accent: "var(--accent-red)",
        area: "health",
      },
      {
        id: "anti-rot-read",
        title: "Read 10 pages",
        type: "Reset",
        bad: "TikTok / Shorts",
        effort: "Medium",
        time: "20 min",
        accent: "var(--accent-purple)",
        area: "personal",
      },
      {
        id: "anti-rot-priority-task",
        title: "Do 1 priority task",
        type: "Discipline",
        bad: "Avoiding priority",
        effort: "Medium",
        time: "30 min",
        accent: "var(--accent-purple)",
        area: "review",
      },
      {
        id: "anti-rot-cold-water",
        title: "Cold water on face",
        type: "Health",
        bad: "Gaming instead of start",
        effort: "Easy",
        time: "5 min",
        accent: "var(--accent-red)",
        area: "health",
      },
      {
        id: "anti-rot-desk-clean",
        title: "5-minute desk clean",
        type: "Environment",
        bad: "Messy desk loop",
        effort: "Easy",
        time: "5 min",
        accent: "var(--accent-purple)",
        area: "personal",
      },
    ],
  },
  challengesRewardFocus: {
    priority: "P3",
    title: "Challenges",
    href: "/challenges",
    contentState: { capacity: 3, itemCount: 3, state: "filled" },
    summary: "Complete 2 challenges today",
    measurementLabel: "1 / 2 measurable · 1 rule active",
    rewardFocus: "Small reward after review closeout",
    items: [
      {
        id: "challenge-no-shorts-evening",
        title: "No Shorts after 18:00",
        cadence: "Daily",
        tracking: "manual",
        sourceLabel: "Needs confirmation",
        type: "Rule",
        status: "Pending",
        footer: "Confirm at day end",
        progress: 0,
        completed: false,
        area: "personal",
      },
      {
        id: "challenge-run-easy",
        title: "Run 2 km easy",
        cadence: "Daily",
        tracking: "auto",
        sourceLabel: "Auto tracked",
        type: "Health",
        status: "In progress",
        footer: "From last workout mock",
        progress: 65,
        completed: false,
        area: "health",
      },
      {
        id: "challenge-study-block",
        title: "Study block 45 min",
        cadence: "Daily",
        tracking: "auto",
        sourceLabel: "Auto tracked",
        type: "Deep focus",
        status: "Done",
        footer: "From agenda mock",
        progress: 55,
        completed: true,
        area: "education",
      },
      {
        id: "challenge-three-runs-week",
        title: "3 runs this week",
        cadence: "Weekly",
        tracking: "auto",
        sourceLabel: "Auto tracked",
        type: "Health",
        status: "2 / 3 logged",
        footer: "Last sync yesterday",
        progress: 66,
        completed: false,
        area: "health",
      },
      {
        id: "challenge-review-four-days",
        title: "Daily Review 4 days",
        cadence: "Weekly",
        tracking: "manual",
        sourceLabel: "Needs confirmation",
        type: "Review",
        status: "3 / 4 confirmed",
        footer: "Confirm after closeout",
        progress: 75,
        completed: false,
        area: "review",
      },
      {
        id: "challenge-mvp-milestone",
        title: "Ship one Life OS milestone",
        cadence: "Monthly",
        tracking: "manual",
        sourceLabel: "Needs confirmation",
        type: "Portfolio",
        status: "Needs review",
        footer: "Confirm when milestone is real",
        progress: 40,
        completed: false,
        area: "coding",
      },
    ],
  },
} satisfies DashboardMockData;
