import {
  containsExportCredential,
  sameOriginExportRequest,
} from "@/features/obsidian-projection/export-security";
import { createAuthenticatedSupabaseServerClient } from "@/lib/supabase/server";
import { getCurrentLifeOsProfileId } from "@/features/profile-data/profile-cookie";
import {
  readProjectProjection,
  projectExportInput,
  ProjectionReadError,
} from "@/features/real-data/supabase/repositories/project-projection-read";
import {
  contentHash,
  projectMarkdown,
} from "@/features/obsidian-projection/project-markdown";
import { zipPackage } from "@/features/obsidian-projection/zip-package";
export const runtime = "nodejs";
const headers = {
  "Cache-Control": "private, no-store",
  "X-Content-Type-Options": "nosniff",
};
const error = (message: string, status: number) =>
  Response.json({ message }, { status, headers });
export async function POST(
  request: Request,
  context: { params: Promise<{ projectId: string }> },
) {
  if (!sameOriginExportRequest(request))
    return error("Export nur direkt aus Life OS möglich.", 403);
  if ((await getCurrentLifeOsProfileId()) !== "manual")
    return error("Der Export benötigt das Manual-Profil.", 403);
  const auth = await createAuthenticatedSupabaseServerClient();
  if (!auth.ok)
    return error("Bitte lokal anmelden und erneut exportieren.", 401);
  const input = projectExportInput.safeParse(await context.params);
  if (!input.success) return error("Ungültiges Project.", 400);
  try {
    const source = await readProjectProjection(
      auth.client,
      auth.user.id,
      input.data,
    );
    // No transaction/migration is introduced for export. Detect changes across two
    // bounded reads; inconsistent snapshots fail visibly instead of shipping stale edges.
    const verification = await readProjectProjection(
      auth.client,
      auth.user.id,
      input.data,
    );
    if (
      contentHash(JSON.stringify(source)) !==
      contentHash(JSON.stringify(verification))
    )
      return error(
        "Project-Daten haben sich geändert. Bitte erneut exportieren.",
        409,
      );
    const projection = projectMarkdown(source);
    const manifest = JSON.stringify(projection.manifest, null, 2) + "\n";
    const files = [
      { path: ".life-os-projection.json", content: manifest },
      ...projection.files,
      {
        path: "README.md",
        content:
          "# Generated by Life OS\n\nLife OS / PostgreSQL remains canonical.\n\nOpen this extracted folder as a vault in Obsidian. No plugin is required.\n\nManual status edits are not synchronized. This is a snapshot, not sync.\nUse a separate folder for each export; do not replace personal vault files.\nArchived notes are labelled history. Removed sources do not authorize deleting user files.\nURL credentials, query parameters and fragments are omitted.\n",
      },
    ];
    // Defense in depth for accidentally pasted common credentials. No system secrets,
    // auth session or provider configuration is ever part of the source allowlist.
    if (files.some((f) => containsExportCredential(f.content)))
      return error(
        "Export enthält möglicherweise Zugangsdaten. Bitte entferne sie aus dem Project-Kontext.",
        422,
      );
    const zip = zipPackage(
      files.map((f) => ({
        path: `${projection.folder}/${f.path}`,
        content: f.content,
      })),
    );
    return new Response(zip, {
      headers: {
        ...headers,
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${projection.folder}.zip"`,
      },
    });
  } catch (cause) {
    return error(
      cause instanceof ProjectionReadError
        ? cause.message
        : "Export konnte nicht erstellt werden. Bitte erneut versuchen.",
      422,
    );
  }
}
