import type { WorkDecisionInput, WorkWikiInput } from "../../schemas/work.schemas";
import type { SupabaseClientLike } from "../database.types";
import { mapWorkDecisionRow } from "../mappers/work-decision.mapper";
import { createSupabaseWorkRepository } from "./supabase-work-repository";
import type { WorkDecision, WorkWikiEntry } from "@/features/work/work-decision";

const fail = (error: string) => ({ error, ok: false as const });

export function createSupabaseWorkKnowledgeRepository(client: SupabaseClientLike) {
  const work = createSupabaseWorkRepository(client);
  async function project(userId: string, projectId: string) { const areaId = await work.ensureArea(userId); if (!areaId) return null; const result = await client.from("projects").select("id,title").eq("user_id", userId).eq("area_id", areaId).eq("id", projectId).is("archived_at", null).maybeSingle(); return result.data; }
  async function wiki(userId: string, resourceId: string) { const areaId = await work.ensureArea(userId); if (!areaId) return null; const result = await client.from("resources").select("id").eq("user_id", userId).eq("area_id", areaId).eq("type", "note").eq("id", resourceId).is("archived_at", null).maybeSingle(); return result.data; }
  return {
    async createWiki(userId: string, input: WorkWikiInput) { const areaId = await work.ensureArea(userId); if (!areaId || input.projectId && !(await project(userId, input.projectId))) return fail("Work project unavailable."); const created = await client.from("resources").insert({ user_id: userId, area_id: areaId, type: "note", title: input.title, summary: input.body }).select("id").single(); if (created.error || !created.data) return fail("Work wiki create failed."); if (input.projectId) { const linked = await client.from("resource_relations").insert({ user_id: userId, resource_id: created.data.id, target_type: "project", target_id: input.projectId, relation_type: "context" }); if (linked.error) return fail("Work wiki link failed."); } return { data: created.data, ok: true as const }; },
    async updateWiki(userId: string, resourceId: string, input: WorkWikiInput) { if (!(await wiki(userId, resourceId))) return fail("Work wiki unavailable."); const result = await client.from("resources").update({ title: input.title, summary: input.body }).eq("user_id", userId).eq("id", resourceId).select("id").maybeSingle(); return result.error || !result.data ? fail("Work wiki update failed.") : { data: result.data, ok: true as const }; },
    async archiveWiki(userId: string, resourceId: string) { if (!(await wiki(userId, resourceId))) return fail("Work wiki unavailable."); const result = await client.from("resources").update({ archived_at: new Date().toISOString() }).eq("user_id", userId).eq("id", resourceId).is("archived_at", null).select("id").maybeSingle(); return result.error || !result.data ? fail("Work wiki archive failed.") : { data: result.data, ok: true as const }; },
    async createDecision(userId: string, input: WorkDecisionInput) { if (!(await project(userId, input.projectId))) return fail("Work project unavailable."); const result = await client.from("work_decisions").insert({ user_id: userId, project_id: input.projectId, decision_date: input.decisionDate, title: input.title, decision: input.decision, rationale: input.rationale ?? null, status: input.status }).select("id").single(); return result.error || !result.data ? fail("Work decision create failed.") : { data: result.data, ok: true as const }; },
    async updateDecision(userId: string, decisionId: string, input: WorkDecisionInput) { if (!(await project(userId, input.projectId))) return fail("Work project unavailable."); const result = await client.from("work_decisions").update({ decision_date: input.decisionDate, title: input.title, decision: input.decision, rationale: input.rationale ?? null, status: input.status }).eq("user_id", userId).eq("id", decisionId).eq("project_id", input.projectId).is("archived_at", null).select("id").maybeSingle(); return result.error || !result.data ? fail("Work decision update failed.") : { data: result.data, ok: true as const }; },
    async archiveDecision(userId: string, projectId: string, decisionId: string) { if (!(await project(userId, projectId))) return fail("Work project unavailable."); const result = await client.from("work_decisions").update({ archived_at: new Date().toISOString() }).eq("user_id", userId).eq("project_id", projectId).eq("id", decisionId).is("archived_at", null).select("id").maybeSingle(); return result.error || !result.data ? fail("Work decision archive failed.") : { data: result.data, ok: true as const }; },
    async getKnowledge(userId: string): Promise<{ wiki: WorkWikiEntry[]; decisions: WorkDecision[] }> { const areaId = await work.ensureArea(userId); if (!areaId) return { wiki: [], decisions: [] }; const [projects, resources, relations, decisions] = await Promise.all([client.from("projects").select("id,title").eq("user_id", userId).eq("area_id", areaId).is("archived_at", null), client.from("resources").select("id,title,summary,archived_at").eq("user_id", userId).eq("area_id", areaId).eq("type", "note").order("updated_at", { ascending: false }), client.from("resource_relations").select("resource_id,target_id").eq("user_id", userId).eq("target_type", "project"), client.from("work_decisions").select("*").eq("user_id", userId).order("decision_date", { ascending: false }).order("created_at", { ascending: false })]); const titleById = new Map((projects.data ?? []).map((item) => [item.id, item.title])); const relationByResource = new Map((relations.data ?? []).filter((item) => titleById.has(item.target_id)).map((item) => [item.resource_id, item.target_id])); return { wiki: (resources.data ?? []).map((item) => { const projectId = relationByResource.get(item.id) ?? null; return { archivedAt: item.archived_at, body: item.summary, id: item.id, projectId, projectTitle: projectId ? titleById.get(projectId) ?? null : null, title: item.title }; }), decisions: (decisions.data ?? []).flatMap((item) => { const projectTitle = titleById.get(item.project_id); return projectTitle ? [mapWorkDecisionRow(item, projectTitle)] : []; }) }; },
  };
}
