import type { WorkMeetingInput } from "../../schemas/work.schemas";
import type { SupabaseClientLike } from "../database.types";
import { mapWorkMeetingRow } from "../mappers/work-meeting.mapper";
import { createSupabaseWorkRepository } from "./supabase-work-repository";
import type { WorkMeeting } from "@/features/work/work-meeting";
const fail = (error: string) => ({ error, ok: false as const });
export function createSupabaseWorkMeetingRepository(client: SupabaseClientLike) { const work = createSupabaseWorkRepository(client); async function project(userId: string, projectId: string) { const areaId = await work.ensureArea(userId); if (!areaId) return null; const r = await client.from("projects").select("id,title").eq("user_id", userId).eq("area_id", areaId).eq("id", projectId).is("archived_at", null).maybeSingle(); return r.data; } async function meeting(userId: string, meetingId: string) { const r = await client.from("work_meetings").select("id,project_id").eq("user_id", userId).eq("id", meetingId).is("archived_at", null).maybeSingle(); return r.data; } return {
  async createMeeting(userId: string, input: WorkMeetingInput) { if (!(await project(userId, input.projectId))) return fail("Work project unavailable."); const r = await client.from("work_meetings").insert({ user_id: userId, project_id: input.projectId, meeting_date: input.meetingDate, started_at: input.startedAt ?? null, duration_minutes: input.durationMinutes, title: input.title, participants: input.participants ?? null, agenda: input.agenda ?? null, outcome: input.outcome, notes: input.notes ?? null }).select("id").single(); return r.error || !r.data ? fail("Work meeting create failed.") : { data: r.data, ok: true as const }; },
  async updateMeeting(userId: string, meetingId: string, input: WorkMeetingInput) { if (!(await project(userId, input.projectId))) return fail("Work project unavailable."); const r = await client.from("work_meetings").update({ meeting_date: input.meetingDate, started_at: input.startedAt ?? null, duration_minutes: input.durationMinutes, title: input.title, participants: input.participants ?? null, agenda: input.agenda ?? null, outcome: input.outcome, notes: input.notes ?? null }).eq("user_id", userId).eq("id", meetingId).eq("project_id", input.projectId).is("archived_at", null).select("id").maybeSingle(); return r.error || !r.data ? fail("Work meeting update failed.") : { data: r.data, ok: true as const }; },
  async archiveMeeting(userId: string, projectId: string, meetingId: string) { if (!(await project(userId, projectId))) return fail("Work project unavailable."); const r = await client.from("work_meetings").update({ archived_at: new Date().toISOString() }).eq("user_id", userId).eq("id", meetingId).eq("project_id", projectId).is("archived_at", null).select("id").maybeSingle(); return r.error || !r.data ? fail("Work meeting archive failed.") : { data: r.data, ok: true as const }; },
  async linkFollowup(userId: string, meetingId: string, taskId: string) { const m = await meeting(userId, meetingId); if (!m) return fail("Work meeting unavailable."); const t = await client.from("tasks").select("id").eq("user_id", userId).eq("id", taskId).is("archived_at", null).maybeSingle(); if (!t.data) return fail("Follow-up task unavailable."); const r = await client.from("work_meeting_followups").insert({ user_id: userId, meeting_id: meetingId, task_id: taskId }).select("id").single(); return r.error || !r.data ? fail("Follow-up link failed.") : { data: r.data, ok: true as const }; },
  async createFollowup(userId: string, meetingId: string, title: string, description?: string) { const m = await meeting(userId, meetingId); if (!m) return fail("Work meeting unavailable."); const r = await client.rpc("create_work_meeting_followup", { p_meeting_id: meetingId, p_title: title, p_description: description }); return r.error || !r.data ? fail("Follow-up create failed.") : { data: { id: r.data as string }, ok: true as const }; },
  async unlinkFollowup(userId: string, meetingId: string, relationId: string) { const r = await client.from("work_meeting_followups").delete().eq("user_id", userId).eq("meeting_id", meetingId).eq("id", relationId).select("id").maybeSingle(); return r.error || !r.data ? fail("Follow-up unlink failed.") : { data: r.data, ok: true as const }; },
  async getMeetings(userId: string): Promise<WorkMeeting[]> { const areaId = await work.ensureArea(userId); if (!areaId) return []; const [projects, meetings, links] = await Promise.all([client.from("projects").select("id,title").eq("user_id", userId).eq("area_id", areaId).is("archived_at", null), client.from("work_meetings").select("*").eq("user_id", userId).order("meeting_date", { ascending: false }).order("created_at", { ascending: false }), client.from("work_meeting_followups").select("id,meeting_id,task_id,tasks!inner(id,title,status,archived_at,user_id)").eq("user_id", userId)]); const titles = new Map((projects.data ?? []).map((p) => [p.id, p.title])); const followups = new Map<string, WorkMeeting["followups"]>(); for (const link of links.data ?? []) { const task = Array.isArray(link.tasks) ? link.tasks[0] : link.tasks; if (task?.user_id === userId) { const list = followups.get(link.meeting_id) ?? []; list.push({ archivedAt: task.archived_at, relationId: link.id, status: task.status, taskId: task.id, title: task.title }); followups.set(link.meeting_id, list); } } return (meetings.data ?? []).flatMap((item) => { const title = titles.get(item.project_id); return title ? [mapWorkMeetingRow(item, title, followups.get(item.id) ?? [])] : []; }); },
}; }
