import { aggregateChallengeProgress, latestActiveProgressLog, rewardBalance, sortChallenges, type ChallengeWorkspace } from "../../domain/challenge";
import type { ChallengeInput, ChallengeProgressInput, UpdateChallengeInput, UpdateChallengeProgressInput } from "../../schemas/challenge.schemas";
import type { SupabaseClientLike } from "../database.types";
import { mapChallenge, mapChallengeLog, mapRewardLedger } from "../mappers/challenge.mapper";
function failure(message: string) { return { error: message, ok: false as const }; }
export function createSupabaseChallengeRepository(client: SupabaseClientLike) {
  async function ownedActive(userId: string, id: string) { const result = await client.from("challenges").select("*").eq("user_id", userId).eq("id", id).eq("status", "active").is("archived_at", null).maybeSingle(); return result.error || !result.data ? null : mapChallenge(result.data); }
  return {
    async getWorkspace(userId: string): Promise<ChallengeWorkspace> { const [challenges, logs, ledger] = await Promise.all([client.from("challenges").select("*").eq("user_id", userId).order("updated_at", { ascending: false }).order("id"), client.from("challenge_progress_logs").select("*").eq("user_id", userId).order("recorded_at", { ascending: false }).order("id", { ascending: false }), client.from("reward_ledger_entries").select("*").eq("user_id", userId).order("created_at", { ascending: false }).order("id", { ascending: false })]); const entries = (ledger.data ?? []).map(mapRewardLedger); return { balance: rewardBalance(entries), challenges: sortChallenges((challenges.data ?? []).map(mapChallenge)), ledger: entries, logs: (logs.data ?? []).map(mapChallengeLog) }; },
    async createChallenge(userId: string, input: ChallengeInput) { const result = await client.from("challenges").insert({ description: input.description, end_date: input.endDate, period_type: input.periodType, reward_coins: input.rewardCoins, start_date: input.startDate, target_value: input.targetValue, title: input.title, unit: input.unit, user_id: userId }).select("*").single(); return result.error || !result.data ? failure("Challenge could not be created.") : { data: mapChallenge(result.data), ok: true as const }; },
    async updateChallenge(userId: string, input: UpdateChallengeInput) { if (!(await ownedActive(userId, input.challengeId))) return failure("Challenge is unavailable."); const result = await client.from("challenges").update({ description: input.description, end_date: input.endDate, period_type: input.periodType, reward_coins: input.rewardCoins, start_date: input.startDate, target_value: input.targetValue, title: input.title, unit: input.unit }).eq("user_id", userId).eq("id", input.challengeId).eq("status", "active").is("archived_at", null).select("*").maybeSingle(); return result.error || !result.data ? failure("Challenge could not be updated.") : { data: mapChallenge(result.data), ok: true as const }; },
    async addProgress(userId: string, input: ChallengeProgressInput) { if (!(await ownedActive(userId, input.challengeId))) return failure("Challenge is unavailable."); const result = await client.from("challenge_progress_logs").insert({ challenge_id: input.challengeId, increment: input.increment, note: input.note, user_id: userId }).select("*").single(); return result.error || !result.data ? failure("Progress could not be logged.") : { data: mapChallengeLog(result.data), ok: true as const }; },
    async updateLatestProgress(userId: string, input: UpdateChallengeProgressInput) { const challenge = await ownedActive(userId, input.challengeId); if (!challenge) return failure("Challenge is unavailable."); const logs = await client.from("challenge_progress_logs").select("*").eq("user_id", userId).eq("challenge_id", input.challengeId).is("archived_at", null).order("recorded_at", { ascending: false }).order("id", { ascending: false }); const latest = latestActiveProgressLog((logs.data ?? []).map(mapChallengeLog)); if (!latest || latest.id !== input.progressLogId) return failure("Only the latest progress log can be changed."); const result = await client.from("challenge_progress_logs").update({ increment: input.increment, note: input.note }).eq("user_id", userId).eq("id", input.progressLogId).select("*").maybeSingle(); return result.error || !result.data ? failure("Progress could not be updated.") : { data: mapChallengeLog(result.data), ok: true as const }; },
    async archiveLatestProgress(userId: string, challengeId: string, progressLogId: string) { const challenge = await ownedActive(userId, challengeId); if (!challenge) return false; const logs = await client.from("challenge_progress_logs").select("*").eq("user_id", userId).eq("challenge_id", challengeId).is("archived_at", null).order("recorded_at", { ascending: false }).order("id", { ascending: false }); const latest = latestActiveProgressLog((logs.data ?? []).map(mapChallengeLog)); if (!latest || latest.id !== progressLogId) return false; const result = await client.from("challenge_progress_logs").update({ archived_at: new Date().toISOString() }).eq("user_id", userId).eq("id", progressLogId); return !result.error; },
    async complete(userId: string, challengeId: string) { if (!(await ownedActive(userId, challengeId))) { const existing = await client.from("challenges").select("id").eq("user_id", userId).eq("id", challengeId).eq("status", "completed").maybeSingle(); if (!existing.data) return failure("Challenge is unavailable."); } const result = await client.rpc("complete_challenge_with_reward", { p_challenge_id: challengeId }); return result.error || !result.data ? failure("Target is not reached or completion failed.") : { data: { id: result.data }, ok: true as const }; },
    async setStatus(userId: string, challengeId: string, status: "abandoned") { if (!(await ownedActive(userId, challengeId))) return false; const result = await client.from("challenges").update({ status }).eq("user_id", userId).eq("id", challengeId).eq("status", "active").is("archived_at", null); return !result.error; },
    async archive(userId: string, challengeId: string) { const result = await client.from("challenges").update({ archived_at: new Date().toISOString() }).eq("user_id", userId).eq("id", challengeId).is("archived_at", null); return !result.error; },
    progressFor(challengeId: string, logs: ChallengeWorkspace["logs"]) { return aggregateChallengeProgress(logs.filter((log) => log.challengeId === challengeId)); },
  };
}
