import type {
  MealPlanSlot,
  MealPlanWeek,
  MealType,
  NutritionProfile,
  PlannedMeal,
  Recipe,
} from "./meal-planner-types";
import { mealTypes } from "./meal-planner-utils";

export const nutritionProfiles: readonly NutritionProfile[] = [
  {
    id: "normal",
    name: "Normal",
    description: "Default planning targets for a balanced week.",
    targets: {
      calories: 2000,
      protein: 165,
      carbs: 146,
      fat: 65,
    },
  },
  {
    id: "high-protein",
    name: "High Protein",
    description: "Keeps protein higher while calories stay moderate.",
    targets: {
      calories: 2100,
      protein: 190,
      carbs: 145,
      fat: 60,
    },
  },
  {
    id: "low-carb",
    name: "Low Carb",
    description: "Lower carb target with a higher fat allowance.",
    targets: {
      calories: 2000,
      protein: 170,
      carbs: 95,
      fat: 85,
    },
  },
  {
    id: "cut",
    name: "Cut",
    description: "Smaller calorie target for later settings alignment.",
    targets: {
      calories: 1850,
      protein: 170,
      carbs: 120,
      fat: 55,
    },
  },
  {
    id: "maintenance",
    name: "Maintenance",
    description: "Higher energy target for a stable routine week.",
    targets: {
      calories: 2300,
      protein: 160,
      carbs: 235,
      fat: 75,
    },
  },
];

export const recipes: readonly Recipe[] = [
  {
    id: "skyr-oats",
    title: "Skyr with oats and berries",
    description: "Cold high-protein breakfast bowl for fast weekday planning.",
    mealTypes: ["breakfast"],
    tags: ["high-protein", "quick", "vegetarian"],
    defaultServings: 1,
    prepMinutes: 8,
    cookMinutes: 0,
    imageUrl: "/images/recipes/skyr-oats.svg",
    imageAlt: "Abstract bowl with oats and berries",
    ingredients: [
      {
        id: "skyr",
        name: "Skyr",
        amount: 300,
        unit: "g",
        calories: 195,
        protein: 33,
        carbs: 12,
        fat: 1,
      },
      {
        id: "oats",
        name: "Oats",
        amount: 50,
        unit: "g",
        calories: 190,
        protein: 6,
        carbs: 31,
        fat: 4,
      },
      {
        id: "berries",
        name: "Berries",
        amount: 100,
        unit: "g",
        calories: 50,
        protein: 1,
        carbs: 12,
        fat: 0,
      },
    ],
    instructions: [
      {
        id: "skyr-oats-1",
        order: 1,
        text: "Add skyr to a bowl and loosen it with a spoon.",
      },
      {
        id: "skyr-oats-2",
        order: 2,
        text: "Top with oats and berries.",
      },
      {
        id: "skyr-oats-3",
        order: 3,
        text: "Let it sit briefly if a softer texture is preferred.",
      },
    ],
    totals: {
      calories: 435,
      protein: 40,
      carbs: 55,
      fat: 5,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
  {
    id: "protein-bowl",
    title: "Protein bowl with vegetables",
    description: "Balanced lunch or dinner bowl with chicken, rice and vegetables.",
    mealTypes: ["lunch", "dinner"],
    tags: ["high-protein", "meal-prep"],
    defaultServings: 1,
    prepMinutes: 24,
    cookMinutes: 18,
    imageUrl: "/images/recipes/protein-bowl.svg",
    imageAlt: "Abstract protein bowl with vegetables",
    ingredients: [
      {
        id: "chicken",
        name: "Chicken breast",
        amount: 160,
        unit: "g",
        calories: 260,
        protein: 48,
        carbs: 0,
        fat: 6,
      },
      {
        id: "rice",
        name: "Cooked rice",
        amount: 140,
        unit: "g",
        calories: 180,
        protein: 4,
        carbs: 39,
        fat: 1,
      },
      {
        id: "mixed-vegetables",
        name: "Mixed vegetables",
        amount: 200,
        unit: "g",
        calories: 90,
        protein: 4,
        carbs: 16,
        fat: 1,
      },
      {
        id: "olive-oil",
        name: "Olive oil",
        amount: 1,
        unit: "tbsp",
        calories: 119,
        protein: 0,
        carbs: 0,
        fat: 14,
      },
    ],
    instructions: [
      {
        id: "protein-bowl-1",
        order: 1,
        text: "Cook or reheat rice and mixed vegetables.",
      },
      {
        id: "protein-bowl-2",
        order: 2,
        text: "Cook chicken breast until done and slice it.",
      },
      {
        id: "protein-bowl-3",
        order: 3,
        text: "Assemble rice, vegetables, chicken and olive oil in a bowl.",
      },
    ],
    totals: {
      calories: 649,
      protein: 56,
      carbs: 55,
      fat: 22,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-19",
  },
  {
    id: "rice-vegetable-pan",
    title: "Rice vegetable pan",
    description: "Vegetarian pan meal with rice, tofu and vegetables.",
    mealTypes: ["lunch", "dinner"],
    tags: ["meal-prep", "vegetarian"],
    defaultServings: 1,
    prepMinutes: 20,
    cookMinutes: 16,
    imageUrl: "/images/recipes/rice-vegetable-pan.svg",
    imageAlt: "Abstract rice and vegetable pan",
    ingredients: [
      {
        id: "rice-pan-rice",
        name: "Cooked rice",
        amount: 180,
        unit: "g",
        calories: 230,
        protein: 5,
        carbs: 50,
        fat: 1,
      },
      {
        id: "rice-pan-vegetables",
        name: "Vegetables",
        amount: 250,
        unit: "g",
        calories: 120,
        protein: 6,
        carbs: 22,
        fat: 1,
      },
      {
        id: "tofu",
        name: "Tofu",
        amount: 120,
        unit: "g",
        calories: 170,
        protein: 18,
        carbs: 4,
        fat: 10,
      },
      {
        id: "soy-sauce",
        name: "Soy sauce",
        amount: 1,
        unit: "tbsp",
        calories: 10,
        protein: 1,
        carbs: 1,
        fat: 0,
      },
    ],
    instructions: [
      {
        id: "rice-vegetable-pan-1",
        order: 1,
        text: "Warm a pan and add tofu with vegetables.",
      },
      {
        id: "rice-vegetable-pan-2",
        order: 2,
        text: "Fold in cooked rice and heat everything through.",
      },
      {
        id: "rice-vegetable-pan-3",
        order: 3,
        text: "Finish with soy sauce and portion for the planner.",
      },
    ],
    totals: {
      calories: 530,
      protein: 30,
      carbs: 77,
      fat: 12,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
  {
    id: "salmon-potatoes",
    title: "Salmon with potatoes",
    description: "Planner-ready dinner with salmon, potatoes and a side salad.",
    mealTypes: ["dinner"],
    tags: ["high-protein", "meal-prep"],
    defaultServings: 1,
    prepMinutes: 28,
    cookMinutes: 22,
    imageUrl: "/images/recipes/salmon-potatoes.svg",
    imageAlt: "Abstract salmon with potatoes",
    ingredients: [
      {
        id: "salmon",
        name: "Salmon",
        amount: 150,
        unit: "g",
        calories: 310,
        protein: 34,
        carbs: 0,
        fat: 20,
      },
      {
        id: "potatoes",
        name: "Potatoes",
        amount: 250,
        unit: "g",
        calories: 210,
        protein: 5,
        carbs: 47,
        fat: 0,
      },
      {
        id: "salad",
        name: "Side salad",
        amount: 120,
        unit: "g",
        calories: 35,
        protein: 2,
        carbs: 6,
        fat: 0,
      },
      {
        id: "yogurt-dressing",
        name: "Yogurt dressing",
        amount: 60,
        unit: "g",
        calories: 45,
        protein: 4,
        carbs: 4,
        fat: 2,
      },
    ],
    instructions: [
      {
        id: "salmon-potatoes-1",
        order: 1,
        text: "Boil potatoes until tender.",
      },
      {
        id: "salmon-potatoes-2",
        order: 2,
        text: "Cook salmon in a pan or oven until just done.",
      },
      {
        id: "salmon-potatoes-3",
        order: 3,
        text: "Serve with side salad and yogurt dressing.",
      },
    ],
    totals: {
      calories: 600,
      protein: 45,
      carbs: 57,
      fat: 22,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-19",
  },
  {
    id: "tofu-bowl",
    title: "Tofu bowl",
    description: "Vegetarian tofu bowl with quinoa, vegetables and tahini.",
    mealTypes: ["lunch", "dinner"],
    tags: ["vegetarian", "meal-prep"],
    defaultServings: 1,
    prepMinutes: 22,
    cookMinutes: 18,
    imageUrl: "/images/recipes/tofu-bowl.svg",
    imageAlt: "Abstract tofu bowl",
    ingredients: [
      {
        id: "bowl-tofu",
        name: "Tofu",
        amount: 180,
        unit: "g",
        calories: 255,
        protein: 27,
        carbs: 6,
        fat: 15,
      },
      {
        id: "quinoa",
        name: "Quinoa",
        amount: 150,
        unit: "g",
        calories: 180,
        protein: 6,
        carbs: 32,
        fat: 3,
      },
      {
        id: "bowl-vegetables",
        name: "Vegetables",
        amount: 200,
        unit: "g",
        calories: 90,
        protein: 4,
        carbs: 16,
        fat: 1,
      },
      {
        id: "tahini",
        name: "Tahini",
        amount: 1,
        unit: "tbsp",
        calories: 89,
        protein: 3,
        carbs: 3,
        fat: 8,
      },
    ],
    instructions: [
      {
        id: "tofu-bowl-1",
        order: 1,
        text: "Cook or reheat quinoa.",
      },
      {
        id: "tofu-bowl-2",
        order: 2,
        text: "Sear tofu until the edges are firm.",
      },
      {
        id: "tofu-bowl-3",
        order: 3,
        text: "Add vegetables and tahini before serving.",
      },
    ],
    totals: {
      calories: 614,
      protein: 40,
      carbs: 57,
      fat: 27,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
  {
    id: "omelette",
    title: "Omelette with vegetables",
    description: "Low-carb breakfast with vegetables and feta.",
    mealTypes: ["breakfast"],
    tags: ["quick", "low-carb", "vegetarian"],
    defaultServings: 1,
    prepMinutes: 12,
    cookMinutes: 8,
    imageUrl: "/images/recipes/omelette.svg",
    imageAlt: "Abstract omelette with vegetables",
    ingredients: [
      {
        id: "eggs",
        name: "Eggs",
        amount: 3,
        unit: "piece",
        calories: 216,
        protein: 19,
        carbs: 1,
        fat: 15,
      },
      {
        id: "omelette-vegetables",
        name: "Vegetables",
        amount: 120,
        unit: "g",
        calories: 45,
        protein: 3,
        carbs: 8,
        fat: 0,
      },
      {
        id: "feta",
        name: "Feta",
        amount: 40,
        unit: "g",
        calories: 105,
        protein: 6,
        carbs: 1,
        fat: 8,
      },
      {
        id: "omelette-oil",
        name: "Olive oil",
        amount: 1,
        unit: "tsp",
        calories: 40,
        protein: 0,
        carbs: 0,
        fat: 4.5,
      },
    ],
    instructions: [
      {
        id: "omelette-1",
        order: 1,
        text: "Whisk eggs and prepare the vegetables.",
      },
      {
        id: "omelette-2",
        order: 2,
        text: "Cook vegetables briefly in olive oil.",
      },
      {
        id: "omelette-3",
        order: 3,
        text: "Add eggs and feta, then cook until set.",
      },
    ],
    totals: {
      calories: 406,
      protein: 28,
      carbs: 10,
      fat: 27.5,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
  {
    id: "chicken-wrap",
    title: "Chicken wrap",
    description: "Quick high-protein wrap with skyr sauce and salad.",
    mealTypes: ["lunch", "dinner"],
    tags: ["high-protein", "quick"],
    defaultServings: 1,
    prepMinutes: 14,
    cookMinutes: 8,
    imageUrl: "/images/recipes/chicken-wrap.svg",
    imageAlt: "Abstract chicken wrap",
    ingredients: [
      {
        id: "wrap",
        name: "Wholegrain wrap",
        amount: 1,
        unit: "piece",
        calories: 190,
        protein: 6,
        carbs: 32,
        fat: 5,
      },
      {
        id: "wrap-chicken",
        name: "Chicken breast",
        amount: 130,
        unit: "g",
        calories: 210,
        protein: 39,
        carbs: 0,
        fat: 5,
      },
      {
        id: "skyr-sauce",
        name: "Skyr sauce",
        amount: 70,
        unit: "g",
        calories: 45,
        protein: 8,
        carbs: 3,
        fat: 0,
      },
      {
        id: "wrap-salad",
        name: "Salad",
        amount: 120,
        unit: "g",
        calories: 35,
        protein: 2,
        carbs: 6,
        fat: 0,
      },
      {
        id: "avocado",
        name: "Avocado",
        amount: 50,
        unit: "g",
        calories: 80,
        protein: 1,
        carbs: 4,
        fat: 7,
      },
    ],
    instructions: [
      {
        id: "chicken-wrap-1",
        order: 1,
        text: "Warm the wrap and prepare the salad.",
      },
      {
        id: "chicken-wrap-2",
        order: 2,
        text: "Add chicken, skyr sauce, salad and avocado.",
      },
      {
        id: "chicken-wrap-3",
        order: 3,
        text: "Roll tightly and cut in half for serving.",
      },
    ],
    totals: {
      calories: 560,
      protein: 56,
      carbs: 45,
      fat: 17,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-19",
  },
  {
    id: "tomato-pasta",
    title: "Pasta with tomato sauce",
    description: "Simple vegetarian pasta that keeps the planner filled quickly.",
    mealTypes: ["lunch", "dinner"],
    tags: ["quick", "vegetarian"],
    defaultServings: 1,
    prepMinutes: 18,
    cookMinutes: 14,
    imageUrl: "/images/recipes/pasta-tomato.svg",
    imageAlt: "Abstract pasta with tomato sauce",
    ingredients: [
      {
        id: "pasta",
        name: "Pasta",
        amount: 90,
        unit: "g",
        calories: 330,
        protein: 12,
        carbs: 65,
        fat: 2,
      },
      {
        id: "tomato-sauce",
        name: "Tomato sauce",
        amount: 180,
        unit: "g",
        calories: 90,
        protein: 3,
        carbs: 14,
        fat: 2,
      },
      {
        id: "mozzarella",
        name: "Mozzarella",
        amount: 60,
        unit: "g",
        calories: 170,
        protein: 12,
        carbs: 2,
        fat: 12,
      },
      {
        id: "pasta-vegetables",
        name: "Vegetables",
        amount: 150,
        unit: "g",
        calories: 60,
        protein: 3,
        carbs: 12,
        fat: 0,
      },
    ],
    instructions: [
      {
        id: "tomato-pasta-1",
        order: 1,
        text: "Cook pasta in salted water.",
      },
      {
        id: "tomato-pasta-2",
        order: 2,
        text: "Warm tomato sauce with vegetables.",
      },
      {
        id: "tomato-pasta-3",
        order: 3,
        text: "Combine pasta, sauce and mozzarella.",
      },
    ],
    totals: {
      calories: 650,
      protein: 30,
      carbs: 93,
      fat: 16,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
  {
    id: "lentil-curry",
    title: "Lentil curry",
    description: "Meal-prep curry with lentils, rice, spinach and coconut milk.",
    mealTypes: ["lunch", "dinner"],
    tags: ["vegetarian", "meal-prep"],
    defaultServings: 1,
    prepMinutes: 26,
    cookMinutes: 22,
    imageUrl: "/images/recipes/lentil-curry.svg",
    imageAlt: "Abstract lentil curry",
    ingredients: [
      {
        id: "lentils",
        name: "Lentils",
        amount: 180,
        unit: "g",
        calories: 210,
        protein: 16,
        carbs: 36,
        fat: 1,
      },
      {
        id: "curry-rice",
        name: "Cooked rice",
        amount: 120,
        unit: "g",
        calories: 155,
        protein: 3,
        carbs: 34,
        fat: 0,
      },
      {
        id: "coconut-milk",
        name: "Coconut milk",
        amount: 80,
        unit: "ml",
        calories: 150,
        protein: 1,
        carbs: 3,
        fat: 15,
      },
      {
        id: "spinach",
        name: "Spinach",
        amount: 100,
        unit: "g",
        calories: 25,
        protein: 3,
        carbs: 4,
        fat: 0,
      },
    ],
    instructions: [
      {
        id: "lentil-curry-1",
        order: 1,
        text: "Warm lentils with coconut milk and spices.",
      },
      {
        id: "lentil-curry-2",
        order: 2,
        text: "Fold in spinach and simmer briefly.",
      },
      {
        id: "lentil-curry-3",
        order: 3,
        text: "Serve with cooked rice or portion for meal prep.",
      },
    ],
    totals: {
      calories: 540,
      protein: 23,
      carbs: 77,
      fat: 16,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-19",
  },
  {
    id: "cottage-cheese-plate",
    title: "Cottage cheese plate",
    description: "Fast high-protein plate for breakfast or light lunch.",
    mealTypes: ["breakfast", "lunch"],
    tags: ["high-protein", "quick", "vegetarian"],
    defaultServings: 1,
    prepMinutes: 9,
    cookMinutes: 0,
    imageUrl: "/images/recipes/cottage-cheese-plate.svg",
    imageAlt: "Abstract cottage cheese plate",
    ingredients: [
      {
        id: "cottage-cheese",
        name: "Cottage cheese",
        amount: 250,
        unit: "g",
        calories: 240,
        protein: 34,
        carbs: 10,
        fat: 8,
      },
      {
        id: "bread",
        name: "Wholegrain bread",
        amount: 80,
        unit: "g",
        calories: 190,
        protein: 7,
        carbs: 36,
        fat: 2,
      },
      {
        id: "tomato",
        name: "Tomato",
        amount: 150,
        unit: "g",
        calories: 30,
        protein: 2,
        carbs: 6,
        fat: 0,
      },
      {
        id: "boiled-egg",
        name: "Boiled egg",
        amount: 1,
        unit: "piece",
        calories: 72,
        protein: 6,
        carbs: 0,
        fat: 5,
      },
    ],
    instructions: [
      {
        id: "cottage-cheese-plate-1",
        order: 1,
        text: "Place cottage cheese on a plate or in a bowl.",
      },
      {
        id: "cottage-cheese-plate-2",
        order: 2,
        text: "Add bread, tomato and boiled egg.",
      },
      {
        id: "cottage-cheese-plate-3",
        order: 3,
        text: "Season lightly and serve cold.",
      },
    ],
    totals: {
      calories: 532,
      protein: 49,
      carbs: 52,
      fat: 15,
    },
    createdAt: "2026-06-15",
    updatedAt: "2026-06-18",
  },
];

function planned(
  date: string,
  mealType: MealType,
  recipeId: string,
  servings = 1,
): PlannedMeal {
  return {
    id: `${date}-${mealType}-${recipeId}`,
    recipeId,
    mealType,
    date,
    servings,
    ingredientAdjustments: [],
  };
}

function slot(
  date: string,
  mealType: MealType,
  recipeId?: string,
): MealPlanSlot {
  return {
    date,
    mealType,
    plannedMeal: recipeId ? planned(date, mealType, recipeId) : undefined,
  };
}

function day(date: string, label: string, recipeIds: Partial<Record<MealType, string>>) {
  return {
    date,
    label,
    slots: mealTypes.map((mealType) => slot(date, mealType, recipeIds[mealType])),
  };
}

export const mealPlanWeek: MealPlanWeek = {
  id: "meal-plan-week-2026-06-15",
  weekStartsOn: "2026-06-15",
  days: [
    day("2026-06-15", "Mon", {
      breakfast: "skyr-oats",
      lunch: "chicken-wrap",
      dinner: "salmon-potatoes",
    }),
    day("2026-06-16", "Tue", {
      breakfast: "omelette",
      lunch: "rice-vegetable-pan",
      dinner: "tofu-bowl",
    }),
    day("2026-06-17", "Wed", {
      breakfast: "cottage-cheese-plate",
      dinner: "tomato-pasta",
    }),
    day("2026-06-18", "Thu", {
      breakfast: "skyr-oats",
      lunch: "protein-bowl",
    }),
    day("2026-06-19", "Fri", {
      lunch: "lentil-curry",
      dinner: "chicken-wrap",
    }),
    day("2026-06-20", "Sat", {
      breakfast: "omelette",
    }),
    day("2026-06-21", "Sun", {
      breakfast: "skyr-oats",
      lunch: "protein-bowl",
    }),
  ],
};
