import type { Exercise, MuscleGroup, RunningPlan, RunningPlanItem, RunningSession, StrengthPlan, StrengthPlanItem, StrengthSession, StrengthSetLog } from "../../domain/training";
import type { TableRow } from "../database.types";

export const mapRunningPlan = (row: TableRow<"running_plans">): RunningPlan => ({ id: row.id, name: row.name, goal: row.goal, archivedAt: row.archived_at, createdAt: row.created_at, updatedAt: row.updated_at });
export const mapRunningPlanItem = (row: TableRow<"running_plan_items">): RunningPlanItem => ({ id: row.id, planId: row.plan_id, title: row.title, plannedDistanceKm: row.planned_distance_km, plannedDurationMinutes: row.planned_duration_minutes, sortOrder: row.sort_order, archivedAt: row.archived_at });
export const mapRunningSession = (row: TableRow<"running_sessions">): RunningSession => ({ id: row.id, planItemId: row.plan_item_id, sessionDate: row.session_date, startedAt: row.started_at, distanceKm: row.distance_km, durationMinutes: row.duration_minutes, averageHeartRate: row.average_heart_rate, notes: row.notes, status: row.status as RunningSession["status"], completedAt: row.completed_at, archivedAt: row.archived_at });
export const mapExercise = (row: TableRow<"exercises">, muscles: readonly MuscleGroup[] = []): Exercise => ({ id: row.id, name: row.name, description: row.description, equipment: row.equipment, archivedAt: row.archived_at, muscles });
export const mapStrengthPlan = (row: TableRow<"strength_plans">): StrengthPlan => ({ id: row.id, name: row.name, goal: row.goal, archivedAt: row.archived_at, createdAt: row.created_at, updatedAt: row.updated_at });
export const mapStrengthPlanItem = (row: TableRow<"strength_plan_items">): StrengthPlanItem => ({ id: row.id, planId: row.plan_id, exerciseId: row.exercise_id, sortOrder: row.sort_order, targetSets: row.target_sets, targetReps: row.target_reps, targetWeightKg: row.target_weight_kg });
export const mapStrengthSession = (row: TableRow<"strength_sessions">): StrengthSession => ({ id: row.id, planId: row.plan_id, sessionDate: row.session_date, startedAt: row.started_at, status: row.status as StrengthSession["status"], notes: row.notes, completedAt: row.completed_at, archivedAt: row.archived_at });
export const mapStrengthSetLog = (row: TableRow<"strength_set_logs">): StrengthSetLog => ({ id: row.id, sessionId: row.session_id, exerciseId: row.exercise_id, setOrder: row.set_order, repetitions: row.repetitions, weightKg: row.weight_kg, notes: row.notes, recordedAt: row.recorded_at });
