"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getCurrentLifeOsProfileId } from "@/features/profile-data/profile-cookie";
import { createAuthenticatedSupabaseServerClient } from "@/lib/supabase/server";
import { challengeIdSchema, challengeInputSchema, challengeProgressIdSchema, challengeProgressInputSchema, updateChallengeInputSchema, updateChallengeProgressInputSchema } from "../schemas/challenge.schemas";
import { createSupabaseChallengeRepository } from "../supabase/repositories/supabase-challenge-repository";
function value(data: FormData, key: string) { const item = data.get(key); return typeof item === "string" ? item.trim() : ""; }
function finish(state: string): never { revalidatePath("/challenges"); revalidatePath("/dashboard"); redirect(`/challenges?state=${encodeURIComponent(state)}`); }
async function context() { if (await getCurrentLifeOsProfileId() !== "manual") finish("auth_blocked"); const auth = await createAuthenticatedSupabaseServerClient(); if (!auth.ok) finish("auth_blocked"); return { repository: createSupabaseChallengeRepository(auth.client), userId: auth.user.id }; }
function challengeInput(data: FormData) { return { description: value(data, "description"), endDate: value(data, "endDate"), periodType: value(data, "periodType"), rewardCoins: value(data, "rewardCoins"), startDate: value(data, "startDate"), targetValue: value(data, "targetValue"), title: value(data, "title"), unit: value(data, "unit") }; }
function progressInput(data: FormData) { return { challengeId: value(data, "challengeId"), increment: value(data, "increment"), note: value(data, "note") }; }
export async function createChallengeAction(data: FormData) { const parsed = challengeInputSchema.safeParse(challengeInput(data)); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish((await repository.createChallenge(userId, parsed.data)).ok ? "created" : "error"); }
export async function updateChallengeAction(data: FormData) { const parsed = updateChallengeInputSchema.safeParse({ ...challengeInput(data), challengeId: value(data, "challengeId") }); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish((await repository.updateChallenge(userId, parsed.data)).ok ? "updated" : "error"); }
export async function addChallengeProgressAction(data: FormData) { const parsed = challengeProgressInputSchema.safeParse(progressInput(data)); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish((await repository.addProgress(userId, parsed.data)).ok ? "progress" : "error"); }
export async function updateChallengeProgressAction(data: FormData) { const parsed = updateChallengeProgressInputSchema.safeParse({ ...progressInput(data), progressLogId: value(data, "progressLogId") }); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish((await repository.updateLatestProgress(userId, parsed.data)).ok ? "progress_updated" : "error"); }
export async function archiveChallengeProgressAction(data: FormData) { const parsed = challengeProgressIdSchema.safeParse({ challengeId: value(data, "challengeId"), progressLogId: value(data, "progressLogId") }); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish(await repository.archiveLatestProgress(userId, parsed.data.challengeId, parsed.data.progressLogId) ? "progress_archived" : "error"); }
export async function completeChallengeAction(data: FormData) { const parsed = challengeIdSchema.safeParse({ challengeId: value(data, "challengeId") }); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish((await repository.complete(userId, parsed.data.challengeId)).ok ? "completed" : "not_ready"); }
export async function abandonChallengeAction(data: FormData) { const parsed = challengeIdSchema.safeParse({ challengeId: value(data, "challengeId") }); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish(await repository.setStatus(userId, parsed.data.challengeId, "abandoned") ? "abandoned" : "error"); }
export async function archiveChallengeAction(data: FormData) { const parsed = challengeIdSchema.safeParse({ challengeId: value(data, "challengeId") }); if (!parsed.success) finish("invalid"); const { repository, userId } = await context(); finish(await repository.archive(userId, parsed.data.challengeId) ? "archived" : "error"); }
