import type {
  EntertainmentItem,
  InventoryItem,
  JournalEntry,
  LifeActivity,
  LifeNote,
  LifeReviewDot,
  LifeSectionSummary,
  LifeTag,
} from "./types";

export const lifeTags: LifeTag[] = [
  { id: "tag-private", label: "private", tone: "purple" },
  { id: "tag-open-loops", label: "open loops", tone: "cyan" },
  { id: "tag-later", label: "later", tone: "gray" },
  { id: "tag-entertainment", label: "entertainment", tone: "blue" },
  { id: "tag-budget", label: "budget", tone: "orange" },
];

export const reflectionPrompts = [
  "Was hat heute unnoetig mentalen Druck erzeugt?",
  "Was hat geholfen, ruhiger zu werden?",
  "Welche offenen Loops kann ich loslassen?",
  "Was sollte morgen nicht wieder passieren?",
];

export const journalEntries: JournalEntry[] = [
  {
    id: "journal-week-reflection",
    title: "Wochenreflexion: mehr Ruhe nach Coding-Block",
    date: "2026-06-20T19:30:00.000Z",
    mood: "stable",
    energyLabel: "Mental voll, aber steuerbar",
    summary:
      "Der lange Coding-Block war produktiv, braucht aber einen klareren Abschluss, damit offene Loops nicht mit in den Abend gehen.",
    body:
      "Der Coding-Block war fachlich gut, aber das Ende war zu weich. Fuer den Abend brauche ich eine kurze Abschlussroutine: offene Punkte notieren, naechsten Schritt markieren und bewusst stehen lassen.",
    reflectionPrompt: "Was hat heute unnoetig mentalen Druck erzeugt?",
    tags: ["coding", "open loops", "review"],
    privacy: "sensitive",
    createdAt: "2026-06-20T19:30:00.000Z",
    updatedAt: "2026-06-20T19:38:00.000Z",
  },
  {
    id: "journal-evening-open-loops",
    title: "Abendnotiz: zu viele offene Loops",
    date: "2026-06-19T21:10:00.000Z",
    mood: "tired",
    energyLabel: "Niedrige Energie",
    summary:
      "Mehrere kleine Entscheidungen lagen nebeneinander. Besser morgen drei davon bewusst parken statt alles gleichzeitig verfolgen.",
    body:
      "Heute waren nicht die Aufgaben selbst das Problem, sondern die vielen halb offenen Mini-Entscheidungen. Ich will morgen zuerst klaeren, was warten darf, bevor ich neue Themen anfasse.",
    reflectionPrompt:
      "Welche offenen Punkte koennen bewusst bis zum naechsten Review warten?",
    tags: ["open loops", "evening"],
    privacy: "sensitive",
    createdAt: "2026-06-19T21:10:00.000Z",
    updatedAt: "2026-06-19T21:18:00.000Z",
  },
  {
    id: "journal-stable-full",
    title: "Check-in: stabil, aber mental voll",
    date: "2026-06-18T08:20:00.000Z",
    mood: "calm",
    energyLabel: "Ruhiger Start",
    summary:
      "Stabiler Zustand, aber die Woche ist dicht. Heute hilft eine enge Auswahl statt mehr Kontext.",
    body:
      "Der Start ist ruhig genug. Ich sollte heute nicht versuchen, alle Bereiche gleichzeitig zu ordnen. Ein klarer Hauptfokus und zwei kleine private Entscheidungen reichen.",
    reflectionPrompt:
      "Welche private Entscheidung braucht nur einen naechsten kleinen Schritt?",
    tags: ["check-in", "focus"],
    privacy: "private",
    createdAt: "2026-06-18T08:20:00.000Z",
    updatedAt: "2026-06-18T08:24:00.000Z",
  },
  {
    id: "journal-training-evening",
    title: "Gedanke nach Training: weniger Druck am Abend",
    date: "2026-06-17T20:05:00.000Z",
    mood: "stable",
    energyLabel: "Koerperlich muede, mental klarer",
    summary:
      "Nach Training ist weniger Druck sinnvoll. Abend nicht mit schweren Entscheidungen fuellen.",
    body:
      "Training hat geholfen, den Tag zu trennen. Danach sollte der Abend bewusst einfach bleiben: essen, kurze Notiz, keine groesseren Planungsentscheidungen.",
    reflectionPrompt: "Was hat geholfen, ruhiger zu werden?",
    tags: ["training", "evening"],
    privacy: "private",
    createdAt: "2026-06-17T20:05:00.000Z",
    updatedAt: "2026-06-17T20:11:00.000Z",
  },
];

export const lifeNotes: LifeNote[] = [
  {
    id: "note-knowledge-idea",
    title: "Gedanke zu neuer Knowledge-Idee",
    type: "idea",
    createdAt: "2026-06-20T16:50:00.000Z",
    updatedAt: "2026-06-20T16:50:00.000Z",
    snippet:
      "Ein Knowledge-Eintrag koennte spaeter aus mehreren Quellen entstehen, aber dieser Gedanke bleibt erstmal lose.",
    body:
      "Vielleicht sollte Knowledge spaeter aus mehreren kleinen Notizen entstehen. Diese Notiz ist aber noch kein Resource-Objekt und soll nicht automatisch eins werden.",
    tags: ["knowledge", "later"],
    source: "quick_capture",
    intentionallyUnstructured: true,
    privacy: "private",
  },
  {
    id: "note-entertainment-collection",
    title: "Warum Entertainment eher Sammlung als To-do sein sollte",
    type: "reflection",
    createdAt: "2026-06-19T18:15:00.000Z",
    updatedAt: "2026-06-19T18:19:00.000Z",
    snippet:
      "Medien sollen Erholung und Erinnerung stuetzen, nicht noch eine Produktivitaetsliste werden.",
    body:
      "Entertainment braucht einen ruhigen Shelf-Charakter. Es geht um Merken, Wiederfinden und bewusste Erholung, nicht um Abschlussdruck.",
    tags: ["entertainment", "principle"],
    source: "manual",
    intentionallyUnstructured: true,
    privacy: "private",
  },
  {
    id: "note-podcast-quote",
    title: "Zitat aus Podcast merken",
    type: "quote",
    createdAt: "2026-06-18T12:05:00.000Z",
    updatedAt: "2026-06-18T12:05:00.000Z",
    snippet:
      "Kurzer Satz ueber ruhige Systeme und klare Grenzen. Spaeter pruefen, ob er in Resources gehoert.",
    body:
      "Ein Satz aus einem Podcast ueber ruhige Systeme und klare Grenzen. Erst behalten, spaeter entscheiden, ob daraus eine Resource wird.",
    tags: ["quote", "systems"],
    source: "import",
    intentionallyUnstructured: true,
    privacy: "private",
  },
  {
    id: "note-personal-not-task",
    title: "Persoenlicher Gedanke, nicht als Task geeignet",
    type: "thought",
    createdAt: "2026-06-17T22:35:00.000Z",
    updatedAt: "2026-06-17T22:35:00.000Z",
    snippet:
      "Ein privater Gedanke, der behalten werden soll, ohne eine Aufgabe oder einen Knowledge-Eintrag daraus zu machen.",
    body:
      "Dieser Gedanke ist eher ein Marker fuer spaeter. Kein Next Step, keine Resource, kein Projekt.",
    tags: ["private", "loose"],
    source: "journal",
    intentionallyUnstructured: true,
    privacy: "sensitive",
  },
  {
    id: "note-inventory-budget-view",
    title: "Idee fuer Inventory-Budget-Ansicht",
    type: "idea",
    createdAt: "2026-06-16T14:40:00.000Z",
    updatedAt: "2026-06-16T14:40:00.000Z",
    snippet:
      "Inventory sollte keine Shopping-App werden, sondern Bedarf, Ersatz und Budget-Fit ruhig nebeneinander zeigen.",
    body:
      "Budget-Fit als Planungssignal reicht. Keine Preis-API, kein Deal-Fokus, keine harte Empfehlung. Wichtig ist: brauche ich es, passt es gerade, oder wartet es?",
    tags: ["inventory", "budget"],
    source: "manual",
    intentionallyUnstructured: true,
    privacy: "private",
  },
];

export const entertainmentItems: EntertainmentItem[] = [
  {
    id: "media-severance",
    title: "Severance",
    type: "series",
    status: "watching",
    priority: "high",
    note: "Ruhig weiterschauen, kein Binge-Zwang.",
    nextAction: "Naechste Episode vormerken",
    addedAt: "2026-06-20T20:00:00.000Z",
    updatedAt: "2026-06-20T20:00:00.000Z",
    ratingPersonal: "liked",
  },
  {
    id: "media-dune-part-two",
    title: "Dune: Part Two",
    type: "movie",
    status: "wishlist",
    priority: "medium",
    note: "Fuer einen ruhigen Filmabend offen halten.",
    nextAction: "Streaming-Verfuegbarkeit manuell pruefen",
    addedAt: "2026-06-18T17:20:00.000Z",
    updatedAt: "2026-06-18T17:20:00.000Z",
    ratingPersonal: "not_rated",
  },
  {
    id: "media-atomic-habits",
    title: "Atomic Habits",
    type: "book",
    status: "reading",
    priority: "low",
    note: "Nur einzelne Kapitel, keine neue Produktivitaetsbaustelle.",
    nextAction: "Kapitel zu Umgebung lesen",
    addedAt: "2026-06-16T10:30:00.000Z",
    updatedAt: "2026-06-16T10:30:00.000Z",
    ratingPersonal: "neutral",
  },
  {
    id: "media-cyberpunk-2077",
    title: "Cyberpunk 2077",
    type: "game",
    status: "paused",
    priority: "medium",
    note: "Spaeter als bewusstes Erholungsfenster fortsetzen.",
    nextAction: "Spielstand notieren",
    addedAt: "2026-06-15T19:45:00.000Z",
    updatedAt: "2026-06-15T19:45:00.000Z",
    ratingPersonal: "liked",
  },
  {
    id: "media-design-systems-talk",
    title: "YouTube: Design Systems Talk",
    type: "video",
    status: "wishlist",
    priority: "medium",
    note: "Als ruhige Inspiration, nicht als sofortige Umsetzung.",
    nextAction: "In Watchlist lassen",
    addedAt: "2026-06-14T14:00:00.000Z",
    updatedAt: "2026-06-14T14:00:00.000Z",
    ratingPersonal: "not_rated",
  },
  {
    id: "media-lenny-product-systems",
    title: "Podcast: Lenny's Podcast - Product Systems",
    type: "podcast",
    status: "finished",
    priority: "low",
    note: "Einzelne Systemgedanken spaeter in Resources pruefen.",
    nextAction: "Zitat in Notes behalten",
    addedAt: "2026-06-12T09:10:00.000Z",
    updatedAt: "2026-06-13T11:20:00.000Z",
    ratingPersonal: "liked",
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "inventory-macbook-upgrade",
    title: "MacBook Pro Upgrade",
    category: "tech",
    status: "planned_purchase",
    owned: false,
    targetPrice: 2400,
    priority: "high",
    budgetFit: "wait",
    note: "Erst Bedarf und Timing klaeren, nicht spontan entscheiden.",
    addedAt: "2026-06-20T15:00:00.000Z",
    updatedAt: "2026-06-20T15:00:00.000Z",
  },
  {
    id: "inventory-headphones",
    title: "Noise-Cancelling Headphones",
    category: "tech",
    status: "wishlist",
    owned: false,
    targetPrice: 240,
    priority: "medium",
    budgetFit: "fits",
    note: "Sinnvoll, wenn Konzentrationsfenster dadurch stabiler werden.",
    addedAt: "2026-06-19T13:10:00.000Z",
    updatedAt: "2026-06-19T13:10:00.000Z",
  },
  {
    id: "inventory-desk-lamp",
    title: "Schreibtischlampe",
    category: "desk",
    status: "needs_replacement",
    owned: true,
    estimatedValue: 35,
    targetPrice: 85,
    priority: "medium",
    budgetFit: "fits",
    note: "Aktuelle Lampe ist funktional, aber abends nicht ideal.",
    addedAt: "2026-06-18T20:20:00.000Z",
    updatedAt: "2026-06-18T20:20:00.000Z",
  },
  {
    id: "inventory-running-shoes",
    title: "Laufschuhe Ersatz",
    category: "fitness",
    status: "planned_purchase",
    owned: false,
    targetPrice: 130,
    priority: "high",
    budgetFit: "wait",
    note: "Erst aktuelles Paar pruefen, dann Ersatz terminieren.",
    addedAt: "2026-06-17T18:30:00.000Z",
    updatedAt: "2026-06-17T18:30:00.000Z",
  },
  {
    id: "inventory-software-subscription",
    title: "Software-Abo pruefen",
    category: "software",
    status: "wishlist",
    owned: false,
    targetPrice: 120,
    priority: "low",
    budgetFit: "unknown",
    note: "Vor Verlaengerung Nutzen und Alternativen festhalten.",
    addedAt: "2026-06-16T09:00:00.000Z",
    updatedAt: "2026-06-16T09:00:00.000Z",
  },
  {
    id: "inventory-monitor-arm",
    title: "Monitor Arm",
    category: "desk",
    status: "wishlist",
    owned: false,
    targetPrice: 95,
    priority: "medium",
    budgetFit: "wait",
    note: "Erst pruefen, ob aktueller Desk-Aufbau wirklich limitiert.",
    addedAt: "2026-06-15T10:45:00.000Z",
    updatedAt: "2026-06-15T10:45:00.000Z",
  },
  {
    id: "inventory-usb-c-dock",
    title: "USB-C Dock",
    category: "tech",
    status: "owned",
    owned: true,
    estimatedValue: 80,
    priority: "low",
    budgetFit: "fits",
    note: "Vorhanden und ausreichend. Nicht neu kaufen.",
    addedAt: "2026-06-14T12:00:00.000Z",
    updatedAt: "2026-06-14T12:00:00.000Z",
  },
];

export const lifeSections: LifeSectionSummary[] = [
  {
    id: "journal",
    title: "Journal",
    purpose: "Private dated reflections and open review prompts.",
    href: "/life/journal",
    lastActivity: "Yesterday / Abendnotiz / 8 min",
    openItems: "2 review prompts open",
    nextAction: "Start reflection",
    accent: "purple",
  },
  {
    id: "notes",
    title: "Notes",
    purpose: "Loose personal thoughts kept outside Tasks and Resources.",
    href: "/life/notes",
    lastActivity: "Today / quick capture",
    openItems: "5 loose notes kept",
    nextAction: "Capture note",
    accent: "cyan",
  },
  {
    id: "entertainment",
    title: "Entertainment",
    purpose: "Media shelf for watching, reading, playing and later ideas.",
    href: "/life/entertainment",
    lastActivity: "Severance marked watching",
    openItems: "2 wishlist items",
    nextAction: "Pick next medium",
    accent: "blue",
  },
  {
    id: "inventory",
    title: "Inventory",
    purpose: "Possessions, replacement needs, wishlist and budget decisions.",
    href: "/life/inventory",
    lastActivity: "MacBook upgrade reviewed",
    openItems: "5 decisions open",
    nextAction: "Review budget fit",
    accent: "orange",
  },
];

export const recentLifeActivity: LifeActivity[] = [
  {
    id: "activity-journal",
    label: "Journal entry created",
    detail: "Wochenreflexion saved locally",
    time: "Yesterday",
    tone: "purple",
  },
  {
    id: "activity-note",
    label: "Note captured",
    detail: "Knowledge idea kept intentionally loose",
    time: "Today",
    tone: "cyan",
  },
  {
    id: "activity-media",
    label: "Media added",
    detail: "Design Systems Talk added to wishlist",
    time: "This week",
    tone: "purple",
  },
  {
    id: "activity-wishlist",
    label: "Wishlist item reviewed",
    detail: "MacBook Pro Upgrade marked wait",
    time: "This week",
    tone: "orange",
  },
];

export const lifeReviewDots: LifeReviewDot[] = [
  { id: "dot-mon", label: "Mon", mood: "calm", detail: "Calm" },
  { id: "dot-tue", label: "Tue", mood: "stable", detail: "Stable" },
  { id: "dot-wed", label: "Wed", mood: "unclear", detail: "Unclear" },
  { id: "dot-thu", label: "Thu", mood: "calm", detail: "Calm" },
  { id: "dot-fri", label: "Fri", mood: "tired", detail: "Tired" },
  { id: "dot-sat", label: "Sat", mood: "stable", detail: "Stable" },
  { id: "dot-sun", label: "Sun", mood: "stable", detail: "Stable" },
];

export const privacyNotes = [
  "Personal data is private by default.",
  "Journal entries are not shared.",
  "Notes stay loose unless manually moved later.",
  "Inventory/Wishlist is personal planning data.",
  "No social sharing in MVP.",
];
