import type {
  CalendarAllDayBlockViewModel,
  CalendarDayViewModel,
  CalendarFilterViewModel,
  CalendarProjectRailItemViewModel,
  CalendarReviewMetricViewModel,
  SchedulableTaskViewModel,
  CalendarTimedBlockViewModel,
  CalendarWeekStatViewModel,
} from "./calendar-types";

export const CALENDAR_DAY_START_MINUTES = 6 * 60;
export const CALENDAR_DAY_END_MINUTES = 22 * 60 + 30;

export const calendarDays = [
  {
    id: "mon-09",
    date: "2026-06-09",
    weekday: "Mon",
    dayNumber: "09",
    fullLabel: "Monday 09 June",
  },
  {
    id: "tue-10",
    date: "2026-06-10",
    weekday: "Tue",
    dayNumber: "10",
    fullLabel: "Tuesday 10 June",
  },
  {
    id: "wed-11",
    date: "2026-06-11",
    weekday: "Wed",
    dayNumber: "11",
    fullLabel: "Wednesday 11 June",
  },
  {
    id: "thu-12",
    date: "2026-06-12",
    weekday: "Thu",
    dayNumber: "12",
    fullLabel: "Thursday 12 June",
    isToday: true,
  },
  {
    id: "fri-13",
    date: "2026-06-13",
    weekday: "Fri",
    dayNumber: "13",
    fullLabel: "Friday 13 June",
  },
  {
    id: "sat-14",
    date: "2026-06-14",
    weekday: "Sat",
    dayNumber: "14",
    fullLabel: "Saturday 14 June",
  },
  {
    id: "sun-15",
    date: "2026-06-15",
    weekday: "Sun",
    dayNumber: "15",
    fullLabel: "Sunday 15 June",
  },
] satisfies CalendarDayViewModel[];

export const calendarHours = [
  "06:00",
  "08:00",
  "10:00",
  "12:00",
  "14:00",
  "16:00",
  "18:00",
  "20:00",
  "22:00",
];

export const calendarFilters = [
  { label: "All", active: true },
  { label: "Events" },
  { label: "Tasks" },
  { label: "Focus" },
  { label: "Routines" },
  { label: "Projects" },
  { label: "Meals" },
  { label: "Health" },
  { label: "Reviews" },
  { label: "Deadlines" },
] satisfies CalendarFilterViewModel[];

export const calendarViewSwitches = [
  { label: "Day" },
  { label: "Week", active: true },
  { label: "Month" },
  { label: "Year" },
] satisfies CalendarFilterViewModel[];

export const projectsThisWeek = [
  {
    label: "Masterarbeit",
    count: 6,
    accent: "var(--accent-blue)",
  },
  {
    label: "Life OS",
    count: 9,
    accent: "var(--accent-cyan)",
  },
  {
    label: "Java",
    count: 4,
    accent: "var(--accent-purple)",
  },
  {
    label: "FI",
    count: 3,
    accent: "var(--accent-green)",
  },
] satisfies CalendarProjectRailItemViewModel[];

export const weekStats = [
  {
    label: "Tasks",
    value: "34",
    detail: "this week",
    accent: "var(--accent-blue)",
  },
  {
    label: "Projects",
    value: "4",
    detail: "touched",
    accent: "var(--accent-cyan)",
  },
  {
    label: "Focus",
    value: "7",
    detail: "blocks",
    accent: "var(--accent-purple)",
  },
  {
    label: "Deadlines",
    value: "3",
    detail: "visible",
    accent: "var(--accent-red)",
  },
  {
    label: "Reviews",
    value: "2",
    detail: "open",
    accent: "var(--accent-orange)",
  },
] satisfies CalendarWeekStatViewModel[];

export const allDayBlocks = [
  {
    id: "literature-source-deadline",
    dayId: "wed-11",
    title: "Literature source deadline",
    type: "deadline",
    status: "needs_decision",
    source: "task",
    area: "Education",
    sourceEntity: {
      type: "task",
      label: "Task / Masterarbeit",
      href: "/tasks",
    },
    accent: "var(--accent-red)",
    timeLabel: "Due 17:00",
    linkedEntity: "Literature source shortlist",
    plannedOutcome: "Confirm the last source group before thesis review.",
  },
  {
    id: "life-os-routing-reminder",
    dayId: "thu-12",
    title: "Reminder: Check route handoff",
    type: "reminder",
    status: "draft",
    source: "manual",
    area: "Coding",
    sourceEntity: {
      type: "project",
      label: "Project / Life OS App",
      href: "/projects",
    },
    accent: "var(--accent-orange)",
    timeLabel: "Soft nudge",
    linkedEntity: "Life OS App routing",
    plannedOutcome: "Decide whether the route note belongs in Calendar or Today.",
  },
  {
    id: "weekly-review-prep",
    dayId: "sat-14",
    title: "Review: Weekly Review",
    type: "review",
    status: "planned",
    source: "review",
    area: "Review / System",
    sourceEntity: {
      type: "review",
      label: "Review / Weekly",
      href: "/review/daily",
    },
    accent: "var(--accent-cyan)",
    timeLabel: "All day prep",
    linkedEntity: "Weekly review draft",
    plannedOutcome: "Collect open loops before the timed weekly review block.",
  },
] satisfies CalendarAllDayBlockViewModel[];

export const timedBlocks = [
  {
    id: "routine-morning-briefing",
    dayId: "mon-09",
    title: "Routine: Morning Briefing",
    type: "routine",
    status: "done",
    source: "routine",
    area: "Personal",
    sourceEntity: {
      type: "review",
      label: "Routine / Daily startup",
      href: "/today",
    },
    accent: "var(--accent-purple)",
    meta: "Daily context check",
    linkedEntity: "Morning briefing ritual",
    plannedOutcome: "Open the day before pulling in more tasks.",
    startTime: "07:30",
    endTime: "07:50",
    startMinutes: 7 * 60 + 30,
    endMinutes: 7 * 60 + 50,
  },
  {
    id: "deep-work-masterarbeit",
    dayId: "mon-09",
    title: "Deep Work: Masterarbeit",
    type: "focus_block",
    status: "planned",
    source: "project",
    area: "Education",
    sourceEntity: {
      type: "project",
      label: "Project / Masterarbeit",
      href: "/projects",
    },
    accent: "var(--accent-blue)",
    meta: "Literature and thesis structure",
    linkedEntity: "Masterarbeit project",
    plannedOutcome: "Produce the next literature structure pass.",
    startTime: "08:00",
    endTime: "10:00",
    startMinutes: 8 * 60,
    endMinutes: 10 * 60,
  },
  {
    id: "team-standup",
    dayId: "tue-10",
    title: "Team Standup",
    type: "event",
    status: "done",
    source: "manual",
    area: "Work",
    sourceEntity: {
      type: "meeting",
      label: "Work",
      href: "/work/meetings",
    },
    accent: "var(--accent-green)",
    meta: "Remote sync",
    linkedEntity: "Work meeting",
    plannedOutcome: "Align on current blockers.",
    startTime: "10:15",
    endTime: "10:35",
    startMinutes: 10 * 60 + 15,
    endMinutes: 10 * 60 + 35,
  },
  {
    id: "batch-admin-cleanup",
    dayId: "tue-10",
    title: "Batch Block: Admin Cleanup",
    type: "batch_block",
    status: "planned",
    source: "inbox",
    area: "Work",
    sourceEntity: {
      type: "task",
      label: "Inbox / admin tasks",
      href: "/inbox",
    },
    accent: "var(--accent-green)",
    meta: "Email, follow-ups, small tasks",
    linkedEntity: "Admin cleanup batch",
    plannedOutcome: "Close small open loops without fragmenting the afternoon.",
    startTime: "14:00",
    endTime: "15:00",
    startMinutes: 14 * 60,
    endMinutes: 15 * 60,
  },
  {
    id: "task-block-literature-structure",
    dayId: "wed-11",
    title: "Task Block: Literaturstruktur uberarbeiten",
    type: "task_block",
    status: "planned",
    source: "task",
    area: "Education",
    sourceEntity: {
      type: "task",
      label: "Task / Masterarbeit",
      href: "/tasks",
    },
    accent: "var(--accent-blue)",
    meta: "Linked task",
    linkedEntity: "Literature structure task",
    plannedOutcome: "Turn notes into a revised outline.",
    startTime: "09:30",
    endTime: "10:45",
    startMinutes: 9 * 60 + 30,
    endMinutes: 10 * 60 + 45,
  },
  {
    id: "lunch-walk",
    dayId: "thu-12",
    title: "Workout / Walk Recovery",
    type: "workout",
    status: "planned",
    source: "health",
    area: "Health",
    sourceEntity: {
      type: "workout",
      label: "Workout / Recovery",
      href: "/health/running",
    },
    accent: "var(--accent-red)",
    meta: "Recovery window",
    linkedEntity: "Recovery walk",
    plannedOutcome: "Protect recovery without turning Calendar into analytics.",
    startTime: "12:00",
    endTime: "13:00",
    startMinutes: 12 * 60,
    endMinutes: 13 * 60,
  },
  {
    id: "skill-practice-figma",
    dayId: "thu-12",
    title: "Focus Block: Life OS Calendar V2",
    type: "focus_block",
    status: "active",
    source: "project",
    area: "Coding",
    sourceEntity: {
      type: "project",
      label: "Project / Life OS App",
      href: "/projects",
    },
    accent: "var(--accent-cyan)",
    meta: "Planning surface pass",
    linkedEntity: "Life OS App project",
    plannedOutcome: "Make Calendar creation visible without DB persistence.",
    startTime: "15:30",
    endTime: "16:30",
    startMinutes: 15 * 60 + 30,
    endMinutes: 16 * 60 + 30,
  },
  {
    id: "dinner-protein-bowl",
    dayId: "thu-12",
    title: "Dinner: Protein Bowl",
    type: "meal",
    status: "planned",
    source: "meal_planner",
    area: "Nutrition",
    sourceEntity: {
      type: "meal",
      label: "Meal / Nutrition",
      href: "/nutrition/meal-planner",
    },
    accent: "var(--accent-yellow)",
    meta: "Protein target",
    linkedEntity: "Protein Bowl meal plan",
    plannedOutcome: "Keep dinner planned without duplicating the meal record.",
    startTime: "19:00",
    endTime: "19:30",
    startMinutes: 19 * 60,
    endMinutes: 19 * 60 + 30,
  },
  {
    id: "journal-plan-tomorrow",
    dayId: "thu-12",
    title: "Routine: Evening Review",
    type: "routine",
    status: "planned",
    source: "routine",
    area: "Review / System",
    sourceEntity: {
      type: "review",
      label: "Review / Daily",
      href: "/review/daily",
    },
    accent: "var(--accent-cyan)",
    meta: "Open loops",
    linkedEntity: "Evening review ritual",
    plannedOutcome: "Close the day and prepare tomorrow's first move.",
    startTime: "21:15",
    endTime: "21:45",
    startMinutes: 21 * 60 + 15,
    endMinutes: 21 * 60 + 45,
  },
  {
    id: "daily-review",
    dayId: "thu-12",
    title: "Daily Review",
    type: "review",
    status: "draft",
    source: "review",
    area: "Review / System",
    sourceEntity: {
      type: "review",
      label: "Review / Daily",
      href: "/review/daily",
    },
    accent: "var(--accent-cyan)",
    meta: "Close day",
    linkedEntity: "Daily review record",
    plannedOutcome: "Separate planned work from actual day evidence.",
    startTime: "21:45",
    endTime: "22:05",
    startMinutes: 21 * 60 + 45,
    endMinutes: 22 * 60 + 5,
  },
  {
    id: "workout-run",
    dayId: "fri-13",
    title: "Workout / Run",
    type: "workout",
    status: "planned",
    source: "health",
    area: "Health",
    sourceEntity: {
      type: "workout",
      label: "Workout",
      href: "/health/running",
    },
    accent: "var(--accent-red)",
    meta: "Base run",
    linkedEntity: "Running plan",
    plannedOutcome: "Complete the planned base run.",
    startTime: "17:30",
    endTime: "18:30",
    startMinutes: 17 * 60 + 30,
    endMinutes: 18 * 60 + 30,
  },
  {
    id: "hyperskill-lesson",
    dayId: "sat-14",
    title: "Task Block: Hyperskill lesson",
    type: "task_block",
    status: "planned",
    source: "task",
    area: "Education",
    sourceEntity: {
      type: "task",
      label: "Task / Education",
      href: "/tasks",
    },
    accent: "var(--accent-blue)",
    meta: "Java path",
    linkedEntity: "Hyperskill Java task",
    plannedOutcome: "Finish one bounded lesson block.",
    startTime: "09:30",
    endTime: "10:30",
    startMinutes: 9 * 60 + 30,
    endMinutes: 10 * 60 + 30,
  },
  {
    id: "weekly-review-block",
    dayId: "sat-14",
    title: "Review: Weekly Review",
    type: "review",
    status: "planned",
    source: "review",
    area: "Review / System",
    sourceEntity: {
      type: "review",
      label: "Review / Weekly",
      href: "/review/daily",
    },
    accent: "var(--accent-cyan)",
    meta: "Weekly closeout",
    linkedEntity: "Weekly review draft",
    plannedOutcome: "Decide what carries into next week.",
    startTime: "11:00",
    endTime: "11:45",
    startMinutes: 11 * 60,
    endMinutes: 11 * 60 + 45,
  },
  {
    id: "reminder-plant-source-list",
    dayId: "sun-15",
    title: "Reminder: Send source list",
    type: "reminder",
    status: "draft",
    source: "manual",
    area: "Education",
    sourceEntity: {
      type: "free_event",
      label: "Manual reminder",
    },
    accent: "var(--accent-orange)",
    meta: "Soft nudge",
    linkedEntity: "Literature source list",
    plannedOutcome: "Nudge without creating an automatic task.",
    startTime: "15:00",
    endTime: "15:30",
    startMinutes: 15 * 60,
    endMinutes: 15 * 60 + 30,
  },
] satisfies Omit<
  CalendarTimedBlockViewModel,
  "compact" | "density" | "durationMinutes" | "layout"
>[];

export const reviewMetrics = [
  {
    label: "Daily Review",
    value: "open",
    detail: "ready tonight",
    accent: "var(--accent-cyan)",
  },
  {
    label: "Weekly Review",
    value: "draft open",
    detail: "write below",
    accent: "var(--text-muted)",
  },
  {
    label: "Open loops",
    value: "5",
    detail: "needs closure",
    accent: "var(--accent-red)",
  },
  {
    label: "Recent wins",
    value: "3",
    detail: "captured today",
    accent: "var(--accent-green)",
  },
  {
    label: "Carry forward",
    value: "2",
    detail: "tomorrow candidates",
    accent: "var(--accent-orange)",
  },
] satisfies CalendarReviewMetricViewModel[];

export const schedulableTasks = [
  {
    accent: "var(--accent-blue)",
    area: "Education",
    createdAt: "2026-06-10",
    dueDate: "2026-06-11",
    durationMinutes: 75,
    id: "task-literature-structure",
    isRecurringOccurrence: false,
    plannedDate: "2026-06-11",
    project: { id: "project-thesis", title: "Masterarbeit" },
    rankingGroup: "due_this_week",
    rankingReason: "Due this week",
    skills: [],
    title: "Literaturstruktur uberarbeiten",
    priority: "P1",
  },
  {
    accent: "var(--accent-cyan)",
    area: "QA",
    createdAt: "2026-06-12",
    dueDate: "2026-06-12",
    durationMinutes: 25,
    id: "task-run-quality-checks",
    isRecurringOccurrence: false,
    plannedDate: "2026-06-12",
    project: { id: "project-life-os", title: "Life OS App" },
    rankingGroup: "due_this_week",
    rankingReason: "Due this week",
    skills: [],
    title: "Run lint and TypeScript checks",
    priority: "P1",
  },
  {
    accent: "var(--accent-purple)",
    area: "Review / System",
    createdAt: "2026-06-11",
    dueDate: "2026-06-14",
    durationMinutes: 30,
    id: "task-review-route-copy",
    isRecurringOccurrence: false,
    plannedDate: "2026-06-14",
    project: { id: "project-daily-flow", title: "Daily Flow" },
    rankingGroup: "due_this_week",
    rankingReason: "Due this week",
    skills: [],
    title: "Prepare static review route copy",
    priority: "P2",
  },
  {
    accent: "var(--accent-green)",
    area: "System",
    createdAt: "2026-06-09",
    dueDate: "2026-06-16",
    durationMinutes: 15,
    id: "task-data-model-timing",
    isRecurringOccurrence: false,
    plannedDate: "2026-06-16",
    project: { id: "project-data-planning", title: "Data Planning" },
    rankingGroup: "project_next_work",
    rankingReason: "Project next work",
    skills: [],
    title: "Confirm data model timing",
    priority: "P3",
  },
  {
    accent: "var(--accent-orange)",
    area: "Roadmap",
    createdAt: "2026-06-10",
    dueDate: "2026-06-18",
    durationMinutes: 45,
    id: "task-agent-context-cleanup",
    isRecurringOccurrence: false,
    plannedDate: "2026-06-18",
    project: { id: "project-data-binding", title: "Data Binding Prep" },
    rankingGroup: "project_next_work",
    rankingReason: "Project next work",
    skills: [],
    title: "Document follow-up data binding tasks",
    priority: "P2",
  },
] satisfies SchedulableTaskViewModel[];
