import type { Challenge, ChallengeTemplate } from "./types";

export const challenges: Challenge[] = [
  {
    id: "challenge-walk",
    title: "10-minute walk",
    cadence: "daily",
    status: "completed",
    difficulty: "easy",
    description: "A short walk to break desk inertia and get daylight.",
    rewardAmount: 4,
    progressCurrent: 1,
    progressTarget: 1,
    progressLabel: "1 / 1 · completed",
    linkedArea: "health",
    dueLabel: "Today",
    completedAt: "2026-06-21",
    nextAction: "Keep the walk short and return to the next planned block",
    createdByUser: false,
  },
  {
    id: "challenge-inbox-zero",
    title: "Inbox zero attempt",
    cadence: "daily",
    status: "active",
    difficulty: "medium",
    description: "Process the visible inbox without trying to solve every item.",
    rewardAmount: 6,
    progressCurrent: 2,
    progressTarget: 4,
    progressLabel: "2 / 4 · in progress",
    linkedArea: "review",
    dueLabel: "Evening",
    nextAction: "Clarify two raw items and archive what is no longer useful",
    createdByUser: false,
  },
  {
    id: "challenge-no-phone-focus",
    title: "No phone during first focus block",
    cadence: "daily",
    status: "paused",
    difficulty: "medium",
    description: "Keep the first focus block free of phone checks.",
    rewardAmount: 5,
    progressCurrent: 0,
    progressTarget: 1,
    progressLabel: "0 / 1 · paused",
    linkedArea: "personal",
    dueLabel: "First block",
    nextAction: "Put phone away before starting the block",
    createdByUser: false,
  },
  {
    id: "challenge-learning-sessions",
    title: "3 learning sessions",
    cadence: "weekly",
    status: "active",
    difficulty: "medium",
    description: "Three focused learning sessions with a short note after each.",
    rewardAmount: 10,
    progressCurrent: 2,
    progressTarget: 3,
    progressLabel: "2 / 3 · one left",
    linkedArea: "education",
    dueLabel: "Sunday",
    nextAction: "Plan the final session before the week closes",
    createdByUser: false,
  },
  {
    id: "challenge-strength-trainings",
    title: "2 strength trainings",
    cadence: "weekly",
    status: "active",
    difficulty: "hard",
    description: "Two strength sessions with enough recovery around them.",
    rewardAmount: 12,
    progressCurrent: 1,
    progressTarget: 2,
    progressLabel: "1 / 2 · one training left",
    linkedArea: "health",
    dueLabel: "Weekend",
    nextAction: "Schedule the second training around recovery",
    createdByUser: false,
  },
  {
    id: "challenge-weekly-review",
    title: "Weekly Review completed",
    cadence: "weekly",
    status: "active",
    difficulty: "easy",
    description: "Complete the weekly review and write down the outcome.",
    rewardAmount: 12,
    progressCurrent: 1,
    progressTarget: 1,
    progressLabel: "1 / 1 · ready to complete",
    linkedArea: "review",
    dueLabel: "Today",
    nextAction: "Review finalisieren und Ergebnis notieren",
    createdByUser: false,
  },
  {
    id: "challenge-project-milestone",
    title: "Finish one meaningful project milestone",
    cadence: "monthly",
    status: "active",
    difficulty: "hard",
    description: "Finish one bounded milestone that visibly moves a project.",
    rewardAmount: 18,
    progressCurrent: 1,
    progressTarget: 3,
    progressLabel: "1 / 3 · milestone shaping",
    linkedArea: "work",
    dueLabel: "End of month",
    nextAction: "Define the smallest shippable milestone",
    createdByUser: false,
  },
  {
    id: "challenge-inventory-wishlist",
    title: "Clean inventory wishlist",
    cadence: "monthly",
    status: "draft",
    difficulty: "easy",
    description: "Review wishlist items and remove what is no longer needed.",
    rewardAmount: 8,
    progressCurrent: 0,
    progressTarget: 1,
    progressLabel: "0 / 1 · draft",
    linkedArea: "personal",
    dueLabel: "This month",
    nextAction: "Open inventory and review planned purchases",
    createdByUser: false,
  },
  {
    id: "challenge-source-summaries",
    title: "Read and summarize 2 sources",
    cadence: "monthly",
    status: "completed",
    difficulty: "medium",
    description: "Read two sources and write a concise summary for each.",
    rewardAmount: 14,
    progressCurrent: 2,
    progressTarget: 2,
    progressLabel: "2 / 2 · completed",
    linkedArea: "education",
    dueLabel: "This month",
    completedAt: "2026-06-19",
    nextAction: "Link summaries to Resources",
    createdByUser: false,
  },
];

export const challengeTemplates: ChallengeTemplate[] = [
  {
    title: "10-minute walk",
    cadence: "daily",
    difficulty: "easy",
    description: "Short movement reset without turning it into a workout.",
    rewardAmount: 4,
    progressTarget: 1,
    linkedArea: "health",
    dueLabel: "Today",
    nextAction: "Walk once around the block",
  },
  {
    title: "Inbox zero attempt",
    cadence: "daily",
    difficulty: "medium",
    description: "Clarify a few raw inbox items and reduce visible friction.",
    rewardAmount: 6,
    progressTarget: 4,
    linkedArea: "review",
    dueLabel: "Evening",
    nextAction: "Process four inbox items",
  },
  {
    title: "No phone during first focus block",
    cadence: "daily",
    difficulty: "medium",
    description: "Keep the first focus block protected from phone checks.",
    rewardAmount: 5,
    progressTarget: 1,
    linkedArea: "personal",
    dueLabel: "First block",
    nextAction: "Place phone outside reach",
  },
  {
    title: "Read 20 pages",
    cadence: "weekly",
    difficulty: "easy",
    description: "Read a small amount and capture one useful note.",
    rewardAmount: 6,
    progressTarget: 20,
    linkedArea: "education",
    dueLabel: "This week",
    nextAction: "Choose the source before starting",
  },
  {
    title: "Clean desk reset",
    cadence: "weekly",
    difficulty: "easy",
    description: "Reset the desk surface and remove stale visual clutter.",
    rewardAmount: 5,
    progressTarget: 1,
    linkedArea: "personal",
    dueLabel: "Weekend",
    nextAction: "Clear the desk and put tools back",
  },
];

export const challengeRules = [
  "Specific and small",
  "Measurable completion",
  "Reward must be intentional",
  "No punishment challenges",
  "Rest days are allowed",
];

