import { optionalTrimmedStringSchema, requiredTrimmedStringSchema, z } from "./schema-contract";
import { projectStatuses } from "../domain/project";
const id = requiredTrimmedStringSchema();
const fields = z.object({ projectId: id, logDate: z.string().date(), startedAt: z.preprocess((v) => v === "" ? undefined : v, z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional()), durationMinutes: z.coerce.number().int().positive().max(1440), focus: requiredTrimmedStringSchema(2), outcome: requiredTrimmedStringSchema(2), notes: optionalTrimmedStringSchema });
export const createWorkProjectInputSchema = z.object({ title: requiredTrimmedStringSchema(2), description: optionalTrimmedStringSchema, status: z.enum(projectStatuses).default("active") });
export const updateWorkProjectInputSchema = createWorkProjectInputSchema.extend({ projectId: id });
export const createWorkLogInputSchema = fields;
export const updateWorkLogInputSchema = fields.extend({ logId: id });
export const archiveWorkLogInputSchema = z.object({ projectId: id, logId: id });
export type WorkLogInput = z.infer<typeof createWorkLogInputSchema>;
const workWikiProjectId = z.preprocess((v) => v === "" ? undefined : v, z.string().trim().uuid().optional());
const wikiFields = z.object({ projectId: workWikiProjectId, title: requiredTrimmedStringSchema(2), body: requiredTrimmedStringSchema(2) });
export const createWorkWikiInputSchema = wikiFields;
export const updateWorkWikiInputSchema = wikiFields.extend({ resourceId: id });
export const archiveWorkWikiInputSchema = z.object({ resourceId: id });
const decisionFields = z.object({ projectId: id, decisionDate: z.string().date(), title: requiredTrimmedStringSchema(2), decision: requiredTrimmedStringSchema(2), rationale: optionalTrimmedStringSchema, status: z.enum(["active", "revisited", "superseded"]).default("active") });
export const createWorkDecisionInputSchema = decisionFields;
export const updateWorkDecisionInputSchema = decisionFields.extend({ decisionId: id });
export const archiveWorkDecisionInputSchema = z.object({ decisionId: id, projectId: id });
export type WorkWikiInput = z.infer<typeof createWorkWikiInputSchema>;
export type WorkDecisionInput = z.infer<typeof createWorkDecisionInputSchema>;
const meetingFields = z.object({ projectId: id, meetingDate: z.string().date(), startedAt: z.preprocess((v) => v === "" ? undefined : v, z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional()), durationMinutes: z.coerce.number().int().positive().max(1440), title: requiredTrimmedStringSchema(2), participants: optionalTrimmedStringSchema, agenda: optionalTrimmedStringSchema, outcome: requiredTrimmedStringSchema(2), notes: optionalTrimmedStringSchema });
export const createWorkMeetingInputSchema = meetingFields;
export const updateWorkMeetingInputSchema = meetingFields.extend({ meetingId: id });
export const archiveWorkMeetingInputSchema = z.object({ meetingId: id, projectId: id });
export const linkWorkMeetingFollowupInputSchema = z.object({ meetingId: id, taskId: id });
export const unlinkWorkMeetingFollowupInputSchema = z.object({ relationId: id, meetingId: id });
export const createWorkMeetingFollowupInputSchema = z.object({ meetingId: id, title: requiredTrimmedStringSchema(2), description: optionalTrimmedStringSchema });
export type WorkMeetingInput = z.infer<typeof createWorkMeetingInputSchema>;
